feat(CO-367): add carbonioMeshCredentials value
Zextras/carbonio-mailbox pull request #102
Opened 2022-09-30 14:31 UTC by Polpetta

2022-09-30 14:32 UTC, Polpetta commented
Before you ask, I dunno why all the spaces where trimmed, I just pasted my code at the end of the file

2022-09-30 15:32 UTC, frisonisland approved these changes

2022-10-03 08:50 UTC, keshavbhatt requested changes
Suggested change in attribute description, and requested to run the java code generator to complete this addition.

2022-10-03 08:50 UTC, keshavbhatt commented on store/conf/attrs/attrs.xml
> +  <desc>Carbonio base64 tarball credentials for Mesh service</desc>
Let's make it more meaningful :)
```suggestion
  <desc>Carbonio mesh service credentials as base64 string</desc>
```

2022-10-04 13:42 UTC, Polpetta commented
I've updated the generated Java classes!

2022-10-06 07:06 UTC, keshavbhatt approved these changes
To avoid code rearrangement on generated classes, you can skip running the Google Java Formatter (one of our pre-commit hooks). But everything should be fine even with that, just to avoid huge changes. I dont know why we dont get same output everytime with it.

2022-10-06 07:09 UTC, frisonisland commented
> To avoid code rearrangement on generated classes, you can skip running the Google Java Formatter (one of our pre-commit hooks). But everything should be fine even with that, just to avoid huge changes. I dont know why we dont get same output everytime with it.

I think it's time we think about not including generated classes in src and add some tests on them to check we get the default values we want ;)

2022-10-06 07:13 UTC, keshavbhatt commented
> > To avoid code rearrangement on generated classes, you can skip running the Google Java Formatter (one of our pre-commit hooks). But everything should be fine even with that, just to avoid huge changes. I dont know why we dont get same output everytime with it.
> 
> I think it's time we think about not including generated classes in src and add some tests on them to check we get the default values we want ;)

Yeah, in maven build we set the code generator to run everytime time the compile happen, i noticed the output remain same unless the attrs.xml is modified(which is good).
You mean tests for AttributeManager utility right?

2022-10-06 07:16 UTC, frisonisland commented
> > > To avoid code rearrangement on generated classes, you can skip running the Google Java Formatter (one of our pre-commit hooks). But everything should be fine even with that, just to avoid huge changes. I dont know why we dont get same output everytime with it.
> > 
> > 
> > I think it's time we think about not including generated classes in src and add some tests on them to check we get the default values we want ;)
> 
> Yeah, in maven build we set the code generator to run everytime time the compile happen, i noticed the output remain same unless the attrs.xml is modified(which is good). You mean tests for AttributeManager utility right?

Exactly! But I noticed the output does not match our lint rules, so each time it proposes me to push ZAttr classes, then runs the hook, fails, and then the files are formatted back as the origin.

2022-10-06 07:47 UTC, merged

2022-10-06 10:38 UTC, keshavbhatt commented
> I'm too for not committing generated code, I mean as long as it is exactly generated I don't see any reason to commit it +1 For now I'll merge as it is

Yes I agree, the reason why we need to commit it is beacuse it is part of the source code and required by other packages within mailbox, other projects to successfully build.