feat: [CO-436] make proxyconfgen download domain certificates
Zextras/carbonio-mailbox pull request #115
Opened 2022-11-07 15:21 UTC by Polpetta

Upon `proxyconfgen` run, the certificates are now taken from LDAP and downloaded in `/opt/zextras/conf/domaincerts` but only if the domain has at least one `virtualHostname` set.

2022-11-07 15:35 UTC, frisonisland commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +          "Unable to remove broken certificates before downloading new ones from LDAP");
Consider switch "broken" for "old". I got that "broken" is because they cannot be removed, but it may seem also that certificates content is broken.

2022-11-07 15:43 UTC, frisonisland requested changes
I just left a couple of comments, I would like to check other options in case of process failure before proceeding!

2022-11-07 15:43 UTC, frisonisland commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException("Unable to write down certificates for domain " + domainName, e);
What if we delete the files and the write fails? 
Do you think doing a backup of the files (e.g.:with .bkp extension) , writing new one, then deleting or restoring the backup, based on operation success, would be a better idea?

2022-11-08 07:44 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +        || (privateKeyFile.exists() && !privateKeyFile.delete())) {
consider using java.nio.file.Files#delete for deletion as it better indicates the cause of the failure in exception.

2022-11-08 07:49 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException("Unable to write down certificates for domain " + domainName, e);
I agree, It would be preferable if the entire change operation could be reversed in the case of any failure.

2022-11-08 07:53 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +  public static void downloadDomainCertificate(
Add javadoc.

2022-11-08 08:00 UTC, keshavbhatt requested changes

2022-11-08 08:00 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +              downloadDomainCertificate(domainName, certificate, privateKey);
Can we move this out of this method? 
**why:** this method `List<DomainAttrItem> loadDomainReverseProxyAttrs()` by definition looks like should just return list of attributes and do nothing.

2022-11-08 09:05 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException("Unable to write down certificates for domain " + domainName, e);
I mean, they already decided to overwrite them when uploading new certificates in the admin UI interface, so I think this backup thingy should be done at LDAP level, not when regenerating the nginx configuration...it's already too late here imho

2022-11-08 10:48 UTC, keshavbhatt commented
Also add a dry-run check conditional to prevent this from being executed with the -n option.

2022-11-08 11:04 UTC, frisonisland requested changes

2022-11-08 11:04 UTC, frisonisland commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
@Polpetta sorry, I think we have to move the certificates back :sweat_smile: otherwise Nginx won't be able to load them!
I would apply this logic:

- if ok remove backup files
- if fails put them back

2022-11-08 14:42 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
I'd relly avoid doing the rollback otherwise the codebase will be a mess :(

2022-11-08 14:43 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
I'd have to do stuff inside a `catch` block :(

2022-11-08 14:46 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
And the operation could still fail if, for instance, the machine has run out of space

2022-11-08 14:55 UTC, frisonisland commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
Understood...what about just writing new content to files instead of deleting them? We'll also have less code. 
See the append option: https://docs.oracle.com/javase/8/docs/api/java/io/FileOutputStream.html#FileOutputStream-java.io.File-boolean-
The file permission thing is a corner case that should not happen anyway in a normal system.

2022-11-08 15:15 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +        || (privateKeyFile.exists() && !privateKeyFile.delete())) {
I used `Files.move` to backup the previous file

2022-11-08 15:15 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +  public static void downloadDomainCertificate(
Done!

2022-11-08 15:15 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +              downloadDomainCertificate(domainName, certificate, privateKey);
This is now outdated

2022-11-08 15:16 UTC, Polpetta commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
I did it anyway I feels sorry for the next dude that will see another try inside a catch block :D

2022-11-08 15:16 UTC, Polpetta commented
@keshavbhatt @frisonisland we updated the PR please check again

2022-11-08 15:20 UTC, frisonisland commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +      throw new ProxyConfException(
It will be probably me :D not sure if vavr would have helped

2022-11-08 15:21 UTC, frisonisland approved these changes

2022-11-09 08:06 UTC, keshavbhatt requested changes
added few suggestion, everything else looks good to me. 
unit tests are still missing.

2022-11-09 08:06 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +   * creates a backup of the old one
```suggestion
   * This method backs up existing certificate and private key files for the given domain before creating
   * new ones and populating them with the new data. Backup files gets restored if the transaction fails.
```

2022-11-09 08:06 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +   * @throws ProxyConfException if something goes wrong :)
remove emoji :D

2022-11-09 08:06 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +  public static void writeDownCertificate(String domainName, String certificate, String privateKey)
consider naming this method `updateDomainCertificate`

2022-11-09 08:06 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +  private static void createFolder(String folderPath) throws ProxyConfException {
if you think this utility method is too generic move it to `com.zimbra.cs.util.proxyconfgen.Utils`

2022-11-09 10:22 UTC, keshavbhatt approved these changes
LGTM

2022-11-17 10:24 UTC, merged