fix: [CO-464] only upload cert and private key if they have value
Zextras/carbonio-mailbox pull request #124
Opened 2022-11-22 08:45 UTC by aheeva-yuliya

2022-11-22 08:53 UTC, keshavbhatt approved these changes
lgtm

2022-11-22 09:12 UTC, Polpetta approved these changes

2022-11-23 08:41 UTC, frisonisland approved these changes
Ok, makes sense to write them if they are not both empty

2022-11-24 09:11 UTC, frisonisland requested changes
If this is an hotfix let's reopen it from main

2022-11-24 11:02 UTC, closed without merging