chore: soap docs style & buildinfo for soap module
Zextras/carbonio-mailbox pull request #144
Opened 2023-01-24 09:35 UTC by keshavbhatt

**What has changed:**

- **fix: generate, package buildinfo class**
    - Now generate and package buildinfo class for soap module in respective mvn phases.
    - This also accomodate the soap docs generator to have correct build info version in the generated files

- **fix: properly set anchor scroll offset**
    -  Now offsets html anchors according to the height of fixed header

2023-01-24 10:14 UTC, Polpetta approved these changes
I think it is fine. I left a comment just to clarify a doubt

2023-01-24 10:14 UTC, Polpetta commented on soap/ant-generate-soap-docs.xml
> +    <javac includeantruntime="false" destdir="${build.classes.dir}" debug="true"
`debug="true"` are you sure about it?

2023-01-24 10:30 UTC, keshavbhatt commented on soap/ant-generate-soap-docs.xml
> +    <javac includeantruntime="false" destdir="${build.classes.dir}" debug="true"
Thanks for pointing this out. I think we can get rid of it, as it is set to "off" by default

 **according to:**
https://ant.apache.org/manual/Tasks/javac.html

> debug
> Indicates whether source should be compiled with debug information. If set to off, -g:none will be passed on the > command line for compilers that support it (for other compilers, no command line argument will be used). If set > to true, the value of the debuglevel attribute determines the command line argument.

2023-01-24 10:34 UTC, aheeva-yuliya approved these changes

2023-01-25 09:22 UTC, frisonisland requested changes

2023-01-25 09:22 UTC, frisonisland commented on soap/pom.xml
> +                  <target name="generate-sources"/>
This execution will run generate-sources ant target. I suggest just executing the specific task generate-buildinfo.

2023-01-25 09:22 UTC, frisonisland commented on soap/ant-generate-soap-docs.xml
> +  <target name="generate-sources" depends="generate-buildinfo"/>
Why define a task called generate-sources that only calls another task?
To keep low maintenance I suggest using just generate-buildinfo or we will end up having too many ant task that are difficult to track down.
Or "generate-sources" could make sense if it collects multiple task for example.
What do you say?

2023-01-25 13:11 UTC, keshavbhatt commented on soap/pom.xml
> +                  <target name="generate-sources"/>
My idea was to wrap all sourece code generation releated tasks under this. Easy to look for from maven phase pov.

2023-01-25 13:12 UTC, keshavbhatt commented on soap/ant-generate-soap-docs.xml
> +  <target name="generate-sources" depends="generate-buildinfo"/>
I agree with that, the idea was to also put other soruce code generation readted task depend on this, so from maven side we set biding for generate-sources ant task :)

2023-01-25 13:28 UTC, frisonisland commented on soap/ant-generate-soap-docs.xml
> +  <target name="generate-sources" depends="generate-buildinfo"/>
Ok, keep in mind that maven has multiple generate-source task anyway, with different ids.
I agree with the idea of defining on "generate-sources" on ant tasks, maybe let's see if we can collect the generate-buildinfo and generate-soap-api in one task?

2023-01-27 12:49 UTC, frisonisland approved these changes
Ok to me! Consider updating the PR description if we don't need the BuildInfoGenerated class!

2023-01-27 13:23 UTC, merged