feat: [CO-526] prevent delegated admins creating DDLs
Zextras/carbonio-mailbox pull request #145
Opened 2023-01-27 08:18 UTC by keshavbhatt

**What has changed:**
- prohibit delegatedAdmins from creating dynamic distribution list using CreateDistributionList SOAP command
    - Now throws ServiceException when a delegatedAdmin requests to create dynamic distribution list

2023-01-27 08:49 UTC, Polpetta requested changes
Check the comment I left :call_me_hand:

2023-01-27 08:49 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/service/admin/CreateDistributionListTest.java
> +    final CreateDistributionList createDistributions = spy(CreateDistributionList.class);
You can use a real object here, no need to spy

2023-01-27 08:54 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/admin/CreateDistributionListTest.java
> +    final CreateDistributionList createDistributions = spy(CreateDistributionList.class);
I agree. the issue is: with real object it fails causing issues on `checkDomainRightByEmail` inside handle.

2023-01-27 11:51 UTC, frisonisland requested changes

2023-01-27 11:51 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/service/admin/CreateDistributionListTest.java
> +  private static Provisioning provisioningSpy;
What about not spying the Provisioning? I remember we achieved the result without needing to spy in old tests

2023-01-27 13:12 UTC, frisonisland approved these changes
Sorry, no need to block for a spy, just check if it can be done by calling the real Provisioning

2023-01-27 13:29 UTC, keshavbhatt commented
> Sorry, no need to block for a spy, just check if it can be done by calling the real Provisioning

@frisonisland I already checked :)  Provisioning::createGroup method involved in the handler requires real provisioning backend, since its a unit test i skipped setting up full fledged provisioning backend. I think spy is the best way to achieve this since only this methos is stubbed whole provisioning is intact and used whenever required.

2023-01-30 08:37 UTC, aheeva-yuliya approved these changes

2023-01-30 08:54 UTC, Polpetta approved these changes

2023-01-30 11:04 UTC, merged