fix: [CO-491] caldav schedule agent client and none
Zextras/carbonio-mailbox pull request #153
Opened 2023-02-09 11:21 UTC by frisonisland

### Goal
When the client sends a CalDAV request with SCHEDULE-AGENT=CLIENT, the server should not send a message for the meeting.

### What's changed

* Added support for SCHEDULE-AGENT=CLIENT (no scheduling)
* Added support for SCHEDULE-AGENT=NONE (no scheduling)

2023-02-10 15:17 UTC, keshavbhatt commented on common/src/main/java/com/zimbra/common/calendar/ZCalendar.java
> +  public static enum ScheduleAgent {
remove static keyword, its static by default.

2023-02-10 15:36 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/dav/caldav/AutoScheduler.java
> +        if (Objects.equals(attendee.getScheduleAgent(), "CLIENT")
instead of hardcoding CLIENT and NONE (which quickly makes no sense) consider using already defined constants in ScheduleAgent enum.

2023-02-10 15:39 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/dav/caldav/AutoScheduler.java
> +        if (Objects.equals(attendee.getScheduleAgent(), "CLIENT")
Thanks I added them for that very purpose, I forgot to use them :sweat_smile:

2023-02-10 15:46 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public CalendarUser setScheduleAgent(String scheduleAgent) {
consider using already defined ScheduleAgent enum as method parameter instead of string.

2023-02-10 15:53 UTC, keshavbhatt requested changes
I requested few changes to improve code quality.
Everything else looks good.

2023-02-10 16:17 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public CalendarUser setScheduleAgent(String scheduleAgent) {
Ok, the initial idea was just to use it to check values, as the schedule agent on CalendarUser is what we get from the request (if nothing fallbacks to "SERVER") and there could be corner cases like wrong case, etc. so by changing this we should take extra care of parsing the input value. I will change it.

2023-02-13 09:15 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public CalendarUser setScheduleAgent(String scheduleAgent) {
I'm doing some changes, there will be more boilerplate basically

2023-02-13 09:48 UTC, frisonisland commented
Reading https://www.rfc-editor.org/rfc/rfc5545 (https://www.rfc-editor.org/rfc/rfc6638.html extends it) property parameters value are intended to be case-insensitive but this is not covered yet, I will add changes.

2023-02-13 10:07 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public CalendarUser setScheduleAgent(String scheduleAgent) {
> Ok, the initial idea was just to use it to check values, as the schedule agent on CalendarUser is what we get from the request (if nothing fallbacks to "SERVER") and there could be corner cases like wrong case, etc. so by changing this we should take extra care of parsing the input value. For example the value "serVer" cannot be translated to ScheduleAgent, same for null string, do we still want to proceed?
> 
> The alternative is to just accept whatever comes from the client, if it does not match "CLIENT" or "NONE" then it sends the message.

I understand that using the string param will make it flexible but the idea is to follow the RFC. The RFC defines strict rules and conditions that must be followed. And to enforce them we must consider restricting to use constants defined in the ENUM. 

I think it will be simple to handle exceptional cases:
if SCHEDULE-AGENT param does not matches the strictly defined values, we can assume the parameter got wrong value and in that case user SERVER as suggested in RFC. I quote from (https://www.rfc-editor.org/rfc/rfc6638.html#section-7.1 [Page 42]):

>This property parameter MAY be specified on "ORGANIZER"
      or "ATTENDEE" iCalendar properties.  In the absence of this
      parameter, the value "SERVER" MUST be used for the default
      behavior.

2023-02-13 10:16 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public CalendarUser setScheduleAgent(String scheduleAgent) {
Agree, also since it is case-insensitive it makes more sense at this point to map the value to a state of Schedule-Agent to avoid issues.

2023-02-13 12:59 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
Why this is required?

2023-02-13 13:03 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
Because we need to translate the incoming request to ScheduleAgent for ZOrganzier and ZAttendee.
I could have done it in a private method of Invite.java class, but that would have meant to implement such method each time converting case-insensitive pops up, so I thought better add it to the enum.

2023-02-13 13:07 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
Plus using .valueOf() parses only case-sensitive inputs and throws exception if provided value is not in enums so it does not cover the scenario.

2023-02-13 13:11 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
What if this method gets arbitary string that is not covered by the enum? I dont see no default case. :confused:

2023-02-13 13:12 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
It returns null at the end! I can add the default, np

2023-02-13 13:13 UTC, keshavbhatt requested changes

2023-02-13 13:13 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/calendar/CalendarUser.java
> +  public void setScheduleAgentFromString(String scheduleAgent) {
This is throwing IllegalArgumentException. Please add a unit test for this method to confirm possible edge cases.

2023-02-13 13:25 UTC, keshavbhatt approved these changes
lgtm.

2023-02-13 13:37 UTC, Polpetta approved these changes

2023-02-13 14:17 UTC, frisonisland commented
I won't make other code changes since everyone approved, but will add some new tests to Invite class since it was never covered.

2023-02-14 08:23 UTC, merged