feat: [CO-335] Add issue LetsEncrypt certificate SOAP API Endpoint and related handler
Zextras/carbonio-mailbox pull request #154
Opened 2023-02-09 11:25 UTC by aheeva-yuliya

2023-02-09 13:21 UTC, frisonisland requested changes
I left some comments on the RemoteCertbot class about design and naming.
Also please add tests for it to see how the command builds and executes!

2023-02-09 13:21 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +public class RemoteCertbot {
Consider renaming this class to RemoteCertbotCmd or RemoteCertbotCommand since it has the "execute" method.
Also I would consider instantiating the class through a factory method.
Reason is I would avoid running execute before creating the command, or is it a safe option?

2023-02-09 13:21 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCommands.java
> +    public static final String CERTBOT_DRY_RUN = "certbot dryrun";
Are this only for certbot? Maybe it's better to move them to RemoteCertbot, what do you say?

2023-02-10 13:23 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +public class RemoteCertbot {
Ok i renamed it, and added tests for createCommand, execute commnad totally done by remote manager i dont want to write tests for remote manager lol 
about safe option from my point of view its safe bcz its gonna add --dry-run flag and you will just see the result from your execution 
It will show you command you are executing and a message in case of failure -> if you executing random stuff -> you getting a messaging what you are executing random stuff

2023-02-10 13:24 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCommands.java
> +    public static final String CERTBOT_DRY_RUN = "certbot dryrun";
i left it there bcz there remote manager knows where to look for it 
if i move it to certbot class i will have to tell where to find this command and its just duplication of code

2023-02-10 13:42 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +public class RemoteCertbot {
Sorry, but was "execute" ever a void method? **I think I got it wrong. If execute accepts a command then RemoteCertbot as class name is a good choice and not my proposal.**
I see now that you defined createCommand to create a String command and execute to accept it, thought it was different when I reviewed it.

2023-02-10 13:50 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +public class RemoteCertbot {
ok

2023-02-13 08:38 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +public class IssueCertRequest extends AdminAttrsImpl {
Why we are extending AdminAttrsImpl:question:

2023-02-13 08:42 UTC, keshavbhatt commented on common/src/main/java/com/zimbra/common/soap/AdminConstants.java
> +  public static final String A_CHAIN = "chain";
ChainType will be better name, I got confused looking this attribute thinking why we need to pass chain in request which will issue a certificate.

2023-02-13 08:47 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   * @zm-api-field-description could be passed zero or one argument - "short". If an argument is
> If an argument is

replace with "If the argument is ..."

>it will try to issue

"it" who?

>in any other cases

Please mention what are those other cases, its confusing.

2023-02-13 08:49 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   */
This comment is hard to understand, please rephrase it clearly mentioning the intension what this attribute will do.

2023-02-13 08:53 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +  private static final String AGREEMENT = "--agree-tos --email";
`--agree-tos` and `--email <email address>` are two different parameters/options in the command please split this constant accordingly.

2023-02-13 09:11 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +          "Domain with id " + domainId + " must have PublicServiceHostname and VirtualHostName.",
The error message is misleading, and does not matches with the condition we checking. 
We doing checks with OR while asking to have both paramaters fullfilled using "and" in out message.

Please match the condition and update the exception message according to our requirements.

2023-02-13 09:23 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    }
>Optional<Server> optionalServer =
>       prov.getAllServers()
>          .stream()
>         .filter(Server::hasProxyService)
>        .findFirst();

Instead of getting Optional of server why dont we get the server object and operate on that directly (will avoid  repeatative Optional::Get calls)?
Also rename the variable to something more meaningful like `proxyServer`.


>throw ServiceException.NOT_FOUND("Server with carbonio-proxy node could not be found.");

 Make this message more meaningful by explaining why we require proxy server. The user has now clue why this command suddenly need a proxy server with current error message.

2023-02-13 09:26 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +        "Issuing a LetsEncrypt cert for domain " + domainId + " result: " + result);
This log message implies that certificate is still being issued. Please refactor it to suggest that execution has finished appending the result.

2023-02-13 09:32 UTC, keshavbhatt requested changes
Added few suggestions and questions, with those fixes in place PR looks good to me for now.

2023-02-13 10:26 UTC, aheeva-yuliya commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +public class IssueCertRequest extends AdminAttrsImpl {
bcz of copy paste

2023-02-13 10:39 UTC, Polpetta requested changes
I've put some things that need to be changed and some code-suggestion to make the code cleaner

2023-02-13 10:39 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    }
Let's make our codebase more 2023 java style yo :sunglasses: 
```suggestion
    final Domain domain = Optional.ofNullable(prov.get(DomainBy.id, domainId)).orElseThrow(() -> ServiceException.INVALID_REQUEST(
          "Domain with id " + domainId + " could not be found.", null));
```

Less cleaner code :wink:

2023-02-13 10:39 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    RemoteManager remoteManager = RemoteManager.getRemoteManager(optionalServer.get());
Another kung-fu java functional style :call_me_hand: 

```suggestion
    final RemoteManager remoteManager =
        prov.getAllServers()
            .stream()
            .filter(Server::hasProxyService)
            .findAny() // just find the first suitable, faster search
            .map(server -> {
                  ZimbraLog.rmgmt.info("Issuing a LetsEncrypt cert for domain " + domainId);
                 return RemoteManager.getRemoteManager(server);
            })
            .orElseThrow(() -> ServiceException.NOT_FOUND("Server with carbonio-proxy node could not be found."))
```

2023-02-13 10:39 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/rmgmt/RemoteCertbotTest.java
> +  private final String[] virtualHostName = {"virtual1.test.demo.zextras.io", "virtual2.test.demo.zextras.io"};
Are these values necessary for the test execution? Or can they be changed from `[...].test.demo.zextras.io` to something more agnostic like `example.com`?

2023-02-13 10:39 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/rmgmt/RemoteCertbotTest.java
> +  private final String mail = "admin@test.demo.zextras.io";
Same for this. Can be checked for `admin@example.com`?

2023-02-13 10:39 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/service/admin/IssueCertTest.java
> +  private final String mail = "admin@test.demo.zextras.io";
Same stuff of other tests

2023-02-13 10:57 UTC, keshavbhatt requested changes

2023-02-13 10:57 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   *     By default the chin type is "long". If an admin user pass zero, "long" or random text with
fix typo "chin"

2023-02-13 11:03 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   *     By default the chin type is "long". If an admin user pass zero, "long" or random text with
Why we need to explain each possible condition here just to tell the default value is long for this attribute?

2023-02-13 11:11 UTC, aheeva-yuliya commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   *     By default the chin type is "long". If an admin user pass zero, "long" or random text with
@keshavbhatt you asked it with this "Please mention what are those other cases, its confusing."

2023-02-13 11:14 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    RemoteManager remoteManager = RemoteManager.getRemoteManager(optionalServer.get());
i dont wanna do this kung-fu it needs to be surrounded with try catch for remote manager

2023-02-13 11:14 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +      throw ServiceException.INVALID_REQUEST(
INVALID_REQUEST is not a correct exception here and in few other places. Consider using correct one like FAILURE etc.

2023-02-13 11:22 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   *     By default the chin type is "long". If an admin user pass zero, "long" or random text with
> @keshavbhatt you asked it with this "Please mention what are those other cases, its confusing."

@aheeva-yuliya I asked because in the previous converstation java doc comment was talking about some unknown cases, I doubt we need to worry about unknown cases unless necessary(in this case), we simply need to document what will be the default in case the attribute is not passed at all.

2023-02-13 11:25 UTC, keshavbhatt requested changes
Use correct ServiceException methods to reflect the real exception cause.

2023-02-13 11:25 UTC, aheeva-yuliya commented on soap/src/main/java/com/zimbra/soap/admin/message/IssueCertRequest.java
> +   *     By default the chin type is "long". If an admin user pass zero, "long" or random text with
@keshavbhatt ok

2023-02-13 11:33 UTC, keshavbhatt requested changes

2023-02-13 11:33 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +            .orElseThrow(() -> ServiceException.NOT_FOUND(
replace this with more generic FAILURE. 
NOT_FOUND is not intended to report this type of situations :confused:

2023-02-13 13:04 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    RemoteManager remoteManager = RemoteManager.getRemoteManager(optionalServer.get());
Maybe I'm missing something, but I don't see any try/catch block in the method body :thinking:

2023-02-13 13:38 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    RemoteManager remoteManager = RemoteManager.getRemoteManager(optionalServer.get());
Fixed irl

2023-02-13 14:08 UTC, Polpetta approved these changes
lgtm

2023-02-13 15:33 UTC, keshavbhatt approved these changes

2023-02-13 15:35 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +                + "Be sure carbonio-proxy is installed, up and running."));
Consider changing to:
```suggestion
                "Issuing LetsEncrypt certificate command requires a carbonio-proxy node. "
                + "Make sure a carbonio-proxy node is installed, up and running in your infrastructure."));
```

2023-02-13 15:38 UTC, frisonisland approved these changes
Changes are ok to me, consider slightly changing the exception message regarding carbonio-proxy node.

2023-02-13 15:39 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +                + "Be sure carbonio-proxy is installed, up and running."));
Also, we dont need to specify "node" keyword. The install could be single server and maybe for some weird reasons server could have missing "proxy" in enabled services.

2023-02-13 15:42 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +                + "Be sure carbonio-proxy is installed, up and running."));
Ok then just 
```suggestion
                "Issuing LetsEncrypt certificate command requires carbonio-proxy. "
                + "Be sure carbonio-proxy is installed, up and running."));
```
should be fine :slightly_smiling_face: 

or

```suggestion
                "Issuing LetsEncrypt certificate command requires carbonio-proxy service to be available. "
                + "Be sure carbonio-proxy is installed, up and running."));
```

2023-02-14 10:36 UTC, merged