feat: [CO-611] prom mailbox process stats
Zextras/carbonio-mailbox pull request #172
Opened 2023-03-09 14:19 UTC by frisonisland

2023-03-10 13:20 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/servlet/MetricsServletModule.java
> +   * @param collectorRegistry thge registry holding collectors
```suggestion
   * @param collectorRegistry the registry holding collectors
```

2023-03-10 13:37 UTC, keshavbhatt requested changes
Changes looks good to me, 

**Only concerns:**
- What about the JMX metrics collection that is already in place? Having two different mechanism to do same task will imapct the performance for sure. I will remove the existing JXM one and all related logic to avoid the overhead. 
- What about removing the exisitng .prom stat collection? I think we should get rid of that too.
- Also if we want to keep the .csv based jxm scrapped stats, consider migrating it to use stats scraped from this one.

2023-03-10 13:42 UTC, frisonisland commented
> Changes looks good to me,
> 
> **Only concerns:**
> 
> * What about the JMX metrics collection that is already in place? Having two different mechanism to do same task will imapct the performance for sure. I will remove the existing JXM one and all related logic to avoid the overhead.
> * What about removing the exisitng .prom stat collection? I think we should get rid of that too.
> * Also if we want to keep the .csv based jvm stats, consider migrating it to use stats scraped from hotspot.

I would propose removing the existing mechanism, although it would be hard to integrate the new system with the CSV, because the old legacy code does not use injection. I don't see the point in having the csv file.
Also the new code is a sort of a blackbox: we use prometheus client libraries to do the magic, for getting source data to outputting, there is no parsing logic.

What do you think?

2023-03-10 14:04 UTC, keshavbhatt commented
> I don't see the point in having the csv file

Same here, just remove them.

2023-03-13 09:09 UTC, aheeva-yuliya approved these changes

2023-03-14 14:17 UTC, Polpetta approved these changes

2023-03-14 14:18 UTC, Polpetta commented
I'd keep everything as KISS as possible

2023-03-14 14:25 UTC, keshavbhatt approved these changes

2023-03-14 15:39 UTC, merged