feat: [CO 621] Allow LE certificates to be generated from Mailbox endpoint
Zextras/carbonio-mailbox pull request #175
Opened 2023-03-13 13:00 UTC by aheeva-yuliya

2023-03-24 09:44 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/MailSender.java
> +     * @since 23.4.0
Remember to put 23.5.0 ;)

2023-04-03 08:15 UTC, frisonisland requested changes

2023-04-03 08:15 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, Object> createIssueCertNotificationMap(
What is the goal of this method? To add from: and to: in form of map? Asking because it seems a bit generic, also all values are String but we return a Map of <String,Object> and later cast again to String.
I suggest to return String, not Object if we deal with only Strings. 
Edit: I see it deals with lists. Maybe we can create a method for each thing you need (I don't like casting :slightly_smiling_face: ).
Something like: 
- List<String> getRecipients(Domain domain)
- String getNotificationSender(Domain domain), etc. 
We could return Optionals also.

2023-04-03 08:15 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/MailSender.java
> +    }
Is this safe? What I mean is I don't like the ability to change the session after some operation are already done. 
Also I don't see the need of creating a MailSender without session, consider creating a factory method and a private constructor with session and hosts maybe. What do you think?

2023-04-03 09:22 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/mailbox/MailSender.java
> +    }
if you check MailSender it has  public MailSender setSession(Account account) which is the same as this one
im getting requested mailsender from the mailbox by providing the domain 
it is the same logic as SendMsg handler doing but there is getting it based on account

2023-04-03 09:27 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, Object> createIssueCertNotificationMap(
the goal of this method is to undersnad which message to which recipients should be sent
bcz we need to send some messages for domain recipients and some only to global
it deals with string and string[] 
i will think mb of little refactor to avoid casting ok

2023-04-03 10:03 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/mailbox/MailSender.java
> +    }
Ok! Then I have an issue the original approach :sweat_smile: 
I think the session should be final, consider adding a "TODO: make session final to avoid issues" if you think it could lead to problems.

2023-04-03 10:27 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, Object> createIssueCertNotificationMap(
@frisonisland i've refactored it No more casting  slightly_smiling_face

2023-04-03 11:14 UTC, frisonisland requested changes
I think the whole map logic is a bit confusing. Maybe consider a more streamlined version where you just do, from the notify:
- parse output
- create  global mime message
- create domain mime message
- send both messages using the same sender
This way we avoid having if conditions in the same method to handle domain and global case.
it is also easier to spot the wanted behavior.

2023-04-03 11:14 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +   * Creates {@link javax.mail.internet.MimeMessage} list what would be sent to recipients.
The method, if I got it, creates  a global message and a domain message, if present. We should state it in the description. It's not clear if we always set global and domain message or we can end up having only the domain message because of the catch() logic. Th subject is the same for both emails, right?

2023-04-03 11:48 UTC, keshavbhatt requested changes
I added some suggestions and requested some changes.

2023-04-03 11:48 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +    // only global admin would be notified
How this comment is relevant here? :eyes:

2023-04-03 11:48 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +    throw new RuntimeException("CertificateNotificationManager class cannot be instantiated.");
```suggestion
    throw new UnsupportedOperationException("CertificateNotificationManager class cannot be instantiated.");
```

2023-04-03 11:48 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/admin/IssueCertTest.java
>      assertEquals(message.getAttribute(A_DOMAIN), domainName);
```suggestion
    assertEquals(domainName, message.getAttribute(A_DOMAIN));
```
correctly order expected and actual values.

2023-04-03 11:48 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/admin/IssueCertTest.java
> +    assertEquals(message.getText(), IssueCert.RESPONSE);
```suggestion
    assertEquals(IssueCert.RESPONSE, message.getText());
```
correctly order expected and actual values.

2023-04-03 11:56 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, String> createIssueCertNotificationMap(
Also, `protected` makes no sense here, as this utility class is not ment to be subclassed (to enforce this add `final` in class definition). Then we can remove protected and make it package private by  just defining it like:
`static Map<String, String> createIssueCertNotificationMap(){}` ...

2023-04-03 12:03 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, String> createIssueCertNotificationMap(
IMHO not even package private, this is not meant to be shared. Ok protected in case we need to change its behavior (but I assume not/does not make sense)

2023-04-03 12:39 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +          + " the certificator must be able to resolve and browse the FQDN provided.\n"
it was provided by luca and danielle, but i will change

2023-04-03 13:37 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +    Session session = sender.getCurrentSession();
ok will get an object of CertificateNotificationManager

2023-04-03 13:44 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static List<MimeMessage> createMimeMessageList(
ok getting an object

2023-04-03 14:22 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  protected static Map<String, String> createIssueCertNotificationMap(
changed it

2023-04-03 14:23 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +    throw new RuntimeException("CertificateNotificationManager class cannot be instantiated.");
outdated

2023-04-03 15:46 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  public void notify(String outputMessage) {
Just one thing about this method: I think DOMAIN_MESSAGE and GLOBAL_MESSAGE do not add anything to the logic, instead they are not necessary and lead to double conditions, e.g.: 
- _if failure -> add DOMAIN_MESSAGE, if DOMAIN_MESSAGE add domain mime message_ 
VS 
- _if failure -> add mime message_.

I suggest also:
```java
/**
   * Notifies global and domain recipients about certificate generation result.
   * In case of failure only global admin receives the message.
   * In case of certbot failure both global and domain admin should receive the status message
   * In case of success global admin receives the message and domain admin receives it only if certbot request was completed.
   *
   * @param outputMessage a message returned by RemoteManager/Certbot acme client
   */
  public void notify(String outputMessage) {
    String domainName = domain.getName();

    ZimbraLog.rmgmt.info(
        "Issuing LetsEncrypt cert command for domain "
            + domainName
            + " was finished with the following result: "
            + outputMessage);


    try {
      Config config = Provisioning.getInstance().getConfig();
      String globalFrom =
          Optional.ofNullable(config.getCarbonioNotificationFrom())
              .orElseThrow(
                  () ->
                      ServiceException.FAILURE(
                          "Global CarbonioNotificationFrom attribute is not present.", null));
      String[] globalTo =
          Optional.ofNullable(config.getCarbonioNotificationRecipients())
              .orElseThrow(
                  () ->
                      ServiceException.FAILURE(
                          "Global CarbonioNotificationRecipients attribute is not present.", null));
      String domainFrom =
          Optional.ofNullable(domain.getCarbonioNotificationFrom()).orElse(globalFrom);
      String[] domainTo =
          Optional.ofNullable(domain.getCarbonioNotificationRecipients()).orElse(globalTo);

      MailSender sender = mbox.getMailSender(domain);
      List<MimeMessage> mimeMessageList = new ArrayList<>();

      if (outputMessage.contains(SYSTEM_FAILURE)) {
        mimeMessageList.add(createMimeMessage(sender.getCurrentSession(), domain.getName() + SUBJECT_TEMPLATE + SYSTEM_FAILURE,
            convert(globalFrom), convert(globalTo), outputMessage));
      }
      else if (outputMessage.contains(FAIL)) {
        mimeMessageList.add(createMimeMessage(sender.getCurrentSession(), domain.getName() + SUBJECT_TEMPLATE + CERTBOT_FAILURE,
            convert(globalFrom), convert(globalTo), outputMessage));

        mimeMessageList.add(createMimeMessage(sender.getCurrentSession(), domain.getName() + SUBJECT_TEMPLATE + CERTBOT_FAILURE,
            convert(domainFrom), convert(domainTo), createDomainFailureMessage(domain, outputMessage)));
      } else {
        // all ok
        mimeMessageList.add(createMimeMessage(sender.getCurrentSession(), domain.getName() + SUBJECT_TEMPLATE + CERTBOT_SUCCESS,
            convert(globalFrom), convert(globalTo), outputMessage));
        if (outputMessage.contains(RECEIVED)) {
          mimeMessageList.add(createMimeMessage(sender.getCurrentSession(), domain.getName() + SUBJECT_TEMPLATE + SUCCESS_RESULT,
              convert(domainFrom), convert(domainTo), createDomainSuccessMessage(domain, outputMessage)));
        }
      }
      // parse the message, add keys based on message
      sender.sendMimeMessageList(mbox, mimeMessageList);

      ZimbraLog.rmgmt.info(
          "Notifications about LetsEncrypt certificate generation were sent "
              + "for the global and domain "
              + domainName
              + " recipients.");

    } catch (Exception e) {
      ZimbraLog.rmgmt.info(
          "Notifications about LetsEncrypt certificate generation weren't sent "
              + "for the global and domain "
              + domainName
              + " recipients.\n"
              + "Sending failure: "
              + e.getMessage());
    }
  }

  private String createDomainFailureMessage(Domain domain, String outputMessage) {
    return String.join(
        "",
        HEADER,
        FAILURE_RESULT,
        FAILURE_DOMAIN_NOTIFICATION_TEMPLATE.replace("<DOMAIN_NAME>", domain.getName()));
  }
  String expire = "\n";

    String regex = "\\d{4}-\\d{2}-\\d{2}";
    Matcher matcher = Pattern.compile(regex).matcher(outputMessage);
    if (matcher.find()) {
      String expiresTemplate = "This certificate expires on ";
      expire = String.join("",expire, expiresTemplate, matcher.group(), ".");
    }
    return
        String.join(
            "",
            HEADER,
            SUCCESS_RESULT,
            SUCCESS_DOMAIN_NOTIFICATION_TEMPLATE.replace("<DOMAIN_NAME>", domain.getName()),
            expire);

  }
``` 
Again I just think the **parseOutput** is a bit generic in naming + you don't need a map. That approach reminds me of Python :sweat_smile:  
Also explain branches conditions in JavaDoc as it defines the behavior.

2023-04-03 15:50 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +  public void notify(String outputMessage) {
@frisonisland i've already modify it
check my last commit pls

2023-04-04 09:57 UTC, keshavbhatt approved these changes

2023-04-04 10:16 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/rmgmt/RemoteCertbot.java
> +        .thenAccept(notificationManager::notify);
Is there any global thread pool where to exec this task instead of putting it in the default ForkJoinPool? Kinda makes it hard to test

2023-04-04 10:27 UTC, Polpetta requested changes
Some minor details to fix, the implementation seems ok!

2023-04-04 10:27 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/admin/CertificateNotificationManager.java
> +      ZimbraLog.rmgmt.info(
Could be better to issue a warning than an info message?

2023-04-04 10:27 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/mailbox/ContactTest.java
> +        System.out.println("Expected exception was caught: " + e);
In this case, please use the self4j logger that can be customized outside the tests in order to be more or less verbose

`private final Logger log = LoggerFactory.getLogger(this.getClass())` at the beginning of the test run and you're good to log tests how much you want

2023-04-06 12:39 UTC, Polpetta approved these changes

2023-04-06 12:50 UTC, merged