chore: [CO-578] remove DNS/MX record checks
Zextras/carbonio-mailbox pull request #198
Opened 2023-04-12 13:22 UTC by aheeva-yuliya

DNS/MX removal

1. CheckDomainMXRecord request, response, handler, right.

2. attributes: 

- zimbraMtaDnsLookupsEnabled (deprecated)
- zimbraAdminConsoleDNSCheckEnabled (enable MX check feature for domain)
- zimbraDNSCheckHostname (DNS check by customers that configure their MX to point at spam relays or other non-zimbra inbox smtp servers)
- zimbraReverseProxyDnsLookupInServerEnabled (control whether force the server side do the DNS lookup and send the result IP back to proxy)
- zimbraDNSMasterIP (IP Address(es) of the root DNS servers to be used by the DNS cache service)
- zimbraDNSUseTCP (for dns cache, whether or not to use TCP)
- zimbraDNSUseUDP (for dns cache, whether or not to use UDP)
- zimbraDNSTCPUpstream (for dns cache, whether or not to only use TCP when talking to the upstream Master DNS servers)

 and related rights.	
	
3. Unbound DNS resolver config.

Related PRs:
https://bitbucket.org/zextras/carbonio-thirds/pull-requests/20
https://github.com/Zextras/carbonio-build/pull/53

2023-04-13 10:40 UTC, keshavbhatt commented
> * zimbraMtaSmtpDnsSupportLevel (value for postconf smtp_dns_support_level)

Removing this attribute will also impact some other places, zmconfigd may fail check if the we also require to perform cleanup in `carbonio-ldap-utilities/conf/zmconfigd.cf` look for [smtp_dns_support_level](https://www.postfix.org/postconf.5.html#smtp_dns_support_level) postconf attribute.

2023-04-13 10:43 UTC, keshavbhatt commented
> * zimbraMtaSmtpTlsDaneInsecureMXPolicy  (value for postconf smtp_tls_dane_insecure_mx_policy)
>   and related rights.

Same for this one. Check if we require cleanup in `carbonio-ldap-utilities/conf/zmconfigd.cf`

2023-04-13 10:50 UTC, keshavbhatt commented
Check if we still require to provide and maintain `carbonio-unbound` package in carbonio-thrid repository. It seems related and required by this feature.

2023-04-13 11:34 UTC, aheeva-yuliya commented on packages/common-appserver-docs/PKGBUILD
> -    "${pkgdir}/opt/zextras/documentation/postfix-split-domain.md"
I can keep it if you think is usefull 
but it's not gonna be up-to-date anymore

2023-04-13 11:56 UTC, frisonisland commented on packages/common-appserver-docs/PKGBUILD
> -    "${pkgdir}/opt/zextras/documentation/postfix-split-domain.md"
We should discuss about this, but all these docs seems outdated.

2023-04-13 11:59 UTC, frisonisland requested changes
Everything looks ok to me except for unbound.conf.in: it is not clear why we have to remove it

2023-04-13 11:59 UTC, frisonisland commented on packages/common-appserver-conf/PKGBUILD
> -    "${pkgdir}/opt/zextras/conf/unbound.conf.in"
What about this? Why remove it? For what is it needed?

2023-04-13 12:14 UTC, aheeva-yuliya commented on packages/common-appserver-conf/PKGBUILD
> -    "${pkgdir}/opt/zextras/conf/unbound.conf.in"
unbound.conf is used to configure Unbound DNS resolver
Luca asked some people to confirm about attributes i want to remove and probably I want to ask about this (Unbound product and its conf) Tell me if you know it's used or how to check if it's used

2023-04-13 12:30 UTC, frisonisland commented on packages/common-appserver-conf/PKGBUILD
> -    "${pkgdir}/opt/zextras/conf/unbound.conf.in"
If it is not within the boundaries of the PR I would remove it another time. Does it have anything to do with check DNS and MX record?

2023-04-13 13:37 UTC, aheeva-yuliya commented on packages/common-appserver-conf/PKGBUILD
> -    "${pkgdir}/opt/zextras/conf/unbound.conf.in"
@frisonisland @keshavbhatt I've asked Luca about Unbound. He said as far as he knows it is not used. Waiting for confirmation from Lorenzo Fascì Omar Verbi Laurent Francoise about attributes and Unbound if we still have to maintain it.

2023-04-18 11:35 UTC, aheeva-yuliya commented on packages/common-appserver-docs/PKGBUILD
> -    "${pkgdir}/opt/zextras/documentation/postfix-split-domain.md"
@keshavbhatt keeping the doc

2023-04-18 12:21 UTC, aheeva-yuliya commented on packages/common-appserver-conf/PKGBUILD
> -    "${pkgdir}/opt/zextras/conf/unbound.conf.in"
@frisonisland removing the config

2023-04-18 12:25 UTC, aheeva-yuliya commented
I also have this https://github.com/Zextras/carbonio-ldap-utilities/pull/35 but as far as I understood there is no need to open it, right

2023-04-19 10:09 UTC, keshavbhatt commented
> I also have this [Zextras/carbonio-ldap-utilities#35](https://github.com/Zextras/carbonio-ldap-utilities/pull/35) but as far as I understood there is no need to open it, right

should not cause any effect but lets have it to completely get rid of these entries from our codebase. The existance of those files there is already a question as they seems not involved in build process.

2023-04-19 10:09 UTC, keshavbhatt commented on packages/common-appserver-docs/PKGBUILD
> -    "${pkgdir}/opt/zextras/documentation/postfix-split-domain.md"
> but all these docs seems outdated

Not **All** :)

2023-04-19 10:11 UTC, keshavbhatt approved these changes
LGTM, 
Just make sure the new build is tested for integration.

2023-05-08 07:24 UTC, Polpetta approved these changes

2023-05-12 08:42 UTC, merged