Feat/service discover expose
Zextras/carbonio-mailbox pull request #2
Opened 2022-01-17 11:39 UTC by frisonisland

Feature: add service discovery integration for mailbox.

2022-01-17 11:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zextras/carbonio-mailbox?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zextras/carbonio-mailbox?pullRequest=2) before we can accept your contribution.<br/><hr/>**Davide Frison** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zextras/carbonio-mailbox?pullRequest=2) it.</sub>

2022-01-17 11:55 UTC, M0Rf30 approved these changes

2022-01-17 13:05 UTC, keshavbhatt approved these changes

2022-01-17 14:04 UTC, M0Rf30 approved these changes

2022-01-19 11:11 UTC, Polpetta requested changes
Check the name with our Architects, then the rest lgtm

2022-01-19 11:11 UTC, Polpetta commented on packages/appserver-service/PKGBUILD
> +  "pending-setups"
Note coordinate with @davide-baldo or @ZeXtrasJay for the name, since for what I understand `service-discover` maybe not the final name. Same for `pending-setups`

2022-01-24 15:32 UTC, frisonisland commented on packages/appserver-service/PKGBUILD
> +  "pending-setups"
Hey @davide-baldo , thanks for the feedback.
I'll add a service-intention kind definition for the user-management service.

About final naming I think we're all set at this point :)

2022-01-25 09:43 UTC, davide-baldo approved these changes

2022-01-25 09:47 UTC, Polpetta approved these changes
lgtm!

2022-01-25 10:02 UTC, merged

2022-01-25 10:32 UTC, Polpetta commented
@frisonisland please merge commits always following conventional commit convention: https://www.conventionalcommits.org/en/v1.0.0/

2022-01-25 11:08 UTC, frisonisland commented
@Polpetta sorry for the inconvenience, thought I wrote "feat" instead of "Feature".

2022-01-26 10:45 UTC, frisonisland commented
@davide-baldo sorry for pointing it out now, but I think user-management definition is wrong and the service name should be carbonio-user-management. Can you confirm that? I'll open another PR.

2022-01-26 11:37 UTC, davide-baldo commented
> @davide-baldo sorry for pointing it out now, but I think user-management definition is wrong and the service name should be carbonio-user-management. Can you confirm that? Other PR: #6

Yep, it's carbonio-user-management, my bad not using the full form, check out of the service-configurations document in dev guide