feat(SOAP): [CO-185] preview service SOAP endpoint
Zextras/carbonio-mailbox pull request #20
Opened 2022-03-17 13:24 UTC by keshavbhatt

WIP:
- enabled generate previews for mail attachment using Carbonio previewer service based on passed parameters.

2022-03-17 13:54 UTC, frisonisland requested changes

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +public class GetPreview extends MailDocumentHandler {
Hi Keshav, I would add the doc for this class to describe the general idea/usage of it.

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  Element requestElement = null;
I see we are storing the request as instance field, but I would avoid that because it's not clear what would happen on subsequent requests. 
If we take a look at the registration of this handler on the dispatcher it is initialized only one time.
So calling the handle() method multiple times could result in overwriting the request, potentially giving unwanted results.

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getImageParams() {
About this method, as per my comment above about request as field, I would change it to have it the request as parameter. Same can be said about other methods with same logic.

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private static class ServiceResponse {
Also don't know if there is a specific need to make this class private, but I would move it to public and in a standalone file, with javadoc for everything (except setters and getters of course :) )

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private ServiceResponse getAttachment(String itemId, String partNo, String baseURL,
About JavaDoc, I would add it also for private methods.
Reason is in the future if we have to pickup the code again it will be easier to understand what we have to do!

2022-03-17 13:54 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  public static String getServerBaseUrl(Server server, boolean withPort) {
Not sure about this method and why we are using it with (null, false) parameters in field definition.
Also is it to get the url of the Files server/api?
I would either: 
* set serverbaseUrl in class constructor 
* set Server in constructor and maybe call something like serverInstance.getUrl() in the code.
Reason is testability, when we will be able to do it properly in the future this will be easier to do and maintain

2022-03-17 13:57 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +public class GetPreview extends MailDocumentHandler {
Yeah sure.

2022-03-17 14:16 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  Element requestElement = null;
> So calling the handle() method multiple times could result in overwriting the request

The handle method is called by the dispatcher when a request arrives, we don't have to call it.

2022-03-17 14:18 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  public static String getServerBaseUrl(Server server, boolean withPort) {
This is to get the server's base URL where the mailbox is hosted. the first param is a server which if passed as null, we get the local one using provisioning. also the false is to set if we want the baseUrl with port or not. I have slightly modified this for my use case. Similar method signatures can be found in other places where we are trying to get the base URL of the local server.

2022-03-17 14:24 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  Element requestElement = null;
Yes, but it will call the handle() method of the same instance you provided with new()

2022-03-17 15:46 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  Element requestElement = null;
It was just a generic XML Element variable, but I removed it now we passing it as the method's argument.

2022-03-17 15:49 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getImageParams() {
Changes are in place, thanks :)

2022-03-17 15:53 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private ServiceResponse getAttachment(String itemId, String partNo, String baseURL,
Docs are coming soon.

2022-03-21 08:57 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  public static String getServerBaseUrl(Server server, boolean withPort) {
changes are in place. Thanks

2022-03-21 09:20 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  public boolean storeContent(String filename, byte[] content) {
Ok, but keep in mind that when and if we have to use an SDK to call the preview API, the ServiceResponse object will be just a representation of the response, and it won't have logic about storing file, etc.
Having the logic on the GetPreview class it would be allow more decoupling and would be easier to refactor. Just a thought! 
Anyway open the PR when you feel it's ready, other people could provide other/different reasoning, so it's all good :)

2022-03-22 08:28 UTC, frisonisland requested changes

2022-03-22 08:28 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    String itemId = request.getAttribute("itemId", null);
There is a utility method that converts from Element to Class type for request and response object.
I would consider using that for type and compile time checking, so if something changes we know what to change.
It's zc.elementToJaxb method (zc is instance of ZimbraSoapContext in this scope).
To give you an idea: zc.elementToJaxb(request) -> jaxbElement.getItem()

2022-03-22 08:28 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getImageParams(Element requestElement) {
Also here, if we use the ElementToJaxb, remember to reactor it to use GetPreviewRequest.
Also for other methods would be the same (getPdfParams, etc.)

2022-03-22 08:28 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getPdfParams(Element requestElement) {
So in these methods we are parsing the request and returning a query string.
I would consider changing the method to name to something like getPdfParamsAsQueryString or something like that.
Reason is it gives a better idea of what we are doing. 
If we don't want to be this specific (imagine the api changes in the future and we have to provide a JSON string instead of query), we can always provide the description in the JavaDoc.

2022-03-22 11:23 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    String itemId = request.getAttribute("itemId", null);
using the utility class.

2022-03-22 11:24 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getPdfParams(Element requestElement) {
changed the name if method,

2022-03-22 11:26 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  private String getImageParams(Element requestElement) {
we can pass the plain request element below our exception check, otherwise, we will also need SoapContext as a method param. If the request element will be malformed the exception will prevent further execution of this method.

2022-03-23 08:51 UTC, Polpetta requested changes
I've made some comments. I'll check it again once you add the tests too

2022-03-23 08:51 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    Element imageEle = requestElement.getOptionalElement(MailConstants.E_P_IMAGE);
Are you sure this is the most elegant and maintainable way to access elements? I saw in @frisonisland codebase that it seems to be a method called `zsc.elementToJaxb(...)` to get the right request object instance.

This seems that this brings type safety inside this codebase which is always a good thing.

2022-03-23 08:54 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +            requestElement);
Not sure, but we only support pdf and image. In this case, we are letting the preview service decide it, We also have error handling checks if the preview service refuse to generate preview.

2022-03-23 08:58 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +      if (previewType.equals("thumbnail")) {
> This equals should be inverted, if previewType is `null` you get a `NullPointerException`

PreviewType cannot be null, we set it to empty string above. but I will keep the suggestion. Thanks

2022-03-23 09:02 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    return stored;
It's no longer a POJO if we add logic to it, hence it's not a POJO :P 
It's a helper class that is being used in the handle method above.

2022-03-23 09:05 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    }
This is the best way and suits our use-case, Service exception is a valid exception here. I don't see any issue.

2022-03-23 09:07 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    Element imageEle = requestElement.getOptionalElement(MailConstants.E_P_IMAGE);
We already used that in the handle method, if the element was not valid it would have returned an exception there.

2022-03-23 09:07 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +  }
I responded there :P

2022-03-23 09:11 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    origFileName = fileName;
I don't get it. This class has only one responsibility -> manage and provide values returned in the response of services.

2022-03-23 10:01 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    Element imageEle = requestElement.getOptionalElement(MailConstants.E_P_IMAGE);
Ok. The fact is regarding the `getOptionalElement(//ID)` stuff, that we wouldn't have if we converted the object to a request type in the first place. I dunno if I'm able to explain myself. If you want we can chat via call whenever you can :blush:

2022-03-23 10:03 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    origFileName = fileName;
I mean you are doing side effect + doing something else. If you can I'd avoid to change the state of a class while calling a method, if said in a explicit way

2022-03-23 10:10 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    return stored;
You're right, but usually `Response` and `Request` kind of objects are POJOs, other operations on them are handled by other classes. In this way you're coupling a data structure with business logic, making more difficult in the future to maintain/work on them

2022-03-23 10:35 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    return stored;
My man, the first reason why we have this class is to have our object feature which can store the content in a temp location, take it as an intermediator which is adding some extra features to the response we got from the service. Otherwise, I would have used the HTTP response directly. Why I would wrap it into another POJO? I can explain the use case more clearly if you want in a quick call.

2022-03-23 15:57 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +            requestElement);
Solved by irl chat

2022-04-01 10:23 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    origFileName = fileName;
It will not cause any issues, we are just setting the filename, this response object is only modified once. Also, I cannot set the filename without getting the original response hence we cannot set the file in the class constructor while initializing object.

2022-04-01 10:43 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    origFileName = fileName;
Just an update: I agree with @Polpetta on this. Also on an old change request I asked something very similar.
But as I see this class does not only provide values returned by services, but its also doing something on the filesystem hence it's mixing some logic with the data. 
Suggestion: I would have defined the storeContent method in the actual service class, which is GetPreview, and avoided side-effects.

2022-04-01 10:52 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/GetPreview.java
> +    origFileName = fileName;
I am not getting what you are guys talking about? Can we have a call so I can better understand your concerns?
Is the name of the class and what it is doing bothering us here? I am sure if we have named it something else then we would've not discussing this :D

2022-04-06 10:17 UTC, Polpetta approved these changes
LGTM :+1:

2022-04-06 10:30 UTC, merged