chore: merge back to devel
Zextras/carbonio-mailbox pull request #205
Opened 2023-04-20 11:20 UTC by frisonisland

2023-04-20 15:03 UTC, aheeva-yuliya approved these changes

2023-04-24 08:27 UTC, keshavbhatt requested changes
It will be nice to bump artifact version to new snapshot.

2023-04-26 10:16 UTC, frisonisland commented on pom.xml
> +    <revision>23.5.0</revision>
This cannot be done, I have to make another branch from main and then merge it to devel.
Usually we merge back and then make a PR to bump version (23.6.0-SNAPSHOT)

2023-04-26 10:20 UTC, keshavbhatt approved these changes

2023-04-26 11:44 UTC, merged