feat: [CO-675] allow global admin to set PublicServiceHostname and VirtualHostName not compliantt with domain name
Zextras/carbonio-mailbox pull request #220
Opened 2023-05-10 08:13 UTC by aheeva-yuliya

2023-05-12 09:54 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
IMHO we can get along even without this method, because "hasRight" actually is "isAdmin and can modify global config"

2023-05-12 09:55 UTC, keshavbhatt approved these changes
lgtm.

2023-05-12 10:00 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
@frisonisland 
if it's a global admin then it won't even go deeper and check if he really has a right to modify global config bcz he has
if it's a delegated admin then it should go throuh all the chain and really check if he has this right bcz usually they don't have it
i didnt get your point how to get along without this method

2023-05-12 10:01 UTC, keshavbhatt commented
Please limit the length of the title of this PR. :D

2023-05-12 10:03 UTC, frisonisland requested changes

2023-05-12 10:03 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/service/admin/ModifyDomainIT.java
> +  public static final String WITH_RIGHT = "_with_right";
This test class could end up with many other tests, how do you ensure the account you create was not already created, thus making the test fail (potentially)? I would recommend treating each test as individual, with local variables. Consider using UUID for email local part of a user

2023-05-12 10:03 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/service/admin/ModifyDomainIT.java
> +        name + "@" + DOMAIN_NAME,
I wouldn't use a static domain, to avoid conflict with users defined in other tests.
It may work now, but that is because the Provisioning class is not the real one used in production, it's the "Mock" which I found having many issues, such as not checking collision, etc.

2023-05-12 10:14 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
What I mean is the method is used just in one place, to me we could have written the condition inline, without defining this method. Also when will we ever use a method called "hasRight" in other places (in this class)?. The method name suggest a  generic check, and has generic parameters, but the behavior is very specific. 
I expect it to be either:
- "hasAdminRightAndCanModifyConfig)
-  hasRight(Right right)

2023-05-12 10:56 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
@ frisonland i made it as a separate method in order to be able to override it in tests
if i would make it inline then tests for delegated admin will be gone
till now i change the name 
choose 😂 keep it inline or add tests

2023-05-12 11:56 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
@frisonisland i would make it inline ok
but about tests 
i have to mock not an AccessManager but abstract AdminAccessControl or private static ACLAccessControl it's more natural but it's not possible
so removing tests for delegated admin

2023-05-12 12:21 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
Ok, let's not remove tests :smile: 
Unfortunately there is a weird/confusing layout of the classes and no interface. We have to find a way to make this code more digestible while working on it somehow, by: make it non-static, use composition, etc.
For example: AdminDocumentHandler has a static method checkRight() that checks the right and returns current AccessControl instance from AccessManager.getInstance(). 
A solution could be, when creating ModifyDomain, passing AccessManager.getInstance() to the constructor. 
...maybe we can create another ticket on this.

2023-05-12 12:33 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
@frisonisland noooooo I've already removed them 

i asked you to choose => you chose

What you want in the end? why you doing this to me on friday?

2023-05-12 12:38 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
I just asked for the method to make sense :sob: I think I got confused, re-reading: no need to add tests for that method. 
I thought you were going to remove some tests from this comment

> but about tests
i have to mock not AccessManager but abstract AdminAccessControl or private static ACLAccessControl it's more natural but it's not possible (or link me how to do it)
so removing tests for delegated admin

2023-05-12 13:49 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/admin/ModifyDomain.java
> +  protected boolean hasRight(AdminAccessControl adminAccessControl, Config config)
Ok, keeping the method and not inline bc code is a mess and tests are more important.

2023-05-15 12:45 UTC, Polpetta approved these changes

2023-05-15 12:46 UTC, Polpetta commented
LGTM after @frisonisland's suggestions

2023-05-15 12:46 UTC, frisonisland approved these changes

2023-05-17 07:09 UTC, merged