chore: upgrade slf4j and spring version
zextras/carbonio-mailbox pull request #222
Opened 2023-05-17 10:36 UTC by Polpetta

CO-514

2023-05-18 07:43 UTC, keshavbhatt approved these changes

2023-05-18 07:53 UTC, frisonisland commented
@Polpetta you will hate me, but did we run a smoke test on an installation? Asking because slf4j libraries are also provided by this repo: https://github.com/Zextras/carbonio-zcs-lib
Some times ago we had Linking issue because of inconsistencies between mailbox dependencies and these.

2023-05-18 07:57 UTC, frisonisland requested changes

2023-05-18 07:57 UTC, frisonisland commented on store/pom.xml
> +      <version>1.2.22</version>
These deps are provided by: https://github.com/Zextras/carbonio-zcs-lib
So we need to change this also.
These libraries are "common", they are not used only by mailbox but also Jetty and probably some other java application. Unfortunately some dependencies are shared.

2023-05-22 13:59 UTC, Polpetta commented
Attached to this PR is also https://github.com/Zextras/carbonio-zcs-lib/pull/18 now

2023-06-07 12:04 UTC, frisonisland commented on store/pom.xml
> +      <version>1.2.22</version>
I'm not sure we need slf4j-reload4j, as slf4j-api is still available: https://mvnrepository.com/artifact/org.slf4j/slf4j-api
Seems reload4j is a drop-in replacement for log4j 1.2.17 (https://github.com/qos-ch/reload4j) so very different from log4j 2

2023-07-07 14:43 UTC, frisonisland commented
This PR may be partially obsolete after #237 . Still we have to bump Spring, but it will be easier since we will merge zcs-lib in this repo and will only have to update 1 pom if we are lucky (dependency management)

2023-07-12 11:05 UTC, keshavbhatt commented
@zextras/nbm can we close this as the migration is completed already?

2023-07-12 12:56 UTC, Polpetta commented
I'll close it, if someone else this this makes sense to merge, please reopen it

2023-07-12 12:56 UTC, closed without merging