chore: update Log4j to version 2.x
zextras/carbonio-mailbox pull request #237
Opened 2023-05-24 12:56 UTC by Polpetta

[CO-715]

2023-05-25 09:11 UTC, keshavbhatt requested changes
I have added few suggestions. 

I suggest to track all details about what changes this change has caused to existing logging output format and analyze if we really need them like they were in the past. And create action to be taken in future to acomplish them as logging is very crucial and changing the log format will not make everyone happy.

2023-05-25 09:11 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/ResetAllLoggers.java
> +    return response;
```suggestion
    return  zsc.createElement(AdminConstants.RESET_ALL_LOGGERS_RESPONSE);
```

2023-05-25 09:11 UTC, keshavbhatt commented on store/pom.xml
> +    </dependency>
are we providing both version of log4j in zcs-lib? 
we need to figureout why we still need it.

2023-05-25 14:15 UTC, Polpetta commented on store/pom.xml
> +    </dependency>
As a temporary solution yes, we will submit both. The thing is I think it detects some bogus or deps in deps usage

2023-05-25 14:20 UTC, Polpetta commented on soap/src/main/java/com/zimbra/soap/util/Jaxb2Xsds.java
> +import org.apache.logging.log4j.Level;
Formatting e optimizing imports puts it back so it seems necessary

2023-05-25 14:21 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/util/ZimbraLog.java
> +  public static void toolSetupLog4j(String defaultLevel, String logFile, boolean showThreads) {
I don't want to get rid of logic I don't know. I prefer to mark it as deprecated, put this new codebase in production and see what happens. It we see they're not necessary anymore, we can remove them imo

2023-05-25 14:22 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/util/ZimbraPatternLayout.java
> +public class ZimbraPatternLayout {
It is used in `log4j.properties` file configuration

2023-05-25 14:22 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/util/LogManager.java
> +
done

2023-05-25 14:23 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/util/LogManager.java
> +  public static void setThisLogAndRootToLevel(Logger logger, Level level) {
done even if I think that javadoc for self-explanatory setters is a overhead

2023-05-25 14:23 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/util/LogFactory.java
done

2023-05-25 14:26 UTC, Polpetta commented
> I suggest to track all details about what changes this change has caused to existing logging output format and analyze if we really need them like they were in the past.

We have to discover this. The idea is to see together if this patch works or not. Didn't have the chance to try on road let's say. In any case I think that the output will probably change, but I didn't change any `log4j.properties` file that were the ones defining the output

2023-05-31 13:16 UTC, Polpetta commented
Ok, I've checked why Log4j 1.2.x is still necessary unfortunately:
```
+-zextras:zm-store:war:23.7.0-SNAPSHOT
  +-org.apache.curator:curator-framework:jar:2.0.1-incubating:compile
    +-org.apache.zookeeper:zookeeper:jar:3.4.5:compile
      +-log4j:log4j:jar:1.2.17:compile

+-zextras:zm-store:war:23.7.0-SNAPSHOT
  +-zextras:store-extra-runtime-dependencies:pom:23.7.0-SNAPSHOT:runtime
    +-log4j:log4j:jar:1.2.17:runtime

+-zextras:zm-store:war:23.7.0-SNAPSHOT
  +-log4j:log4j:jar:1.2.16:compile
```

This is what `goal org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce` on `zm-store` says.

2023-06-07 07:51 UTC, frisonisland commented
> Ok, I've checked why Log4j 1.2.x is still necessary unfortunately:
> 
> ```
> +-zextras:zm-store:war:23.7.0-SNAPSHOT
>   +-org.apache.curator:curator-framework:jar:2.0.1-incubating:compile
>     +-org.apache.zookeeper:zookeeper:jar:3.4.5:compile
>       +-log4j:log4j:jar:1.2.17:compile
> 
> +-zextras:zm-store:war:23.7.0-SNAPSHOT
>   +-zextras:store-extra-runtime-dependencies:pom:23.7.0-SNAPSHOT:runtime
>     +-log4j:log4j:jar:1.2.17:runtime
> 
> +-zextras:zm-store:war:23.7.0-SNAPSHOT
>   +-log4j:log4j:jar:1.2.16:compile
> ```
> 
> This is what `goal org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce` on `zm-store` says.

So:
- store-extra-runtime-dependencies are libraries needed at runtime and should be the same you get from zcs-lib in production. We could put log4j 2 in place of 1.2.
- We can remove log4j 1.2 from zm-store and put log4j 2 probably, unless some classes of 1.2 are used somewhere in the code
- Zookeper dependency scare me the most, because we could have runtime issues

I noticed we are declaring log4j dependency as type 'pom' and scope import. Thus zm-store should declare log4j-core and log4-api in place of log4j in its dependencies, same for store-extra-runtime. I will do some changes locally and propose them if I find it fixes the issue.

2023-07-04 14:23 UTC, frisonisland commented on store/pom.xml
> +    </dependency>
Removed

2023-07-04 14:27 UTC, frisonisland commented
Related PRs:
- https://github.com/zextras/carbonio-jython/pull/2
- https://github.com/zextras/carbonio-ldap-utilities/pull/52
- https://github.com/zextras/carbonio-core-utils/pull/52
- https://github.com/zextras/carbonio-zcs-lib/pull/22

2023-07-05 07:10 UTC, Polpetta commented
@frisonisland @keshavbhatt related to https://github.com/zextras/carbonio-zcs-lib/pull/22 should we merge this?

2023-07-05 07:15 UTC, frisonisland commented
> @frisonisland @keshavbhatt related to [zextras/carbonio-zcs-lib#22](https://github.com/zextras/carbonio-zcs-lib/pull/22) should we merge this?

Not yet, there are some small improvements I would like to add from https://github.com/zextras/carbonio-mailbox/pull/261

2023-07-10 07:34 UTC, frisonisland approved these changes

2023-07-10 08:08 UTC, keshavbhatt approved these changes

2023-07-10 09:43 UTC, merged