feat(CO-770): remove UCInfo SOAPI calls
zextras/carbonio-mailbox pull request #260
Opened 2023-07-03 13:36 UTC by Polpetta

See https://zextras.atlassian.net/browse/CO-770

2023-07-03 14:21 UTC, keshavbhatt commented
@Polpetta we can drop it.
https://wiki.zimbra.com/wiki/UCIntegration

2023-07-04 07:38 UTC, keshavbhatt commented
We can drop the whole VoiceConstants class and its usages. There are many classes that can be cleaned to remove UCService.

![image](https://github.com/zextras/carbonio-mailbox/assets/5965031/b1cc4b2d-3bb0-40c0-894b-86ba8d1ffb33)

2023-07-04 08:14 UTC, Polpetta commented
Ty @keshavbhatt, I'm gonna search and clean up the whole `VoiceConstants` stuff

2023-07-05 08:28 UTC, keshavbhatt requested changes
Apart from a few suggestion I made,

**We can also get rid of the following classes:**

- soap/src/main/java/com/zimbra/soap/admin/type/UCServiceInfo.java
- soap/src/main/java/com/zimbra/soap/admin/type/VoiceProviderInfo.java
- soap/src/main/java/com/zimbra/soap/admin/type/UCServiceAttribute.java
- soap/src/main/java/com/zimbra/soap/admin/message/ModifyUCService*
- soap/src/main/java/com/zimbra/soap/admin/message/CreateUCService*
- soap/src/main/java/com/zimbra/soap/admin/message/GetAllUCServices*
- soap/src/main/java/com/zimbra/soap/admin/message/RenameUCService*
- soap/src/main/java/com/zimbra/soap/admin/message/DeleteUCService*

This will also require minor cleanup in JaxbUtil and AdminConstants...

**There are still a entry related to UCService in `store-conf/conf/msgs`:**

We can get rid of them running the following command in store-conf/conf/msgs directory.

`for file in ./*; do sed -i '/listUCService/d' "$file"; done`

2023-07-05 13:26 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/account/ProvUtil.java
> -  private void doCountObjects(String[] args) throws ServiceException {
I didn't know if they were related to UCService counting only

2023-07-05 14:15 UTC, Polpetta commented on soap/src/main/java/com/zimbra/soap/admin/message/UpdatePresenceSessionIdRequest.java
> +@XmlRootElement(name = VoiceAdminConstants.E_UPDATE_PRESENCE_SESSION_ID_REQUEST)
Done!

2023-07-05 14:18 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/account/ProvUtil.java
> -  private void doCountObjects(String[] args) throws ServiceException {
I checked the codebase and it seemed is was related only to UC stuff in one way or another, so I removed it altogether

2023-07-05 14:20 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/account/ProvUtil.java
> -  private void doCountObjects(String[] args) throws ServiceException {
Looking at what it does, first it checks for domains or uc services (depending on the flag), and then it calls  `prov.countObjects(type, domain, ucService);` which iirc it didn't make too much sense without `ucservice` variable

2023-07-05 15:22 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/account/ProvUtil.java
> -  private void doCountObjects(String[] args) throws ServiceException {
NO,

**The the logic works like this:**

` countObjects {userAccount|account|alias|dl|domain|cos|server|calresource|accountOnUCService|cosOnUCService|domainOnUCService|internalUserAccount|internalArchivingAccount|internalUserAccountX} [-d {domain|id}] [-u {UCService|id}]`

So, user can either count mentioned objects in domain or UCService.

**For example:**

- to count number of userAccount in domain test.com
`zmprov countObjects userAccount -d test.com`

**We need to keep the above usecase valid and working while dropping support for UCService and its object types.**

2023-07-05 15:25 UTC, keshavbhatt requested changes
We need to keep the CountObjects capability. I added more details.

2023-07-05 15:25 UTC, keshavbhatt commented on soap/src/main/java/com/zimbra/soap/admin/type/CountObjectsType.java
> +  private CountObjectsType(boolean allowsDomain) {
we can drop private here, as its a enum constructor.

2023-07-06 09:01 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/account/ProvUtil.java
> -  private void doCountObjects(String[] args) throws ServiceException {
Restored

2023-07-06 09:02 UTC, Polpetta commented on soap/src/main/java/com/zimbra/soap/admin/type/CountObjectsType.java
> +  private CountObjectsType(boolean allowsDomain) {
Done

2023-07-06 09:20 UTC, keshavbhatt approved these changes
LGTM.

2023-07-06 09:25 UTC, frisonisland approved these changes

2023-07-06 10:50 UTC, merged