feat: remove Zimbra Mobile Gateway feature
zextras/carbonio-mailbox pull request #271
Opened 2023-07-11 12:45 UTC by Polpetta

ref: [CO-775]

2023-07-11 13:01 UTC, frisonisland commented on common/src/main/java/com/zimbra/common/soap/AccountConstants.java
>    public static final String E_BOOTSTRAP_MOBILE_GATEWAY_APP_RESPONSE =
I think we are missing these

2023-07-11 13:07 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/mail/CreateDataSource.java
> -        boolean isAppProvisioned = doZMGAppProvisioningIfReq(zsc, prov, eDataSource, type);
I think you can remove this, as the only condition where it is used evaluates always to true

2023-07-11 13:26 UTC, Polpetta commented on store/utils/docker/carbonio-db/scripts/01-db.sql
> -CREATE TABLE zmg_devices (
Ok, I'll drop it there too :+1:

2023-07-11 13:27 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/GalSyncAccountUtil.java
> -		System.out.println("zmgsautil: {command}");
Yeah, my goal was to remove the first line, I think I got carried away by the deletion process hehe

2023-07-11 13:32 UTC, frisonisland requested changes
There are still some references that can be removed, everything else looks good to me

2023-07-12 08:16 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/soap/AccountConstants.java
>    public static final String E_BOOTSTRAP_MOBILE_GATEWAY_APP_RESPONSE =
Removed!

2023-07-12 08:22 UTC, frisonisland commented on common/src/main/java/com/zimbra/common/soap/AccountConstants.java
>    public static final String E_BOOTSTRAP_MOBILE_GATEWAY_APP_RESPONSE =
All of them :laughing: See all "MOBILE_GATEWAY" constants!

2023-07-12 10:15 UTC, Polpetta commented on common/src/main/java/com/zimbra/common/soap/AccountConstants.java
>    public static final String E_BOOTSTRAP_MOBILE_GATEWAY_APP_RESPONSE =
Done

2023-07-12 11:04 UTC, keshavbhatt approved these changes
LGTM.

2023-07-12 12:42 UTC, aheeva-yuliya approved these changes

2023-07-12 12:54 UTC, frisonisland approved these changes

2023-07-12 12:55 UTC, merged