chore: [CO-774] remove document features
zextras/carbonio-mailbox pull request #274
Opened 2023-07-12 09:45 UTC by aheeva-yuliya

2023-07-18 11:58 UTC, keshavbhatt approved these changes
LGTM.

2023-07-18 12:06 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/mailbox/Folder.java
>              return false;
This will change the symantic but its okay since we are also going to remove TASK :D

2023-07-19 07:47 UTC, frisonisland commented on common/src/main/java/com/zimbra/common/mailbox/MailItemType.java
> -        DOCUMENT, /** Item is a bare Document. */
Check next lines, there are references about COMMENT. I see we removed comment API, so I guess this is safe to remove too

2023-07-19 07:53 UTC, frisonisland requested changes
I checked, seems there are still few things that could be removed.
Are we going to remove Documents AND comments in this PR? 
Could you maybe add a note in PR description with things we want to fully remove? E.g.: "with this PR we want to remove: -documents, comments, notebook, etc." Thanks

2023-07-19 08:00 UTC, aheeva-yuliya commented on common/src/main/java/com/zimbra/common/mailbox/MailItemType.java
> -        DOCUMENT, /** Item is a bare Document. */
@frisonland Next line references to NOTE not comment; Notes will be removed by Kesahv

2023-07-19 08:03 UTC, frisonisland commented on common/src/main/java/com/zimbra/common/mailbox/MailItemType.java
> -        DOCUMENT, /** Item is a bare Document. */
Next LINES :smile: for some reason I cannot highlight it, but it's line 26

2023-07-19 12:21 UTC, frisonisland approved these changes

2023-07-19 12:25 UTC, merged