Feat/copy to drive api
Zextras/carbonio-mailbox pull request #28
Opened 2022-04-11 10:48 UTC by frisonisland

The goal of this PR is to provide the copy-to-files API to allow a user to upload an email attachment to Files.

**What's new: CopyToFiles** handler class + **Request and Response classes** + **registration in MailService** (store), MailConstants (common) and JaxbUtil (soap).

**Implementation**: implementation was done **mainly in functional programming style**, also because **vavr** library has been introduced from third-party carbonio-files-sdk. Also to get a mail attachment the class **MailboxAttachmentService** (store) has been introduced, **instead of calling ContentServlet Http endpoint to get the attachment**.

**Testing: CopyToFilesIT** mainly to test integration and soap exceptions, **CopyToFilesTest** for UT (just one for now).
Some **manual testing** has also been done, as **trying to get an attachment of another user, resulting in error** (unfortunately cannot/was not able to automate because of many constraints). Same for authorization.

**Other changes**: you will find **many test classes have been updated**. **Due to Powermockito and OpenJDK11 conflicts** I had to remove Powermockito and instead encourage standard Mockito usage. To accomodate these changes I had to change some already existing classes.
Also **to be able to mock**, **I created some methods in old classes** to return providers. **Previously there were static method calls in method that prevented mocking (tight couple)**. 
**See for example: 

- GalInfoProvider.getInstance -> getGalInforProvider() 
- new SoapHttpTransport() -> getSoapHttpTransportInstance()**

2022-04-12 14:34 UTC, keshavbhatt commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> +  @XmlElement(name=MailConstants.A_MESSAGE_ID /* messageId */, required=true)
Not a big deal for me personally but the `A` prefix is being used to indicate if the object is an Attribute in MailConstants.A_MESSAGE_ID while, I see we are trying to create an element that should be prefixed with `E` char.
Not a big deal, but just to stick with the convention we are following throughout the code.

2022-04-12 14:48 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/MailboxAttachmentService.java
> +            part))// have to read content to load the stream
comment could be dropped?

2022-04-12 14:56 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> +  @XmlElement(name=MailConstants.A_MESSAGE_ID /* messageId */, required=true)
I think you are right! 
Some commits ago I was using attributes on the request, but very recently had to change the implementation and left "A_" as naming without thinking about the meaning. Thanks

2022-04-12 14:57 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> +// SPDX-FileCopyrightText: 2022 Synacor, Inc.
I think this is a copy/paste mistake. Will check also the other classes. Thanks ;)

2022-04-12 15:12 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                    new SoapFaultException("Service failure.", "", true)))
So the deal with SoapFaultException is that if the instance is created in specific ways it will return a 500 error client-side with an error message.
For example using the constructor new SoapFaultException("Service failure.", request) will produce a 200.
Unfortunately I'm not able to automate tests in a way that can be shown in the code.

Also I'm not a fan of defining inline SoapFaultException, and would have defined specific classes with error codes.
As you can see the SoapFaultException being used here has these parameters: message, error code, isServerFault
but error code is not defined. I will try to add more error codes if that's the case, else any suggestion is highly appreciated. The error codes should be meaningful for the client

2022-04-19 11:09 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                    new SoapFaultException("Service failure.", "", true)))
I use ServiceException, it is able to handle all my needs :)
ex: ServiceException.FAILURE
      ServiceException INVALID_REQUEST etc check out there are lots of generic service failure methods with reasonable  
attributes you can pass into them.

2022-04-19 11:12 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                    new SoapFaultException("Service failure.", "", true)))
the bonus is: Error code will be handled automatically if we use the correct method based on our reason.

2022-04-19 12:09 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                    new SoapFaultException("Service failure.", "", true)))
Ok thanks, will check and update the code!

2022-04-19 12:58 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> +// SPDX-FileCopyrightText: 2022 Synacor, Inc.
Mark as resolved because I have removed the Synacor line (my bad)

2022-04-19 13:15 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                    new SoapFaultException("Service failure.", "", true)))
Ok, I have used a mix of ServiceException.FAILURE, PARSE_ERROR and NOT_FOUND.
Also introduced a static method on ServiceException to allow calling constructor without throwable parameter.

2022-04-19 13:18 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> +  @XmlElement(name=MailConstants.A_MESSAGE_ID /* messageId */, required=true)
This has been updated: my idea is to leave identifiers as attributes (like the id), everything else as element.
In this case mailId and Part uniquely identify a CopyToFilesRequest, so they are attributes. Let me know

2022-04-20 15:43 UTC, Polpetta commented
Please add the following `pre-commit` script checker, so that we can start checking what we're writing:
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: mixed-line-ending
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
      - id: shellcheck
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
      - id: pretty-format-java
        args: [--autofix]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
    - id: markdownlint
    - id: markdownlint-fix
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.17.0
  hooks:
    - id: gitlint
```

Remember to install it with `pre-commit install`. You can then squash your commit (if you want) and it will check only on your diff

2022-04-20 16:13 UTC, Polpetta requested changes
I've still to review `CopyToFiles` class, but right now there are those changes to do :grin:

2022-04-20 16:13 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +  }
This is not the way to check for exceptions in the codebase: please check https://www.baeldung.com/junit-assert-exception

In particular note that with:
```java
@Rule
public ExpectedException exceptionRule = ExpectedException.none();
```

After you can check the exception message and other stuff

2022-04-20 16:13 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +    }
This is not the way to check for exceptions in the codebase: please check https://www.baeldung.com/junit-assert-exception

In particular note that with:
```java
@Rule
public ExpectedException exceptionRule = ExpectedException.none();
```

After you can check the exception message and other stuff

2022-04-20 16:13 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +          "system failure: got null response from Files server.", serviceException.getMessage());
This is not the way to check for exceptions in the codebase: please check https://www.baeldung.com/junit-assert-exception

In particular note that with:
```java
@Rule
public ExpectedException exceptionRule = ExpectedException.none();
```

After you can check the exception message and other stuff

2022-04-20 16:13 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +            fileSize);
This is not the way to check for exceptions in the codebase: please check https://www.baeldung.com/junit-assert-exception

In particular note that with:
```java
@Rule
public ExpectedException exceptionRule = ExpectedException.none();
```

After you can check the exception message and other stuff

2022-04-20 16:13 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
> +//            .toReturn(bytes);
Remove commented code if not necessary

2022-04-20 16:13 UTC, Polpetta commented on store/src/java/com/zimbra/cs/mailbox/MailServiceException.java
> +    //TODO: in future we can consider moving not implemented to a more generic/shared error code
This TODO is still valid?

2022-04-20 16:13 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/AttachmentService.java
> + * @author davidefrison
Add `@since` specification

2022-04-20 16:13 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/MailboxAttachmentService.java
> + * @author davidefrison
Add `@since` part

2022-04-21 07:00 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +            fileSize);
Ok thanks, was looking for assertThrows but forgot to check what was the JUnit 4 way.

2022-04-21 15:31 UTC, frisonisland commented on store/src/java/com/zimbra/cs/mailbox/MailServiceException.java
> +    //TODO: in future we can consider moving not implemented to a more generic/shared error code
I'd say yes. My idea is simply having a "not implemented" for generic purposes (e.g.: we want to provide a new API for some early access to the client but the functionality is not quite there).

2022-04-21 15:39 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/MailboxAttachmentService.java
> + * @author davidefrison
Added. But we should decide/talk about versioning ;)

2022-04-21 15:39 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/mail/message/CopyToFilesRequest.java
> + *
Added

2022-04-21 15:41 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/filter/ZimbraMailAdapterTest.java
> +        Mailbox mbox = Mockito.mock(Mailbox.class);
Done

2022-04-21 15:41 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/AttachmentService.java
> + * @author davidefrison
Done

2022-04-22 15:01 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/MailboxAttachmentService.java
> + * @author davidefrison
Yeah I agree with you

2022-04-22 15:21 UTC, Polpetta requested changes
I reviewed your latest changes and there are some things to fix here and there.

Little note: it is ok to put documentation on a tests if it helps the next maintainer to understand it, but personally, I don't consider it mandatory. Good job writing it down anyway :+1:

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/ldap/unboundid/UBIDUserCertificateAttributeTest.java
> +      fail("Exception thrown");
I mean this is not really necessary, the test will fail even if the exception is thrown, so this is sort-of unnecessary code

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/ldap/unboundid/UBIDUserCertificateAttributeTest.java
> +      fail("Exception thrown");
Same as before here

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
> +    Assert.assertEquals(ldapThumbnailImageData, attrMap.get(ZAttrProvisioning.A_thumbnailPhoto));
Static import

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
> +    Assert.assertEquals(profileItemId, getResponseJaxb.getProfileImageId());
Static import

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
> +    Assert.assertEquals(null, attrMap1.get(ZAttrProvisioning.A_thumbnailPhoto));
Static imports

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
> +  }
Don't catch exceptions on `@Before`, `@After` or `@BeforeClass` and similar. Let the exception be sent to JUnit, otherwise possible errors in tests could be not displayed because they're catched

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                            ex -> ServiceException.FAILURE("internal error.", ex)))
You can use `onFailure` method to avoid `instanceOf` that is not for being slow.
```suggestion
                    .onFailure(ServiceException.class, ex -> ServiceException.FAILURE("internal error.", ex))
```

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                ex -> ServiceException.PARSE_ERROR("Malformed request.", ex)));
See suggestion above:
```suggestion
        .onFailure(Exception.class, ex -> ServiceException.PARSE_ERROR("Malformed request.", ex));
```

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                            MailConstants.A_MESSAGE_ID + " must be an integer.", ex)));
See suggestion above:
```suggestion
            .onFailure(Exception.class,
                    ex ->
                        ServiceException.PARSE_ERROR(
                            MailConstants.A_MESSAGE_ID + " must be an integer.", ex));
```

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                            ex -> ServiceException.NOT_FOUND("File not found.", ex))))
See suggestion above:
```suggestion
                    .onFailure(Exception.class,
                            ex -> ServiceException.NOT_FOUND("File not found.", ex))
```

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +          return fileSize;
Suggestion: IIRC there is an Apache Commons method or a Stream way to avoid doing it the ol' imperative way ;)

2022-04-22 15:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                ex -> ServiceException.FAILURE("Cannot get file content-type.", ex)));
```suggestion
        .onFailure(Exception.class,
                ex -> ServiceException.FAILURE("Cannot get file content-type.", ex));
```

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/UserServletTest.java
> +      //            Assert.assertEquals("must authenticate", response.getMsg());
Question: have you figured out why? :sweat_smile: It is important to investigate it if it fails on the CI since it means tests runs in a different manner in CI or your machine

2022-04-22 15:21 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/UserServletTest.java
> +    }
Please let the exception fly up in the junit sky :D

2022-04-27 08:57 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                ex -> ServiceException.PARSE_ERROR("Malformed request.", ex)));
@Polpetta I'm not sure this will introduce the behavior I was thinking about.
The idea is:

- to log the underlying exception
- map the exception to a specific ServiceException.

By using the onFailure(), which accepts a consumer, it will execute the consumer in case it matches but it will return the identity (this). So it will not map the exception to a ServiceException and the old failure will be preserved. 
Also some tests have been made to track this behavior and if I change the code as suggested they fail.(see shouldThrowServiceExceptionIfFileNotFound)

What I can do (but it's a style thing at this point) is:
```suggestion
        .mapFailure(
            Case(
                $(instanceOf(Exception.class)),
                ex -> {
                              mLog.debug(ex.getMessage());
                              return ServiceException.NOT_FOUND("File not found.", ex);
                            }));
```
and remove the onFailure entirely.

2022-04-27 12:41 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/ldap/unboundid/UBIDUserCertificateAttributeTest.java
> +      fail("Exception thrown");
@Polpetta first of all: sorry for this monster PR. 
**The changes I made here are because I removed PowerMockito** and had to change many tests accordingly. **But these tests were not made by me.** This is one of those test classes. The only tests made by me are the one inside **CopyToFilesIT**.
We can talk about removing these tests if they do not provide any value, but I'll propose to save it for the next iteration, else there will be a never-ending refactor :)

Same can be said about static import in many places. But in that case there is no harm in adapting the code style to our needs, so I'll gladly do it.

2022-04-27 12:48 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/ldap/unboundid/UBIDUserCertificateAttributeTest.java
> +      fail("Exception thrown");
Let me add: one could argue that these files should not be changed if there is no added value.

Value: we can run some old tests without them breaking because of PowerMockito. 
Also we are laying a base to slowly improve the test codebase.

2022-04-27 13:06 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/UserServletTest.java
> +      //            Assert.assertEquals("must authenticate", response.getMsg());
@Polpetta soory again, I think it's better to see it together, because things have got out of hand.
These changes are because I removed PowerMockito, but can't answer about everything else (e.g.: catching exceptions, commenting why it fails in CI, etc.). It's the first part of a refactor.
Also it's definitely not my style :sweat_smile:

2022-04-28 09:55 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/ldap/unboundid/UBIDUserCertificateAttributeTest.java
> +      fail("Exception thrown");
Yeah, I agree with you, since this is a recent fork we should adapt it gradually, and in my opinion the best way to do it is to adapt what we're touching along the way, otherwise it'd impossible to do it at once. So no problem for the exception, if you want remove it otherwise it is fine (but someone else sooner or later will have to do it)

2022-04-28 09:57 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +                ex -> ServiceException.PARSE_ERROR("Malformed request.", ex)));
Ooooh ok, I got the point. Nope, keep it like it is and resolve all the other corrections pleasee :+1: Resolve this one once you've read the comment

2022-04-28 13:09 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/mail/SearchActionTest.java
> +import java.util.List;
**FYI (if you are here wondering what changed)**: this class has been updated due to pre-commit linting

2022-04-28 13:10 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/imap/MemcachedImapCacheTest.java
> +import static org.mockito.Mockito.mock;
**FYI:** class changed due to pre-commit

2022-04-28 13:10 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/mail/CopyToFilesIT.java
> +package com.zimbra.cs.service.mail;
**FYI:** class changed due to pre-commit

2022-04-29 09:53 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/mail/CopyToFiles.java
> +          return fileSize;
Thanks, I checked the Apache library, but all I could find was methods that load the stream into a byte array and then can compute the size.
I did it this way because I don't need the entire byte array and it will avoid storing too much in memory.
Also not sure about other stream way, I think it will require to read, create a list, stream it, but the result will be the same, if not it will make the code less readable in this particular case.

2022-05-02 08:41 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/mailbox/ContactTest.java
>  import static org.mockito.Mockito.mock;
Pre commit here too?

2022-05-02 08:42 UTC, Polpetta approved these changes
LGTM :+1:

2022-05-02 08:53 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/mailbox/ContactTest.java
>  import static org.mockito.Mockito.mock;
Yes, It's the CopyToFIlesIT file that is new (the very next one), sorry for the mistake in the comment!

2022-05-04 16:07 UTC, keshavbhatt approved these changes

2022-05-05 09:23 UTC, merged