chore: CO 791 Remove task features
zextras/carbonio-mailbox pull request #287
Opened 2023-07-19 14:06 UTC by aheeva-yuliya

2023-07-24 14:08 UTC, Polpetta requested changes
Everything seems ok, just remove that extra comment that is not necessary imho

2023-07-24 14:13 UTC, frisonisland approved these changes

2023-07-24 14:39 UTC, keshavbhatt commented
@aheeva-yuliya 

We can also have some cleanup on the MailItemType: https://github.com/zextras/carbonio-mailbox/blob/chore_CO-791_remove_task_feature/common/src/main/java/com/zimbra/common/mailbox/MailItemType.java#L35

Please remove Note type (has no usages) which I missed in one of my recent PR. 
And also other which have no usages if you want.

2023-07-25 10:35 UTC, Polpetta approved these changes

2023-07-26 08:21 UTC, merged