Feat/CO-249 attachment preview servlet
Zextras/carbonio-mailbox pull request #29
Opened 2022-04-14 06:37 UTC by keshavbhatt

The preview service servlet - serves preview for requested mail attachments using Carbonio's previewer service
 
    The API is almost the same as of preview service(https://zextras.atlassian.net/wiki/spaces/SW/pages/2353430753/Preview+API)
    with a few modifications that let us make it useful as a  preview service for mailbox attachments.
 
    itemId, partNo, disposition(disp) are notable new parameters, their usage can be found in the URL given below:
 
    https://nbm-s01.demo.zextras.io/service/preview/{format}/{itemId}/{partNo}/{area}/{thumbnail}/?[{query-params}]
 
           Path parameters:
                     format  =  image | pdf
                     itemId  =  mail-item-id
                     partNo  =  mail-item-part-number
                       area  =  width of the output image (>=0) x height of the output image (>=0),
                                width x height => 100x200. The first is width, the latter height, the order is important!
                  thumbnail  =  omit for full preview type
                                'thumbnail' if requesting the preview type
                                 thumbnail
 
           Query parameters:
                       disp  =  attachment(a) | inline(i) ; default inline(i)
                      shape  =  rounded | rectangular
                    quality  =  lowest | low | medium | high | highest
              output_format  =  jpeg | png
                       crop  =  True will crop the picture starting from the borders.
                                This option will lose information, leaving it False will scale and have borders to fill the requested size.
                 first_page  =  integer value of first page to preview (n>=1)
                  last_page  =  integer value of last page to preview (0 = last of the pdf)
 
             Authentication  =  expects ZM_AUTH_TOKEN cookie passed in the request
                                headers

2022-04-14 15:20 UTC, Polpetta commented on build-ivysettings.xml
> +      </url>
@davide-baldo sorry to disturb you but I just notice we are plugging in JFrog like this. Can we do it? I think we're distributing our dependency publicity via Artifactory and I don't remember clearly what we can or can't do with it

2022-04-14 16:21 UTC, Polpetta reviewed
I've checked till here, next days I'll check the tests too

2022-04-14 16:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +    }
Also this way you can delete the `Try` at the beginning of the method, the one that retrieves the `InputStream`, and you can move it there (check suggestion above)

2022-04-14 16:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +      Try<BlobResponse> response, String fileName, String dispositionType) {
Please avoid passing `Try` method arguments. The same is for `Optional` fyi.

Try and Optional are intended to be either return arguments or to be used on-the-spot in pipelines

2022-04-14 16:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +    if (optArea != null) parameterBuilder.setPreviewArea(optArea);
Please avoid this kind of statements, they are not compliant with the Google Style guide that we adopted as our coding style company wide (check DevDoc for more information)

2022-04-14 16:21 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +        }
Please use `.onFailure()` method instead of this `if-else` waterfall. In particular, there is this signature you can use: 
```java
onFailure(Class<X> exceptionType, Consumer<? super X> action)
```

Where you can specify the type of the exception and pass a lambda function that will contain the desired exception. So this becomes:
```suggestion
      final Try<BlobResponseStore> previewOfAttachment =      getAttachmentPreview(getUrlWithQueryParams(req), attachmentMimePart.get())
      .onFailure(BadRequest.class, ex -> respondWithError(resp, HttpServletResponse.SC_BAD_REQUEST, previewOfAttachment.getMessage())
      .onFailure( // Continue from there :))
```

2022-04-15 05:15 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +    }
Yes, I considered that before writing the controller this way. I prefer it to remain in this way since it's more expressive and clean. The idea is to have the logic of each API endpoint separate rather than mixing the logic into one method. I will work on eliminating if :D 
Note that, I am aware of chained failure and success methods and use them wherever I find they fir best. 

If you look at the whole method definition, you will find a flow where each we respond with errors whenever they occur or process to the next step, rather than encapsulating the whole logic in one chain. I understand we can create a single big chain and get away with it, but think how easy that will be to maintain in the future.

2022-04-15 05:24 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +        }
The idea was to not have a single chain doing more than one job.
I changed the code according to your suggestion, now we have a statement doing more than one task. Handling errors of preview service and committing the response.

2022-04-15 05:24 UTC, keshavbhatt commented
Thanks @Polpetta for your suggestion :+1:

2022-04-15 08:02 UTC, davide-baldo commented on build-ivysettings.xml
> +      </url>
> I think we're distributing our dependency publicity
No we are not, these are the paths for authenticated upload, we cannot give public access to artifactory repositories.
The same idea persist, to fully mirror this repository in repo.zextras.io in order to make them public.

2022-04-19 14:52 UTC, Polpetta requested changes
Additional couple of things to fix before it's good to go:
- Most if not all of the methods have package private visibility. Please use a more restrictive one like `private`. We need to keep things encapsulated
- Most of the variable are declared not `final`. Please declare them as `final` if the pointer to the instantiated object doesn't change (like 90% of the cases)

2022-04-19 14:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +    Assert.assertEquals(expectedUrlWithQueryParams, url.toString());
Same here, use static import qualifier

2022-04-19 14:52 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              });
This can still be refined in:

```suggestion
        Try.of(() -> getAttachmentPreview(getUrlWithQueryParams(req), attachmentMimePart.get()))
                .onSuccess(previewOfAttachment -> respondWithSuccess(resp, previewOfAttachment.get()))
                .onFailure(BadRequest.class, ex -> respondWithError(resp, HttpServletResponse.SC_BAD_REQUEST, ex.getMessage()))
                .onFailure(ItemNotFound.class, ex -> respondWithError(resp, HttpServletResponse.SC_NOT_FOUND, ex.getMessage()))
                .onFailure(ValidationError.class, ex -> respondWithError(resp, HttpServletResponse.SC_UNAUTHORIZED, ex.getMessage())
                .onFailure(ex -> respondWithError(resp, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, ex.getMessage());
```

This way it's easier to handle new errors in case it's needed and it's clear what's happening. Plus, you are not doing type checking, that it is known for being slow.

2022-04-19 14:53 UTC, Polpetta commented on build-ivysettings.xml
> +      </url>
Okok! Thanks :+1:

2022-04-20 07:04 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +  }
From the documentation:  Before annotation indicates that this method must be executed before each test in the class, so as to execute some preconditions necessary for the test. The BeforeClass annotation indicates that the static method to which is attached must be executed once. When we want to execute an expensive common operation before each test, it's preferable to execute it only once before running all tests using @BeforeClass 

Reading this BeforeClass seems the perfect candidate to me.

2022-04-20 07:12 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +    MockHttpServletRequest mockRequest = PowerMockito.mock(MockHttpServletRequest.class);
I totally agree with this, but I don't know if this change will provide us with any performance gains. But for sure will contribute to unreadable and unmaintainable code if used excessively.

2022-04-20 07:16 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              });
I tested this when you suggested it in the previous comment. Unfortunately, this results in undesirable behavior. I am getting two error codes :smiling_face_with_tear:

2022-04-20 07:22 UTC, frisonisland commented on build-ivysettings.xml
> +      </url>
Ok, so this is the way to proceed right now right? 
Because I'm doing the same on PR #28 and already asked about it and about having a public accessible repository

2022-04-20 13:43 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +import org.powermock.api.mockito.PowerMockito;
I'd like to add: i**n PR #28 I made changes to remove PowerMockito**. Beware that removing it will result in having to made changes to many other test classes (changes that I've already made on my branch).
**We can either choose to make the same changes in this branch**, **or** leave at it is and instead **having it removed once my changes are included**. Unfortunately testing is quite difficult to handle

2022-04-20 13:57 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +    MockHttpServletRequest mockRequest = PowerMockito.mock(MockHttpServletRequest.class);
Mmmh to be honest I feel this is all about style.
Personally sometimes, when using them, I found difficult to understand to which class a static method belongs at first glance (e.g. assert, etc.), especially when reading PRs from github.
An advantage could be that when testing we have already the assertEquals, assertTrue, etc. already available and prompt with IDE support. 
So I say we should go for it and maybe develop a habit on using them (included myself).

2022-04-20 15:33 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +  }
It is the perfect candidate, unfortunately tho it uses static memory allocations that are capped until a certain point: this will cause out of memory errors at some point and it will be impossible to debug. Trust me on this, we wasted a week at debugging this on the Zextras Suite.

Note that you are allocating on the static stack:
```java
private static PreviewServlet previewServlet;
private static String authTokenString;
```

The `PreviewServlet` is a complex object that, if instantiated a great number of times for each test (note those are not removed after the test execution, so no garbage collection) will consume all the static heap one day.

2022-04-20 15:35 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +import org.powermock.api.mockito.PowerMockito;
We could cherry pick some changes, but anyway I vote to remove it

2022-04-20 15:36 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +    MockHttpServletRequest mockRequest = PowerMockito.mock(MockHttpServletRequest.class);
I confirm, it's about style not performances

2022-04-20 15:37 UTC, Polpetta commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              });
Can you print them here? It seems strange, I tested this code on my machine and they worked :sweat_smile:

2022-04-22 16:05 UTC, frisonisland requested changes

2022-04-22 16:05 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +  Try<BlobResponseStore> getAttachmentPreview(String requestUrl, MimePart attachmentMimePart) {
Any reason why we are using many package private methods?
PreviewServlet seems very specific to me, don't know if there is the need to extend the class in the same package. 
Also I don't think we are going to call this method in other classes with a preview servlet instance.

2022-04-22 16:05 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +    resp.addHeader("connection", "close");
For headers take a look org.apache.http.HttpHeaders class (it's already a dependency), it has all the headers as constants.

2022-04-25 11:39 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +  }
Using before we are talking about the initialization of Mailbox and other classes (in this case) to be done before every test case. While in the BeforeClass case we are doing it once, and also cleaning the heap once the test is complete, see teardown method. I don't see any memory leak in this case. If you guys find any let me know.

2022-04-26 07:08 UTC, frisonisland commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +  }
What me and @Polpetta are trying to say is that having many @BeforeClass annotations will lead to a point where running all test cases will fill the heap and tests won't even start. 
He told me it already happened to him in a similar scenario, also a similar case happened to me in the past.
We are saying this because there are already many test classes using @BeforeClass. If your test was the only one using @BeforeClass the conversation wouldn't have (probably) started.
Worst case of having @Before (for each test) is tests will run slower, but we can optimize them later and use @Before accordingly if that's a problem. Also in my case I didn't found any performance issue starting the mailbox in @Before.
So in this case @Before and @BeforeClass will lead to same result, but running the entire test suite will lower the chances of filling the heap space.

2022-04-28 10:14 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +    MockHttpServletRequest mockRequest = PowerMockito.mock(MockHttpServletRequest.class);
using static import as suggested.

2022-04-28 10:16 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +  }
using Before instead of BeforeClass as suggested, though I still don't understand the reasoning behind filling up of the heap.

2022-04-28 10:18 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +import org.powermock.api.mockito.PowerMockito;
@Polpetta & @frisonisland what I should do at this point, remove the powermockito in this PR and use mockito, or should wait for you to merge the refactor PR and then proceed with the same?

2022-04-28 14:34 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/service/PreviewServletTest.java
> +import org.powermock.api.mockito.PowerMockito;
I am using mockito since Refactor PR is already merged.

2022-05-02 08:44 UTC, Polpetta approved these changes
:+1:

2022-05-04 15:08 UTC, frisonisland approved these changes
All good for me, we have just to sync up and exclude that httpclient dependency from the WAR

2022-05-06 09:46 UTC, merged