fix: [CO-792] Fix redirects in PreAuth servlet + refactoring
zextras/carbonio-mailbox pull request #291
Opened 2023-07-25 09:47 UTC by keshavbhatt

**What has chnaged:**
- The default redirect paths are aligned with out web app paths
- Heavy refactoring of whole codebase
- Path of servlet was changed from `com.zimbra.cs.service.PreAuthServlet` to `com.zimbra.cs.service.servlet.preauth.PreAuthServlet` the idea is to keep encapsulate each servlet into its respective package to improve maintinance. Webapp configuration was upated accordingly.
- The codebase has now the coverage of ~76% which was 0 before.

2023-07-27 07:03 UTC, frisonisland approved these changes

2023-07-27 14:06 UTC, aheeva-yuliya approved these changes

2023-08-01 13:12 UTC, Polpetta requested changes
Please check carefully this pull request because is violating SOLID principles and also the design is not fully clear to me. In particular, I'd take care to not execute logic inside the Servelet. Instead I'd delegate it to a separated class that doesn't use Jetty objects (like for instance `HttpServletRequest` and `HttpServletResponse`) but it "talks" internally with its domain objects.
In order to achieve this, there are two ways: either we start adopting the hexagonal design - that can also be used not only for architectural stuff but also for "code" implementations (like this one) - or we resort back to the good ol' MVC pattern.

I'd suggest moving the hexagonal design and implement all the future API calls in this way, but on this one I'll let you decide.

2023-08-02 08:15 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthParams.java
> +  }
Done.

2023-08-02 08:15 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +    prov.createAccount("one@test.com", "secret", attrs);
done.

2023-08-02 08:17 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +            eq(true));
The problem in this case is Provisioning which is not injectable to PreauthServlet. We will fix this when we will move to new code architecture in future.

2023-08-02 08:17 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +            eq(true));
Provided limitations in my previous comment. we will figure this out later.

2023-08-02 08:17 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +    AuthToken authToken = AuthProvider.getAuthToken(account, expires, false, null);
done.

2023-08-02 08:17 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +    AuthToken authToken = AuthProvider.getAuthToken(account, expires, false, null);
done

2023-08-02 08:18 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +    Map<String, String[]> parameterMap = new HashMap<>();
done.

2023-08-02 08:18 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthServletTest.java
> +  }
done.

2023-08-02 08:20 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    Map<String, Object> adminAttrs = Maps.newHashMap();
done

2023-08-02 08:23 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    assertEquals("requiredValue", result);
done

2023-08-02 08:23 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    HttpServletRequest request = createMockRequestWithParamValue(paramName, null);
done

2023-08-02 08:23 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    assertThrows(ServiceException.class, () -> Utils.getRequiredParam(request, paramName));
done

2023-08-02 08:23 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String result = Utils.getOptionalParam(request, paramName, "defaultValue");
done

2023-08-02 08:23 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    HttpServletRequest request = createMockRequestWithParamValue(paramName, null);
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String result = Utils.getOptionalParam(request, paramName, "defaultValue");
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String baseUrl = Utils.getBaseUrl(request);
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String expectedOutput1 = "/path";
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String expectedOutput2 = "/";
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String inputURL3 = "invalid-url";
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    String inputURL4 = null;
done,

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    AuthToken authToken = Utils.generateAuthToken(account, expires, false);
done

2023-08-02 08:24 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    AuthToken authToken = Utils.generateAuthToken(account, expires, true);
done

2023-08-02 08:25 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    assertEquals(expectedAuthContext, authContext);
done

2023-08-02 08:25 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/UtilsTest.java
> +    HttpServletRequest request = mock(HttpServletRequest.class);
done

2023-08-02 08:39 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthParamsTest.java
> +class PreAuthParamsTest {
I will keep this for following reasons:
- Verification of expected behavior
- Catch unintended changes
- For easy refactoring and maintenance in future
- Ensuring code coverage for sure :sweat_smile:

2023-08-02 08:51 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParamsTest.java
> +  }
done

2023-08-02 09:07 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParamsTest.java
> +  void testAutoProvisioningParams() {
I found it hard to read.

Also according to many articles there is no standard convention for this and everyone is free to use whatever they want. One such post that list most of the conventions adopted with pros and cons: https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea

In in this PR I tried to follow 

```
void testMethodName{
    // comment about the behavior being tested
    ...
}
```

I we want to follow `should_expectedBehavior_whenCondition` naming convention I highly encourage we split the keywords involed with an underscore (_) for better redability. I will try to move all tests to follow this.

2023-08-02 09:08 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParamsTest.java
> +    AutoProvisioningParams params =
done

2023-08-02 09:09 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParamsTest.java
> +    Map<String, Object> authContext = Utils.createAuthContext(accountIdentifier, request);
done.

2023-08-02 09:11 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    return authToken;
Done,

I don't know what is the problem with usage of simple ternary operators here.

2023-08-02 09:13 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +      StringBuilder sb = new StringBuilder();
done

2023-08-02 09:18 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    }
This was done since the redirect url is an Optional parameter and if you remeber the method that deals with param parsing also returns null if the param value is null and there is no default for it. For now i will keep it simple just like that preventing modifications everywhere. Also notice there are tradeoffs having both approaches.

2023-08-02 09:21 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    }
A nested ternary op indeed makes the code hard to read, but banning simple ternary op is like killing the democracy :D 

I will follow what is suggested. But let's not kill the choices. :sweat_smile:

2023-08-02 09:22 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    String protocolPattern = "^(http|https|ftp|file)://.*$";
done.

2023-08-02 09:22 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    int port = url.getPort();
done

2023-08-02 09:23 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +      AuthToken localAuthToken = Utils.generateAuthToken(acct, expiresParam, adminParam);
done

2023-08-02 09:32 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +    }
done, we dont have to negate isDomainAdminAccount though :slightly_smiling_face:

2023-08-02 09:44 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +                  .build());
done

2023-08-02 09:44 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParams.java
> +  }
done.

2023-08-02 09:50 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +        Utils.getOptionalParam(req, PreAuthParams.PARAM_BY.getParamName(), AccountBy.name.name());
The `getRequiredParam` method handles that and explicitly mention's its contract in the java doc.

2023-08-02 11:30 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +    Provisioning provisioning = Provisioning.getInstance();
done

2023-08-02 11:32 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +  void handleRawAuthTokenRequest(
We cannot test everything via doGet due to involvement of various classes that cannot be mocked.
I tried my best to get good coverage already on doGet and some other branches it calls.

2023-08-03 06:37 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +    }
done.

2023-08-03 06:39 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +   * @param resp The HttpServletResponse object representing the HTTP response to be sent back.
done

2023-08-03 06:39 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +   * @param req The HttpServletRequest object representing the incoming HTTP request.
done

2023-08-03 06:57 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +public class PreAuthServlet extends ZimbraServlet {
done.

2023-08-03 07:39 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +    AuthToken authToken = AuthProvider.getAuthToken(rawAuthToken);
done

2023-08-03 07:39 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +      ZimbraAuthToken oneTimeToken = (ZimbraAuthToken) authToken;
done

2023-08-03 07:40 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +      String replaceProtocol = String.format("%s://", protocol);
done

2023-08-09 09:09 UTC, merged

2023-08-16 14:53 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParams.java
> +  }
You can use Step builder pattern to force some mandatory parameters if this is the goal: https://www.javacodegeeks.com/2013/05/building-smart-builders.html

2023-08-16 14:54 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/PreAuthServlet.java
> +    }
Yes, while writing the suggestion I forgot to add the parenthesis :sweat_smile:

2023-08-16 14:57 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    }
The goal is to have, simple, easy to read and maintainable code. If ternary operators don't meet one of those goals they should be avoided.

2023-08-16 15:05 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    }
Can you please provide me a list of the tradeoffs?

Regarding null it is known to be the "billion dollar mistake" by the inventor itself, that regretted the invention of such thing. Why should we use something that is clearly a design error? Better switch to alternative that are sound, also from language design pov.

> I call it my billion-dollar mistake. It was the invention of the null reference in 1965. At that time, I was designing the first comprehensive type system for references in an object oriented language (ALGOL W). My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement. This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years.
> - [Tony Hoare](https://en.wikipedia.org/wiki/Tony_Hoare), 2009

2023-08-16 15:06 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/service/servlet/preauth/Utils.java
> +    return authToken;
Very difficult to read

2023-08-16 15:07 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/AutoProvisioningParamsTest.java
> +  void testAutoProvisioningParams() {
Keshav, is a matter that we wrote code in this way for years and it is better to keep it consistent. We can review it with the approval of everyone. For now, stick to how it was done in the past please.

2023-08-16 15:10 UTC, Polpetta commented on store/src/test/java/com/zimbra/cs/service/servlet/preauth/PreAuthParamsTest.java
> +class PreAuthParamsTest {
I don't agree. The first three points are imho invalid, since there's not logic to test, so the testing itself in this case should happen naturally in those test cases that use this enum