feat: [CO-784] add documentation URL attributes
zextras/carbonio-mailbox pull request #300
Opened 2023-08-02 11:15 UTC by inno-dima

**What was changed:**

- Added LDAP attributes in attrs.xml and rights-domainadmin.xml
- Added JSON configuration for LDAP update script

2023-08-02 11:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-mailbox?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-mailbox?pullRequest=300) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Polpetta<br/>:x: inno-dima<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-mailbox?pullRequest=300) it.</sub>

2023-08-02 12:02 UTC, frisonisland approved these changes

2023-08-02 12:07 UTC, keshavbhatt commented on store/ldap/src/updates/attrs/1690904855.json
> +  "zimbra_globalconfig": [
We don't need migration, since these are new attributes.

2023-08-02 12:09 UTC, keshavbhatt requested changes
Reuqested a change everything else look good.

2023-08-02 12:10 UTC, frisonisland commented on store/ldap/src/updates/attrs/1690904855.json
> +  "zimbra_globalconfig": [
Are you sure? The documentation suggest the opposite. I thought the update was meant to add a default value to new attributes created on existing entities
See: https://github.com/zextras/carbonio-mailbox/blob/devel/store/ldap/src/updates/attrs/ReadMe.md

2023-08-02 12:27 UTC, Polpetta approved these changes
Everything is fine after the migration thing with LDAP is settled

2023-08-02 15:29 UTC, keshavbhatt commented on store/ldap/src/updates/attrs/1690904855.json
> +  "zimbra_globalconfig": [
Yes its true. But as discussed these attributes will probably not have any default value.

2023-08-03 06:10 UTC, frisonisland commented on store/ldap/src/updates/attrs/1690904855.json
> +  "zimbra_globalconfig": [
It was confirmed we have a default value, but we have to wait for it to be provided!

2023-08-08 11:04 UTC, keshavbhatt requested changes
You need to build the project after updating attrs.xml and commit whatever changed, usually the build will generate and update some files. They need to be commited.

Other than this, I asked for minor cleanup of ReadMe file which was updated.

2023-08-08 13:51 UTC, keshavbhatt approved these changes

2023-08-09 07:52 UTC, aheeva-yuliya approved these changes

2023-08-09 07:54 UTC, merged