feat: [CO-772] Allow admins to specify custom domain login and logout URL
zextras/carbonio-mailbox pull request #301
Opened 2023-08-03 09:06 UTC by keshavbhatt

### Whats has changed:

** Added new attributes to manage custom domain login and logout URL**
    - carbonioWebUILoginURL
    - carbonioWebUILogoutURL
    - carbonioAdminUILoginURL
    - carbonioAdminUILogoutURL 
    
**All above mentioned attributes are:**

- optional in `globalConfig` and `domain` entries
- returned as part of the `GetDomainInfo` SOAP call
- are modifiable by a `domain admin` and `global admin` ofcourse

**New proxyconfgen variables to** 

support redirection of web login and logout for both default and virtualhost templates all defaulting to `/static/login/` path.
- for handling login `web.carbonio.[webui|admin].login.url.[default|vhost]`
- for handling logout `web.carbonio.[webui|admin].logout.redirect.[default|vhost]`

**Note:** the redirection of logout is handled by othe carbonio components like UI and Auth.

**Testing:**
- Unit tests were added to verify the behavior of newly added variables.
- Manual testing.

2023-08-04 13:13 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    AddHeadersVar addHeadersVar = new AddHeadersVar(null, null, null, null);
Why all these null? It means the class doesn't need the dependencies probably

2023-08-04 13:19 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +  }
I see these tests test:
- url empty -> default value
- url not empty -> set actual value

This is not necessary, I would set whatever is passed. 
This would make it non-ambiguous.
Consider choosing the value to set when instantiating the class, passing the correct value.

2023-08-04 13:25 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +  }
This method name starts with "modifyCsp" but doesn't modify anything, rather it returns a value. So it is a get or the method doesn't perform what it announces.
Also the logout URL conditions are not clear. Probably a smell this method is doing too much.

2023-08-04 13:27 UTC, frisonisland requested changes
Code can be cleaned up, I think it would be nice to check together and make it more maintainable

2023-08-07 09:01 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
I am following `should_expectedBehavior_whenCondition` unit test naming convention as it is the most accepted and practical one. The one that we were using was hard to read and hard to write, We can have a quick talk about this and think about adopting it everywhere. Anyway, there are many conventions there to name your test methods but the one we were using is documented no where. I persoanlly had reading and writing issues with that, and if you will see adding those underscore as separator fixes the issue making it easily readable.

2023-08-07 09:02 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    AddHeadersVar addHeadersVar = new AddHeadersVar(null, null, null, null);
Those values are not required for this test.

2023-08-07 09:05 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +  }
To change this behaviour we need to change the logic of ProxyConfVar which this class extends.

2023-08-07 09:25 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +  }
Updated the name to  `generateModifiedCspHeaderValue`, extracted cspUpdate logic to `generateModifiedConnectSrcDirectiveWithCustomUrls`.

2023-08-07 09:26 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +    super(null, null, null, null, null, null, null, null, null, null, null, null, null);
DomainAttrItem now uses builder, this custom exception was updated accordingly.

2023-08-09 07:43 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    assertFalse(AddHeadersVar.isValidSrcDirectiveUrl("https://www.test.com https://test.com"));
Use a parameterized test, you can pass urls as arguments.
Also I see we named the test as "<methodName>_should_<condition+expectation>".
We could name it as "shouldReturnFalse_WhenInvalidUrl".

2023-08-09 07:45 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +    assertEquals("return 307 /static/login/", var.mValue);
This test tells me we are setting a default value on constructor if value empty.
Generally is better to just assign things in Constructor, with no logic.
We can achieve the same by making the constructor private and using a factory method that checks the emptiness.

2023-08-09 08:40 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    assertFalse(AddHeadersVar.isValidSrcDirectiveUrl("https://www.test.com https://test.com"));
This is exactly the same naming convention that is used across other method names.

methodUnderTest_should_expectedBehavior_whenCondition.

2023-08-09 08:54 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    assertFalse(AddHeadersVar.isValidSrcDirectiveUrl("https://www.test.com https://test.com"));
Done,
But, I dont know why we want to take this freedom away :D

2023-08-09 09:00 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +    assertEquals("return 307 /static/login/", var.mValue);
removed update method call from constructor. leaving with no logic check

2023-08-09 09:29 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +    assertFalse(AddHeadersVar.isValidSrcDirectiveUrl("https://www.test.com https://test.com"));
It's the same concept as mixing snake case and camel case in the end, team decision in the end + naming consistency.
It would be odd if in a next PR someone decides to use another naming convention for example.
If we care about the name being displayed during tests consider using: https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/DisplayName.html
since we adopted junit jupiter

2023-08-10 07:30 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +        "^(https?://(w{3}\\.)?)?((\\*\\.)?\\w+(-\\w+)*\\.\\w+(\\.[a-zA-Z]+)*(:\\d{1,5})?(/\\*|/\\w*)*(\\??(.+=.*)?(&.+=.*)?)?)?$",
I think for all utilities method in ProxyConfGen context it could be a good idea to move them to a ProxyConfGenUtil class. This way we will slowly slim down ProxyConfGen and related class.
Also the name of this class is bit weird IMHO, why AddHeadersVar and not HeadersVar? I know we didn't create it, but does it represent a Header or an Add Header operation?

2023-08-10 07:50 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +        "^(https?://(w{3}\\.)?)?((\\*\\.)?\\w+(-\\w+)*\\.\\w+(\\.[a-zA-Z]+)*(:\\d{1,5})?(/\\*|/\\w*)*(\\??(.+=.*)?(&.+=.*)?)?)?$",
It is named like this maybe because it is supposed to generate "add_header is a nginx directive". I agree to move this method to ProxyConfGenUtil.

2023-08-10 08:09 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +        "^(https?://(w{3}\\.)?)?((\\*\\.)?\\w+(-\\w+)*\\.\\w+(\\.[a-zA-Z]+)*(:\\d{1,5})?(/\\*|/\\w*)*(\\??(.+=.*)?(&.+=.*)?)?)?$",
done.

2023-08-10 08:14 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      directives.add(header);
I will ask to try to move this logic outside, it is weird having a class update itself and leads to side effects. I prefer returning a value from a method rather then void and update its internal value. This because it is unclear you have to call the update() to get some value later, it is more natural to call a get() (which can call an update status internally ofc).
Also I have no idea how these "mValues" are being used and. I think there a re lots of options to make the operation more clear, these are just raw ideas:
1) Creating a HeaderVar interface with a get() method that returns the requested header as string for nginx. This is basically a
https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html
We can add special parsing logic for special headers or just return the identity (output equal to input).
2) Rename this class as ProxyHeaders with a get() method. When calling the get() it returns parsed headers with correct values (the mValues).
This ismore or less the current update() except it returns values.
Since the topic is wide let's discuss together IRL

2023-08-10 08:54 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      directives.add(header);
Agree with points but also notice that this class inherits ProxyConfVar, which has its own trait and changing them is out of scope if this task. We can approach refactoring this in near future.

If the behavior is not clear we can talk about it for sure.

2023-08-16 14:24 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +  public static class Builder extends DomainAttrItem.Builder {
I have several questions about this Builder class.
1. Does it need to be public? With IntelliJ I don't see any usage. If the design of this builder (and relative class) is to be used inside its package only, then the builder too should be marked as `package-private` (i.e remove the `public` attribute)
2. Add `@author` tag on the builder


On a final note, I see you're creating a hierarchy of Builders and of DomainAttrItem. I've checked it out and I think this is a slippery slope for something that will be difficult to maintain in the future. Instead of extending DomainAttrItem I'd make use of `Try` object, encapsulating the exception if something bad happens, and returning the expected objet if everything is fine. This way, we avoid also the `instanceof` that are present in `ProxyConfGen` that violates SOLID principles.

2023-08-16 14:28 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +    public DomainAttrExceptionItem buildWithException(ProxyConfException exception) {
This is super fragile. Another user will end up confused about calling `build` or `buildWithException`. I suggest overriding `build` and directly return `DomainAttrExceptionItem` instead.

2023-08-16 14:30 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
>  class DomainAttrExceptionItem extends DomainAttrItem {
This hierarchy makes little sense imo. An Exception shouldn't extend a parent class. This is just exploiting the Java type system, but it is not maintainable nor a sane design choice.

2023-08-16 14:32 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  DomainAttrItem(Builder builder) {
You shouldn't pass the builder here. It was correct as it was done previously. Please revert this and pass all the arguments to the constructor. The builder itself will take care to call the constructor with all the correct parameters (also fix the constructor visibility to `private`)

2023-08-16 14:33 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +    public Builder(String domainName, String virtualHostname, String virtualIPAddress) {
In order to set mandatory parameters instead of using the builder constructor consider instead the Step Builder pattern: https://www.javacodegeeks.com/2013/05/building-smart-builders.html

2023-08-16 14:34 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  public static class Builder {
`DomainAttrItem` is not public but the builder is. Is this intended behavior? If not fix the visibility please (all the methods inside the class too)

2023-08-16 14:35 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +  static final String DEFAULT_WEB_LOGIN_PATH = "/static/login/";
I don't know why this variable is package private. It can be put as `private` instead.

2023-08-16 14:37 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +    mConfIncludesDir = mConfDir + File.separator + mIncDir;
I don't know why you moved this line here. Please revert it as it was, that was the correct way. Doing stuff in static block is strongly discouraged, and I'd seek ways to eliminate this block instead of making it bigger.

2023-08-16 14:38 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +          String webUiLoginUrl = entry.getAttr(ZAttrProvisioning.A_carbonioWebUILoginURL, "");
Mark it as `final`

2023-08-16 14:38 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +          String webUiLogoutUrl = entry.getAttr(ZAttrProvisioning.A_carbonioWebUILogoutURL, "");
Mark it as `final`

2023-08-16 14:38 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +          String adminUiLoginUrl = entry.getAttr(ZAttrProvisioning.A_carbonioAdminUILoginURL, "");
Mark it as `final`

2023-08-16 14:38 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +          String adminUiLogoutUrl = entry.getAttr(ZAttrProvisioning.A_carbonioAdminUILogoutURL, "");
Mark it as `final`

2023-08-16 14:40 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +    // Add domain the response headers list variables for web
Please remove code comments. They make the code less maintainable.

2023-08-16 14:40 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +    // Add domain custom login and logout variables for webUi and AdminUi
Please remove code comments. They make the code less maintainable.

2023-08-16 14:45 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/WebCustomLoginUrlVar.java
> +  public WebCustomLoginUrlVar(
This constructor shouldn't be `public`, instead `package-private`. Please fix the visibility accordingly.

2023-08-16 14:46 UTC, Polpetta commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVar.java
> +  public WebCustomLogoutRedirectVar(
Fix visibility to `package-private`.

2023-08-16 15:19 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      // Handle CSP header
done

2023-08-16 15:19 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +        String newCspValue = generateModifiedCspHeaderValue(header.value);
done

2023-08-16 15:19 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +  String generateModifiedCspHeaderValue(String cspValue) {
done

2023-08-16 15:20 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +  String extractConnectSrcDirective(String cspHeader) {
done, moved to `ProxyConfUtil`

2023-08-16 15:22 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> + * @author jiankuan, Keshav Bhatt
done.

2023-08-16 15:23 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +   * Get the associated exception.
done

2023-08-16 15:23 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +  public ProxyConfException getException() {
done.

2023-08-16 15:26 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +  public static class Builder extends DomainAttrItem.Builder {
removed the builder class, due to no usages.

2023-08-16 15:26 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +    public DomainAttrExceptionItem buildWithException(ProxyConfException exception) {
removed, as not useful anymore.

2023-08-16 15:28 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
>  class DomainAttrExceptionItem extends DomainAttrItem {
You are right, the reason is explained in the javadoc :)

`The visit of com.zimbra.cs.account.ldap.LdapProvisioning can't throw the exception out. Therefore, uses this special item to indicate exception.`

2023-08-17 07:18 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  DomainAttrItem(Builder builder) {
fixed.

2023-08-17 07:19 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  public static class Builder {
fixed.

2023-08-17 07:24 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/ProxyConfGen.java
> +    mConfIncludesDir = mConfDir + File.separator + mIncDir;
This was done to avoid illegal forward referencing of variable that composes mConfIncludesDir. This issue was happening due to inteiij rearraging the code. This will have no major impact.

2023-08-17 07:26 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +    public Builder(String domainName, String virtualHostname, String virtualIPAddress) {
using fluent complete builder.

2023-08-29 07:18 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      String key,
@keshavbhatt  we discussed AddHeadersVar is the add_header directive of Nginx. We can put it in JavaDoc

2023-08-29 07:22 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      String key,
Also "key" in this case is header name, right? I would just make it clear with variable naming

2023-09-06 14:22 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      String key,
Provided javadoc. It is called keyword now and is aligned with the name suggested by the base class. 

"keyword is word for this variable that will be used to explode the value in nginx templates"

2023-09-06 14:25 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +      String description,
> Why is description needed
This represents the description of this ProxyConfVar.

> Also: description of what?
description of this ProxyConfVar offcourse.

Also note that these things are not made up or added for fun. Reading and understanding the code can help understand why these things are involved.

2023-09-06 14:28 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVar.java
> +  String generateModifiedCspHeaderValue(String cspValue) {
CSPHeaderVar is not something that represent a proxyconfvar. It is something that is a header which is already covered by add_header proxyconfvar. hence it is handled within the add_header.

2023-09-06 14:29 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrExceptionItem.java
> +  }
I did not created this exception class. Renaming it is beyond the scope of this task.

2023-09-06 14:37 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> Consider using constructor without passing a builder, instead passing each field.

IDK if this already became outdated. If not please let me know what you are refering to. 

Also i checked possibility of making the constructor private, but it causes issues in DomainAttrExceptionItem since it extends DomainAttrItem.

2023-09-11 10:12 UTC, frisonisland requested changes
I have added some comments, understanding that for now the ProxyConfGen design will be still the same, as it will impact too many classes

2023-09-11 10:12 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
GIven these two tests are nearly the same, is it possible to make them more compact? Perhaps using parameterized tests we can pass one or more urls in input

2023-09-11 10:12 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +    MailboxTestUtil.initServer();
Why do we need to spin up the whole Mailbox? Perhaps these classes are using the Provisioning in a static way underneath? If so, is it possible to provide the Provisioning in constructor so we are able to Unit Test the class?
Asking because I see we are not doing any setup operation on variables.
I think a test where we would need to start the mailbox should be for example: write web.custom.logout.redirect variable to LDAP, check the template file from proxyconfgen contains the correct value

2023-09-11 10:27 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  interface FinalStep {
@frisonisland we are implementing Step builder. 
https://www.svlada.com/step-builder-pattern/
https://medium.com/@castigliego/step-builder-pattern-3bcac4eaf9e8

2023-09-11 10:27 UTC, keshavbhatt commented on store/conf/attrs/attrs.xml
> +<attr id="3138" name="carbonioAdminUILoginURL" type="string" max="256" cardinality="single" optionalIn="globalConfig,domain" flags="domainInfo,domainAdminModifiable" requiresRestart="nginxproxy" sinc
Yes.

2023-09-11 11:55 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
> GIven these two tests are nearly the same, is it possible to make them more compact? Perhaps using parameterized tests we can pass one or more urls in input

It will look something like the following, which is more confusing then keeping them separeate i think.

```
class AddHeadersVarTest {
  private Provisioning provisioning;

  @BeforeEach
  void setUp() {
    provisioning = mock(Provisioning.class);
  }

  @ParameterizedTest
  @MethodSource("testData")
  void update_should_modifyCspHeaderValueCorrectly(
      String key, ArrayList<String> responseHeaders, String description,
      Map<String, String> customLogInLogoutUrlValueMap, String expectedCspValue)
      throws ServiceException, ProxyConfException {

    final AddHeadersVar addHeadersVar =
        new AddHeadersVar(provisioning, key, responseHeaders, description,
            customLogInLogoutUrlValueMap);

    addHeadersVar.update();

    assertEquals(expectedCspValue, addHeadersVar.confValue());
  }

  private static Stream<Object[]> testData() {
    return Stream.of(
        new Object[]{
            "web.add.headers.vhost",
            createResponseHeadersList(),
            "add_header directive for vhost web proxy",
            createCustomLogInLogoutUrlValueMap(),
            "add_header Content-Security-Policy default-src 'self'; connect-src 'self' *.test.tools"
                + " https://auth.test.com https://auth.test.com/logout; script-src 'self';;"
        },
        new Object[]{
            "web.add.headers.default",
            createResponseHeadersList(),
            "add_header directive for vhost web proxy",
            createCustomLogInLogoutUrlValueMapWithAdminUrls(),
            "add_header Content-Security-Policy default-src 'self'; connect-src 'self'"
                + " *.test.tools https://auth.test.com https://admin-auth.test.com/logout"
                + " https://auth.test.com/logout https://admin-auth.test.com; script-src 'self';;"
        }
    );
  }

  private static ArrayList<String> createResponseHeadersList() {
    final ArrayList<String> responseHeaders = new ArrayList<>();
    responseHeaders.add(
        "Content-Security-Policy: default-src 'self'; connect-src 'self' *.test.tools;"
            + " script-src 'self';");
    return responseHeaders;
  }

  private static Map<String, String> createCustomLogInLogoutUrlValueMap() {
    final Map<String, String> customLogInLogoutUrlValueMap = new HashMap<>();
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioWebUILoginURL, "https://auth.test.com");
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioWebUILogoutURL, "https://auth.test.com/logout");
    return customLogInLogoutUrlValueMap;
  }

  private static Map<String, String> createCustomLogInLogoutUrlValueMapWithAdminUrls() {
    final Map<String, String> customLogInLogoutUrlValueMap = new HashMap<>();
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioWebUILoginURL, "https://auth.test.com");
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioWebUILogoutURL, "https://auth.test.com/logout");
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioAdminUILoginURL, "https://admin-auth.test.com");
    customLogInLogoutUrlValueMap.put(
        ZAttrProvisioning.A_carbonioAdminUILogoutURL, "https://admin-auth.test.com/logout");
    return customLogInLogoutUrlValueMap;
  }
}
```

2023-09-11 11:59 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/WebCustomLogoutRedirectVarTest.java
> +    MailboxTestUtil.initServer();
resolved in IRL.

2023-09-11 12:11 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/util/proxyconfgen/DomainAttrItem.java
> +  interface FinalStep {
Thx, talked IRL and now makes more sense to me

2023-09-11 12:29 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
You mean swaping the key? If yes,
the key is only to store a value, value can be anything. We use appropriate key in our templates to expload whatevery is stored in it by the proxyconfgen.

2023-09-11 12:33 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
Also be careful about map ordering. The example provided above fails due to computation of values in the implementation: sometimes it returns https://auth.test.com before https://auth.test.com/logout and viceversa.
Can we be sure the order of values is always the same?

2023-09-11 12:34 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
I am fine with use of parameterized tests when the test data is almost same, but in this case they are not just urls but different types of URLs. Offcourse this setup will work but the issue i see with this is: It doesn't make clear distinction between the test data.  I am also considering future of this test class where will may add more tests.
I decide to keep them separate.

2023-09-11 12:43 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
Another thing: these tests are telling us a lot about how we use our classes. 
AddHeadersVar uses customLoginLogoutUrls to iterate over values(), which is an array, so why not directly pass customLoginLogoutUrls as array instead of map? -> Key are never accessed + this way order of values is preserved

2023-09-11 13:31 UTC, keshavbhatt commented on store/src/test/java/com/zimbra/cs/util/proxyconfgen/AddHeadersVarTest.java
> +  void update_should_modifyCspHeaderValueCorrectly() throws ServiceException, ProxyConfException {
Probably the map was introduces in the past when the implementaiton was different. The featuer reuqest changed later and the map remained there :D

Anyway, the latest changes are using List.

2023-09-11 13:42 UTC, frisonisland approved these changes

2023-09-12 08:38 UTC, Polpetta approved these changes

2023-09-12 11:21 UTC, merged