feat: [CO-779] Use latest Preview SDK
zextras/carbonio-mailbox pull request #302
Opened 2023-08-04 07:49 UTC by inno-dima

**What has changed**

- bump preview-sdk version to 1.0.2
- Added GIF support in PreviewServlet.java

2023-08-04 12:05 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/PreviewServlet.java
> +    GIF
Tests for this feature?

2023-08-04 12:07 UTC, inno-dima commented on store/src/main/java/com/zimbra/cs/service/PreviewServlet.java
> +    GIF
I'll do it, but I'm not sure how to test it properly. Let's discuss it on Monday

2023-08-04 12:40 UTC, frisonisland requested changes
It is not clear what is needed to add GIF support. 
Should we add tests for parsing?
Consider starting from some tests that define the use case. Also I see this class is way too big, definitely a smell, consider refactoring it if it helps testing! (I'm sure it will).
For example: PreviewQueryParameters class that is used in the client call. It might help splitting the servlet in Controller and another Service/Logic classs

2023-08-16 15:17 UTC, Polpetta requested changes
As @frisonisland said, I agree to the fact that there's the necessity to add tests for the new feature.

I also added a minor improvement.

2023-08-16 15:17 UTC, Polpetta commented on pom.xml
> +        <version>1.0.2</version>
Please move the version as a POM variable. It makes easy to see all the dependency versions since we'll gradually group them all in one place.

2023-08-24 12:07 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/PreviewServlet.java
> +    GIF
I was thinking that perhaps we can add a test that attests the gif output_format is working correctly

2023-09-19 09:49 UTC, Polpetta approved these changes

2023-09-25 15:02 UTC, frisonisland approved these changes

2023-09-26 08:52 UTC, keshavbhatt approved these changes

2023-10-04 15:33 UTC, merged