chore: [CO-739] limit LE certificate management for delegated admins
zextras/carbonio-mailbox pull request #306
Opened 2023-08-14 13:20 UTC by aheeva-yuliya

**What has changed:**

issueCert api will be available for global admins, domain admins (on their domains) and delegated admin with setDomainAdminDomainAttrs right (instead of getDomain right).

Also modified response message a little.

2023-08-16 10:02 UTC, keshavbhatt requested changes
Asked for minor changes.

2023-08-16 10:02 UTC, keshavbhatt commented on store/src/main/java/com/zimbra/cs/service/admin/IssueCert.java
> +    final String chain =
Variable name `chain` is little misleading,
```suggestion
    final String chainType =
```

2023-08-16 13:16 UTC, keshavbhatt approved these changes

2023-08-16 15:25 UTC, Polpetta requested changes
I've made some minor suggestions! I've also a question: why did you add `handle` at the beginning of tests? :thinking:

2023-08-23 07:45 UTC, frisonisland approved these changes

2023-08-23 09:25 UTC, Polpetta approved these changes

2023-08-23 09:34 UTC, merged