refactor: previewservlet
zextras/carbonio-mailbox pull request #308
Opened 2023-08-23 15:08 UTC by frisonisland

This PRs adds a new implementation of Preview using PreviewController with Jersey.
The implementation is done starting from an OAS 3 spec and using codegen.
The reason is to introduce a Framework that helps with API validation and routing, and also be able to add DI.

## Flow
- previewApi.yaml for API schema.
- web.xml.production adds the servlet registration PreviewResourceConfig under /api/*, which scans classes to register paths
- PreviewResourceConfig binds Jersey DI to Guice DI
- PreviewServletModule is a Guice Module that binds dependencies
- PreviewController implements PreviewApi, which is exposed under /preview.
- PreviewUseCase implements the core logic of previewing an attachment

## Other changes
- added a class to make Http requests to other mailboxes (MailboxHttpClient) to get attachments
- added AuthorizationFilter to filter incoming requests and authorize based on COOKIE. Only standard user.
- refactor MailboxAttachmentService to LocalMailboxAttachmentService
- implement MailboxHttpAttachmentService to get attachment over http, since requested attachment account may not be local

2023-09-18 15:05 UTC, inno-dima approved these changes

2023-09-18 15:05 UTC, inno-dima commented on store/src/test/java/com/zextras/mailbox/servlet/MailboxResourceConfigTest.java
> +  //  }
I think we should remove commented code

2023-09-19 07:17 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/servlet/MailboxResourceConfigTest.java
> +  //  }
> I think we should remove commented code

Agree, this code was to test DI if I'm not wrong I will double check-it before removing it

2023-09-19 07:18 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +    // TODO: test failure
> Is it relevant now?

Perhaps not anymore, will check again and remove the comment

2023-09-20 13:15 UTC, Polpetta approved these changes

2023-09-25 14:19 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/servlet/MailboxResourceConfigTest.java
> +  //  }
I added the test actually

2023-09-26 08:46 UTC, frisonisland commented
TODO: 
- If preview service is down we answer 404
- If preview service is live and answers with 500 error we return 404

2023-09-26 15:18 UTC, keshavbhatt requested changes
Most of the changes looks good, I suggested some changes focusing to improve redability and maintinability of the code. The oragnization of some classes is not clear and we need to talk about it. Also there are some concerns about error handling here and there.

2023-09-26 15:18 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/preview/usecase/PreviewUseCase.java
> +  public Try<Tuple2<MimePart, BlobResponse>> getAttachmentAndPreview(
javadoc, plus why this method is supposed to have multiple responsibilities? (getting attachment and getting preview for that attachment) 

Breaking it down into two will help in simplifying the code and will make the error handling cleaner.

2023-09-26 15:18 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/preview/usecase/PreviewUseCase.java
> +public class PreviewUseCase {
javadoc.

2023-09-26 15:18 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/servlet/PreviewServletModule.java
> +public class PreviewServletModule extends AbstractModule {
provide javadoc,

2023-09-26 15:26 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +    String filename =
```suggestion
    final String filename =
```

2023-09-26 15:30 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/preview/usecase/PreviewUseCase.java
> +  public Try<Tuple2<MimePart, BlobResponse>> getAttachmentAndPreview(
Not really, the solution would be to create another composite object which is a mix between the two

2023-09-26 15:31 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/MailboxHttpAttachmentService.java
> +  public Try<MimePart> getAttachment(
On a implementation? Isn't the JavaDoc already in the interface?

2023-09-26 15:32 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +   * @param userServletRequest request for {@link UserServlet}
It's a pram though. Perhaps:
```suggestion
   * @param userServletRequest a {@link UserServlet} request
```

2023-09-26 15:32 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +   * @param userServletRequest request for {@link UserServlet}
Also "relevant" depends on a lot of things, it depends on the use case. But since UserServlet was made so generic and without doc this is what we get

2023-09-26 15:35 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +  public Try<UserServletResponse> callUserServlet(
It's a get request to the user servlet but it is not specific, parameters may. Unfortunately the user servlet doesn't have any doc/explicit endpoints, else we would have use that. I'm talking about something like openapi

2023-09-26 15:40 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/UserServletRequest.java
> +  public static UserServletRequest buildRequest(String authType, String itemId, String itemPart) {
I think it's a bit pedantic asking javadoc for everything, builders for example. The method should be self-explanatory. It's almost like writing javadoc fro getters and setter to me.

2023-09-26 16:01 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/UserServletRequest.java
> +    return Objects.equals(this.toString(), o.toString());
Mmmh this class is a representation of a UserServlet request. There are tools that generate this code from an api-spec, doing it manually is a burden, I will see if it's possible to generate it from an openapi spec.

2023-09-26 16:06 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/filter/AuthorizationFilter.java
> +  public void filter(ContainerRequestContext ctx) throws IOException {
Check the interface, it provides the javadoc, do we need to overwrite it?

2023-09-26 16:08 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/preview/resource/PreviewController.java
> +public class PreviewController implements PreviewApi {
Weel yes but perhaps we can work on swagger description of the api.
Check the interface PreviewApi class, it has a description field

2023-10-09 11:17 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +  public Try<UserServletResponse> callUserServlet(
Renamed to doUserServletGetRequest

2023-10-09 11:18 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +      return Try.failure(ServiceException.FAILURE("Status code not 200.", null));
Added MailboxHttpClientException which accepts a status code + string message/reason. For now it is empty as it is unknown if the UserServlet returns a reason as string message

2023-10-09 11:18 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/preview/usecase/PreviewUseCase.java
> +  public Try<Tuple2<MimePart, BlobResponse>> getAttachmentAndPreview(
Added AttachmentPreview class to represent the domain object

2023-10-09 11:24 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/servlet/PreviewServletModule.java
> +public class PreviewServletModule extends AbstractModule {
added

2023-10-09 11:25 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +    String filename =
done

2023-10-09 11:25 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/MailboxHttpClient.java
> +    String contentType =
done

2023-10-09 11:26 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/UserServletRequest.java
> +    return Objects.equals(this.toString(), o.toString());
method removed as was used only for testing purposes

2023-10-09 11:26 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/UserServletRequest.java
> +  final String itemPart;
made private only

2023-10-09 11:27 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/client/UserServletResponse.java
> +  final InputStream content;
done

2023-10-09 11:31 UTC, frisonisland commented
Closing as there are no strong reason to refactor (other than decoupling and maintainability) and there is no interests on using new tools and investing on a different design

2023-10-09 11:32 UTC, frisonisland commented
Closing as there are no strong reason to refactor (other than decoupling and maintainability) and there is no interests on using new tools and investing on a different design

2023-10-09 11:32 UTC, closed without merging