feat: [CO-778] zimlet code cleanup
zextras/carbonio-mailbox pull request #310
Opened 2023-08-24 14:05 UTC by keshavbhatt

**What has changed:**
- removed all zimlet related SOAP APIs
- deprecated zimlet related attributes

**NOTE for future:**

**We can perform further cleanup, as some part of the code was kept for the following reason.**
- Zimlet Entry was kept : “zimlet”s are LDAP entry types, and many LDAP attributes are present in the system which are expecting this entry in the system. If we remove the zimlet entry type from backend and schema in our coming update, we leave users to the risk where they will have some of ldap entries in locked state(this happens when LDAP schema is not aware of the entry type due to missing definition in schema). For this reason the entry will be kept intact in the codebase.
- Attempting to perform further cleanup affects GetInfo SOAP command, resulting in removal of some zimlet specific fileds(elements,attributes & properties) from the response. This is breaking the Carbonio Web UI and admin UI as they are still looking for these fileds for no obvious reasons. Cleanup in the Rights was also skipped for the same reason.

2023-08-28 15:34 UTC, frisonisland requested changes
Cleanup looks good to me, just have a suggestion about carbonio version usage in ant

2023-08-28 15:34 UTC, frisonisland commented on store/ant-store.xml
> -      <sysproperty key="carbonio.version" value="${carbonio.buildinfo.all}"/>
I just noticed carbonio.buildinfo.version is never set. and "zimbra" is. What if we declare carbonio.buildinfo.version in place of zimbra.buildinfo.version for the future? I saw it is defined in ant-build-common and never used.

2023-08-29 07:48 UTC, Polpetta approved these changes

2023-08-29 07:57 UTC, keshavbhatt commented on store/ant-store.xml
> -      <sysproperty key="carbonio.version" value="${carbonio.buildinfo.all}"/>
Yes, What i noticed while working on this PR is that there is no property called carbonio.buildingo.all while there was zimbra.buildinfo.all so for a quick fix i used the it. We need to provide the carbonio one if it is really required.

2023-08-30 06:52 UTC, aheeva-yuliya approved these changes

2023-08-30 07:11 UTC, frisonisland commented on store/ant-store.xml
> -      <sysproperty key="carbonio.version" value="${carbonio.buildinfo.all}"/>
zimbra.buildinfo.all is not used from what I checked, that's why I suggested to define carbonio.buildinfo.all in place of it

2023-08-30 07:20 UTC, frisonisland approved these changes

2023-08-31 07:28 UTC, merged