feat: [CO-732] delete mountpoints for revoked folders
zextras/carbonio-mailbox pull request #326
Opened 2023-09-12 07:52 UTC by aheeva-yuliya

2023-09-12 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-mailbox?pullRequest=326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-mailbox?pullRequest=326) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: frisonisland<br/>:white_check_mark: aheeva-yuliya<br/>:white_check_mark: Polpetta<br/>:white_check_mark: inno-dima<br/>:x: TjHobby<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-mailbox?pullRequest=326) it.</sub>

2023-09-13 12:00 UTC, Polpetta approved these changes

2023-09-18 11:27 UTC, keshavbhatt requested changes
Asked for minor changes for now.

2023-09-20 08:05 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/mail/CreateFolder.java
> +          ZimbraLog.soap.warn("error ignored while rolling back folder create", nse);
@keshavbhatt it wasn't changed. it seems like bcz of formating but we didn't. you can check once again with intellij

2023-09-20 08:42 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/mail/ItemAction.java
> +          reconstructedConvIds.add(id);
@keshavbhatt this also wasn't changed

2023-09-20 09:19 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/service/GranteeService.java
> +    NamedEntry nentry = provisioning.get(AccountBy.name, email);
it's not final

2023-09-20 09:31 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/util/GrantType.java
> +  GRANTEE_USER(
we decided not to rename it

2023-09-21 07:49 UTC, frisonisland requested changes

2023-09-25 08:30 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/EmptyFolderActionUseCase.java
> +public class EmptyFolderActionUseCase {
Done

2023-09-25 08:31 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/mail/ItemActionUtil.java
> +    long ret =
Done

2023-09-25 08:33 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/mail/ItemActionUtil.java
> +public class ItemActionUtil {
This class was removed. It had one method "validateGrantExpiry" which was moved to ACLHelper

2023-09-25 08:35 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/ImportFolderActionUseCase.java
> +                              "unable to locate the mailbox for the given accountId"));
We made a method in Mailbox which returns a Try and throws a similar exception as failure. 
We plan on using this new Mailbox method to avoid repetition

2023-09-25 08:41 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/converter/GrantConverter.java
> +public class GrantConverter {
Done

2023-09-25 08:45 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/mail/CreateFolder.java
> +        new ACLUtil()
Done

2023-09-25 08:46 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/service/mail/ItemActionUtil.java
> +  public long validateGrantExpiry(String grantExpiry, long maxLifetime) throws ServiceException {
Done

2023-09-25 15:10 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/FreeBusyFolderActionUseCase.java
> +public class FreeBusyFolderActionUseCase {
Closing, not very important for now

2023-09-25 15:12 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/SetUrlFolderActionUseCase.java
> +  public Try<Void> setFolderUrl(
We noticed the enableFreeBusy option is managed by alterTag and FreeBusyFolderAction already provides the same behavior, so we can use that

2023-09-25 15:43 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/usecase/UpdateFolderActionUseCaseTest.java
> +  void shouldReturnFailureIfFolderItemIdDoesntBelongToUserMailbox() throws ServiceException {
Mocked

2023-09-25 15:44 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/usecase/UpdateFolderActionUseCaseTest.java
> +    when(itemId.getId()).thenReturn(0);
Made test name more explicit

2023-09-26 08:34 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/usecase/service/GranteeServiceTest.java
> +  }
We used InMemoryDirectoryServer

2023-09-26 08:37 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/service/MountpointService.java
> +  }
We have to rethink the mountpoint service because it does not perform recursive deletion

2023-09-26 08:38 UTC, frisonisland approved these changes

2023-09-26 13:13 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/EmptyFolderActionUseCase.java
> +                              "unable to locate the mailbox for the given accountId"));
Done

2023-09-26 13:14 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/FreeBusyFolderActionUseCase.java
> +    return excludeFreeBusy(operationContext, accountId, folderId, true);
Done

2023-09-26 13:14 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/util/GrantType.java
> +                            "invalid grantee type for revokeOrphanGrants", null)));
Done

2023-09-26 13:14 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/util/GrantType.java
> +                            "invalid grantee type for revokeOrphanGrants", null)));
Done

2023-09-26 13:14 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/util/GrantType.java
> +public enum GrantType {
Done

2023-09-26 13:15 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/service/mail/ItemActionUtil.java
> +public class ItemActionUtil {
Done

2023-09-26 13:15 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/ImportFolderActionUseCase.java
> +                              "unable to locate the mailbox for the given accountId"));
Done

2023-09-26 13:15 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeFolderActionUseCase.java
> +   * deletes linked to revoked folder mountpoints.
Done

2023-09-26 13:16 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeFolderActionUseCase.java
> +          Account granteeAccount = Provisioning.getInstance().getAccountById(granteeId);
Done

2023-09-26 13:16 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeOrphanAccessFolderActionUseCase.java
> + * Use case class to revoke orphan access from a folder.
Done

2023-09-26 13:16 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeOrphanAccessFolderActionUseCase.java
> +          SearchDirectoryOptions opts = new SearchDirectoryOptions();
Done

2023-09-26 13:16 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeOrphanAccessFolderActionUseCase.java
> +          String query = "(" + ZAttrProvisioning.A_zimbraId + "=" + zimbraId + ")";
Done

2023-09-26 13:16 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RevokeOrphanAccessFolderActionUseCase.java
> +      boolean canAdmin =
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/SyncFolderActionUseCase.java
> +    return innerSyncCall(operationContext, accountId, folderId, true);
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/UpdateFolderActionUseCase.java
> +  public Try<Void> update(
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/UpdateFolderActionUseCase.java
> +            ACL acl =
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/UseCaseDI.java
> +public class UseCaseDI extends AbstractModule {
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/factory/OperationContextFactory.java
> + * Factory class to create an {@link OperationContext}.
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/factory/ItemIdFactory.java
> + * Factory class to create an {@link ItemId}.
Done

2023-09-26 13:18 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/service/GranteeService.java
> +      InternetAddress addr = new InternetAddress(email);
Done

2023-09-26 13:19 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/service/GranteeService.java
> +      Account authacct =
Done

2023-09-26 13:19 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/account/accesscontrol/ACLUtil.java
> +  }
Done

2023-09-27 08:07 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/ActiveSyncFolderActionUseCase.java
> + * Use case class to manage ActiveSync support on a folder.
Done

2023-09-27 08:08 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/RefreshFolderActionUseCase.java
> + * Use case class to refresh a folder.
Done

2023-09-27 09:04 UTC, keshavbhatt requested changes
I request a few more minor changes. Rest looks good to me.

2023-09-27 09:19 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/usecase/service/MountpointService.java
> +    FolderNode folderTree =
@keshavbhatt @aheeva-yuliya @inno-dima  Just one thing about these comments on final and javadoc: I think we should setup some rules with linting, else it becomes a waste of time for people that have to review to say "add javadoc" or "final". 
IDEs should take already care of these things and having a PR with lots of comments saying the issue is just a "final" is not good IMHO

2023-09-27 09:33 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/folderaction/GrantFolderAction.java
> +              Grant grantResult =
Done

2023-09-27 09:41 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/folderaction/RevokeFolderAction.java
> +                              .collect(Collectors.toList());
Done

2023-09-27 09:43 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/service/MountpointService.java
> +    FolderNode folderTree =
Done

2023-09-27 09:43 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/usecase/service/MountpointService.java
> +    List<Mailbox.FolderNode> granteeSubFolders = folderTree.getSubFolders();
done

2023-09-29 14:10 UTC, keshavbhatt approved these changes

2023-10-06 11:06 UTC, merged