Feat/CO-168 stats compatible with prometheus
Zextras/carbonio-mailbox pull request #33
Opened 2022-04-29 10:09 UTC by keshavbhatt

These changes Make mailbox stats compatible with Prometheus metrics.

2022-04-29 12:57 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumper.java
> +    writer.close();
I would consider to close it on a finally. Maybe with a try resources.
This is because if any exception happens at least we can close the file.

2022-04-29 13:16 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
Ok, I'm seeing that some logic of StatsDumperPrometheus is the same as StatsDumper.
Also seeing StatsDumper and StatsDumperPrometheus makes me think that one is an implementation of another (or a specific case).

At least I would consider a class extension since there are some common patterns: file directory exists, same runnable, etc.

2022-04-29 14:37 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumper.java
> +    writer.close();
I have made the suggested changes. 
Note that we don't want to handle any exception in this case, if some exception occurs they are passed to the method.

2022-04-29 14:51 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
Yes, I agree and it makes 100% sense. But I did not consider this while extracting logic from StatsDumper to implement something similar called StatsDumperPrometheus. I thought we might need to change the behavior at some point maybe in the future.
Also, I think tightly coupling a Schedule class will prevent us from changing the scheduling of two different dumpers who can have different requirements(that's why we have two of them separated). I hope I am clear, we can have a quick call about this later if we want.

2022-04-29 15:20 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
I get your point.
But consider that having a simple Scheduler class will not introduce tight couple, but more flexibility instead.
My first (wrong) suggestion  of extending StatsDumper would have introduced tight coupling (inheritance), while having a Scheduler class + Callable will favor composition and flexibility. The two Callable WILL have different logic :)
For example this way we could:
* define a common Scheduler if we want to maintain the same clock cycle (schedule interval).
* define two different Scheduler if we want to have different intervals for Prometheus stats and standard stats
* have specific schedule interval for Imap, Pop, etc. for example

Something like
```
public class StatsScheduler {
        
        private final long interval;
        public StatsScheduler(long interval) {
            this.interval = interval;
        }
        
        public void schedule(Callable<Void> callable) {
            // your logic about logging, etc.
            Try.of(callable::call);
        }
    }```
    and we will recycle the code in the schedule() method. Just a suggestion.

2022-04-29 15:41 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
You are right but if you take a look at the ZimbraPref class we are scheduling dumpers and not the stats data source. Stats data sources bring the stats data when different services push them. Then when the dumper runs at a defined interval they collect the data from different sources and write them to the destination. 

We can use what you are proposing but I don't see any major benefits. Also, note that going this way will affect various other implementations that already exist and that have nothing to do with this PR.

2022-04-29 15:57 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
My idea was to schedule the dumpers, not the data sources! That's why I proposed schedule(Callable) -> the callable is the dumper.
The "only" benefits I see are: more flexibility + easier testable code (more unit). You could even assert that Prometheus dumper is indeed in the correct format, without starting a schedule or a thread.
Also I proposed these changes because I saw that in ZimbraPerf class we call StatsDumper.schedule, or StatsDumperProm.schedule.
Instead we could have statsScheduler.schedule(stdDumper), or statsScheduler.schedule(promDumper), where statsScheduler = new StatsScheduler(interval).
I assumed this was the place were its all tied together, so it didn't seem too much of a problem.
Anyway feel free to consider or reject the suggestion, not a blocker, but I think many developers will be grateful if we can favor composition and break things into smaller pieces (even if it will require a bit more effort)!

2022-05-04 09:39 UTC, Polpetta reviewed
A part from the scheduler stuff the rest is fine. I've commented some tip and trick here and there

2022-05-04 10:34 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
I tried ScheduledExecutorService in past to avoid thread sleep but it didn't work in this case. Basically, I was not getting any stats. 

**Why we are having thread sleep**
If you will check the design they are calling thread sleep on a runnable method body the runnable task is then executedin a separate thread which is responsible for reporting metrics, hence it will not block the other routines. The design is async since we are using separate threads for processing the dump.
In the past Zimbra avoid using their TaskSchedular class for the very same reason.


**To summarise the design**: We have Two classes StatsDumper and StatsDumperPrometheus (which inherits a few functionalities from StatsDumper but has completely different use-case)

**Why we are using callable and not runnable** -> We have a few exceptions that we want to handle, from the documentation I confirm that Runnable cannot throw checked exceptions, Runnable is a functional interface and its run method does not accept parameters. We want to pass varying parameters to collect stats from different activity trackers in our case. Callable is an improved version of runnable(from Baeldung).

For me, this design is okay since it already fulfills the requirement that is on our table.

I can extract a class to make it more DRY as suggested but we will end up doing the same thing we are doing right now. I can explain why if you want in a quick call as always :P

2022-05-04 12:08 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  }
I have extracted a Runnable, we are using it to create instances and passing them to thread.

2022-05-04 13:51 UTC, frisonisland commented on common/src/java-test/com/zimbra/common/stats/PrometheusFormatterTest.java
> +  public void ShouldCleanHeaderWhenCalledSanitizeHeader() {
The convention is to use lowerCamelCase for methods

2022-05-04 13:53 UTC, frisonisland commented on common/src/java-test/com/zimbra/common/stats/PrometheusFormatterTest.java
> +  public void AddTimestampWhenCalledAddTimeStamp() {
Also tests should start with "should" convention (we decided together on this I believe).

2022-05-04 13:57 UTC, keshavbhatt commented on common/src/java-test/com/zimbra/common/stats/PrometheusFormatterTest.java
> +  public void ShouldCleanHeaderWhenCalledSanitizeHeader() {
my bad :smile_cat:

2022-05-04 14:21 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +    try (FileWriter writer = new FileWriter(file, false)) {
Any reason why we are writing not appending to file?

2022-05-04 15:01 UTC, frisonisland commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
@keshavbhatt so are you saying that using an ExecutorService with Callable<V> didn't work?

2022-05-04 15:02 UTC, frisonisland requested changes
Just a couple of comments (Java Doc), and a couple of questions left about ExecutorService and file writing

2022-05-04 15:24 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +    try (FileWriter writer = new FileWriter(file, false)) {
Yes, this is because we don't want to accumulate values in these files unlike we were doing in csv. Node exporter read data from here and look for new data everytime, dont care about old one.

2022-05-11 07:37 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsDumperPrometheus.java
> +  public static void schedule(final StatsDumperDataSource dataSource, final long intervalMillis) {
@Polpetta Thanks for the deep investigation. We will do the refactoring in the next interation. We can have a quick call to specify what to use and what not.

2022-05-12 12:02 UTC, frisonisland approved these changes

2022-05-12 12:17 UTC, Polpetta approved these changes

2022-05-12 12:22 UTC, merged