feat: [CO-844] delete user should revoke all grants
zextras/carbonio-mailbox pull request #348
Opened 2023-10-04 07:44 UTC by frisonisland

Opening draft to see changes

2023-10-05 14:19 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/db/DbPool.java
> -    private static boolean isShutdown;
Now that I think about it the methods were this variable is updated are already synchornized + static, so there is no need to use an AtomicReference

2023-10-16 10:02 UTC, keshavbhatt requested changes
requested minor changes, rest looks good.

2023-10-16 12:24 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/account/usecase/DeleteUserUseCase.java
> +   * Perform the deletion of a user given its id.
minor: Performs

2023-10-16 12:24 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> + * Utility class for operation on folders. Methods were extracted from {@link
minor: operations

2023-10-16 12:25 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +  private FolderUtil() {}
minor: we could add exeption throwing in constructor like for others utility classes

2023-10-16 12:26 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +  public static Set<Folder> flattenAndSortFolderTree(FolderNode root) {
minor: could have final modifiers for parameters and later on variables

2023-10-16 12:30 UTC, aheeva-yuliya commented on store/src/main/java/com/zextras/mailbox/acl/AclService.java
> + * @author davidefrison
minor: consider adding since annotation

2023-10-16 12:34 UTC, aheeva-yuliya commented on store/src/main/java/com/zimbra/cs/db/DbPool.java
> +        isShutdown = false;
i've missed why we added this?

2023-10-16 14:31 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/service/admin/DeleteAccountTest.java
> +//  @Test
Yes, this test was removed because spinning up the SpapServlet calls a System.exit and tests fail, I will remove the test.

2023-10-16 15:16 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/account/usecase/DeleteUserUseCase.java
> +      AclService aclService,
We have decided to remove all the annotations + UseCaseDI module as the system is not using DI at the moment, except for the metrics servlet.

2023-10-16 15:26 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +  private FolderUtil() {}
We could discuss about common rules as a team, we introduced private constructor last week, now exceptions :sweat_smile:

2023-10-17 07:27 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +  private FolderUtil() {}
I think its fine to just have an empty private constructor.

2023-10-17 07:30 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +  private FolderUtil() {}
IMHO we don't have to focus on these tiny details, but of course if it is really important we can talk about having some common work guidelines for the code

2023-10-17 07:44 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/account/usecase/FolderUtil.java
> +    for (FolderNode subNode : node.mSubfolders) flattenAndSortFolderTree(subNode, flattened);
@frisonisland here as well :)

2023-10-17 07:44 UTC, keshavbhatt approved these changes

2023-10-17 09:53 UTC, merged