refactor: move db.sql from carbonio-core to appserver-db
zextras/carbonio-mailbox pull request #371
Opened 2023-11-03 12:28 UTC by frisonisland

- versions-init.sql is already in this package
- these files are needed by the appserver only

TODO:
- [] remove carbonio-build references
- [] move migrations scripts to same package
- [] deprecate/remove carbonio-db-conf repo

2023-11-03 12:52 UTC, keshavbhatt approved these changes

2023-11-03 12:55 UTC, frisonisland commented
I want to check the options also with @M0Rf30 , reason is there could be conflicts in file location (db.sql, create_database.sql) moving them from carbonio-core to this package. All the other files are in a new location and are only run manually. Also removed old migrations file that are not needed anymore. Probably in the future we will automate the migration with a tool like Liquibase or FlyWay and avoid using perl.

2023-11-03 14:54 UTC, M0Rf30 requested changes

2023-11-03 14:54 UTC, M0Rf30 commented on packages/common-appserver-db/PKGBUILD
> +  install -D "store/db/migrate/*" \
this glob doesn't expand
it should be
`install -D "store/db/migrage/"*`
with the asterisk out of quotes
you  should have a warning also on shellcheck (now that PKGBUILD are bash/sh compliant)

2023-11-03 15:18 UTC, frisonisland commented on packages/common-appserver-db/PKGBUILD
> +  install -D "store/db/migrate/*" \
Thanks, this PR is still a rough idea, I will complete it with your suggestion! Do you think there are issues in moving files from  one package to another? Anything against it?

2023-11-03 15:34 UTC, M0Rf30 commented on packages/common-appserver-db/PKGBUILD
> +  install -D "store/db/migrate/*" \
No AFAIK

2023-11-06 09:29 UTC, frisonisland commented on packages/common-appserver-db/PKGBUILD
> +  install -D "store/db/migrate/*" \
I made the changes and used rsync. Also tested packages locally starting from 23.11.0, however I get:

#0 12.66 Unpacking carbonio-common-appserver-db (4.10.0-1focal) over (4.9.1-1ubuntu1~focal) ...
#0 12.66 dpkg: error processing archive /tmp/apt-dpkg-install-as6lUI/5-carbonio-common-appserver-db_4.10.0-1focal_amd64.deb (--unpack):
#0 12.66  trying to overwrite '/opt/zextras/db/create_database.sql', which is also in package carbonio-core 4.0.28-1ubuntu1~focal

I think this requires changing carbonio-core first. Should we make carbonio-appserver-db-conf depend on carbonio-core to be sure of the update order?

2023-11-06 11:35 UTC, M0Rf30 commented on packages/common-appserver-db/PKGBUILD
> +depends=(
Why? appserver already calls carbonio-core
https://github.com/zextras/carbonio-core/blob/devel/appserver/PKGBUILD
maybe you want to add carbonio-appserver-db to carbonio-appserver

2023-11-06 11:47 UTC, frisonisland commented on packages/common-appserver-db/PKGBUILD
> +depends=(
Ok, thanks!

2023-11-06 12:13 UTC, M0Rf30 commented on packages/common-appserver-db/PKGBUILD
> +  install -D "store/db/migrate/*" \
That's because the only mandatory requirement is to update both core (4.0.28) and appserver-db.

2023-11-06 15:22 UTC, M0Rf30 commented on packages/yap.json
> +    {
Please respect the alphabetical order. here is possible (no native deps)

2023-11-06 15:22 UTC, M0Rf30 commented on Jenkinsfile
> +                            "pattern": "artifacts/x86_64/(carbonio-appserver-db)-(*).el8.x86_64.rpm",
Please respect alphabetical order

2023-11-06 15:22 UTC, M0Rf30 commented on Jenkinsfile
> +                            "pattern": "artifacts/x86_64/(carbonio-appserver-db)-(*).el9.x86_64.rpm",
Please respect alphabetical order

2023-11-06 15:45 UTC, M0Rf30 approved these changes

2023-11-08 08:34 UTC, frisonisland commented
Added few changes:
- add rhel8 container for local testing of packages
- add back carbonio-common-appserver db with empty files
I noticed using conflicts=() was keeping old cabronio-common-appserver-db in rhel8, so I thought at this point the best solution was to keep common-appserver-db as empty transient package. This allows installing carbonio-appserver-db without conflicts.
In next releases carbonio-common-appserver-db won't be released anymore

2023-11-08 08:46 UTC, M0Rf30 approved these changes

2023-11-08 08:46 UTC, M0Rf30 commented on packages/common-appserver-db/PKGBUILD
> +pkgdesclong="Transactional package - replaced by carbonio-appserver-db - will be removed in next Carbonio release 24.1.0"
pkgdesclong is not parsed anymore. It will cause no issues, simply is not evaluated in the package generation

2023-11-09 12:27 UTC, keshavbhatt approved these changes

2023-11-09 15:54 UTC, keshavbhatt approved these changes

2023-11-10 08:45 UTC, merged