[CO-276] new stats scheduler
Zextras/carbonio-mailbox pull request #38
Opened 2022-05-13 09:13 UTC by keshavbhatt

**Motivation:**
While working on [CO-168] it was found that adding new custom dumpers is adding extra threads to the system, the old implementation is also using thread.sleep() to achieve execution of these timer jobs which is leading to a busy-wait condition in each of these threads. Using fixed threads in this way is expensive for the whole system as these threads are assigned/occupied throughout the time the mailbox is running and each has to sleep for 1 minute before waking up again to do its job.

To avoid the above we came up with a new solution where we will assign fewer threads to perform the same job without losing the asynchronous behavior and concurrency. 

**Changes**
- Now using ScheduledExecutorService to schedule Dumpers
- Now using single StatsDataSource for both CSV and PROM Dumpers

2022-05-13 15:34 UTC, Polpetta requested changes
I detected some possible race conditions/deadlock while using `synchronized` and I suggested you to add some `final` here and there where you were the last committer (checked with IntelliJ)

2022-05-13 15:34 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +      List<String> columns = new ArrayList<>();
```suggestion
      final List<String> columns = new ArrayList<>();
```

2022-05-13 15:34 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +      List<Object> data = new ArrayList<>();
```suggestion
      final List<Object> data = new ArrayList<>();
```

2022-05-13 15:34 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +          a.reset();
This thing is fucked up and won't synchronize anything. I don't know what they where doing. Please remove it, but do please understand what kind of race condition could be happening here if you can

2022-05-13 15:34 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +      List<String> retVal = new ArrayList<>(1);
```suggestion
      final String line = StringUtil.join(",", data);
      final List<String> retVal = new ArrayList<>(1);
```

2022-05-17 09:53 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/stats/StatsScheduler.java
> +}
included these changes, unfortunately, it was not possible to commit here since they are outdated.

2022-05-17 12:26 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  }
they moved here automatically using the java formattter :(

2022-05-17 12:32 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  public static synchronized void initialize(ServerID serverID) {
I am using a single lock, there is no circular dependency b/w methods, Also I learned that reentrant lock is one of the alternatives to synchronization and is not required unless we require additional features the reentrant lock class provides. 
I am using reentrant lock and unlock calls only which are the same as using synchronized, correct me if m wrong,

2022-05-17 12:33 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  }
they moved here automatically using the java formattter :(

2022-05-18 08:28 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  }
moved manually.

2022-05-19 07:47 UTC, frisonisland approved these changes

2022-05-19 15:19 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  public static synchronized void initialize(ServerID serverID) {
Yes, problem is `synchronized` is not clear (at least to me) on what you're locking. In `synchronized` you're locking on `this` instance and sometimes can be confusing. Locking on a lock, on the other hand, is explicit.

In that case, you are having two `synchronized` methods in this class. This means that if a thread is calling synchMethod1 and another one is calling the other method (synchMethod2) one of those two threads will wait for the other to finish, and this doesn't make sense if there's no sync needed (synchMethod1 and 2 don't have any concurrent memory access). With a lock, you can have multiple locks for multiple methods avoiding possible unnecessary synchronization.

> I am using reentrant lock and unlock calls only which are the same as using synchronized, correct me if m wrong.
>
> I have tested both, and they work fine.

Finally yep, the calls and the behavior are apparently the same, but under the hood it's not necessary the same! Otherwise imo they wouldn't have made the `Lock` object in the first place

2022-05-19 15:27 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  public static synchronized void initialize(ServerID serverID) {
I agree.

2022-05-20 07:50 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  }
I doubt, this class is being called directly from somewhere else to run as a process or a command. In that case, we should keep it.

2022-05-20 09:04 UTC, Polpetta commented on store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
> +  }
Oh, I didn't know it. So ok, let them be here :/

2022-05-20 09:20 UTC, merged