feat: healthcheck
zextras/carbonio-mailbox pull request #401
Opened 2023-12-07 16:31 UTC by frisonisland

2023-12-08 14:16 UTC, sonersivri approved these changes

2023-12-11 08:55 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/health/ServiceDependency.java
> +
@keshavbhatt I would avoid using these variable in the parent class. Reason is I would like to keep it as simple as possible. I would **maybe** create a PollingServiceDependency abstract class extending ServiceDependency. But even then there are some methods, like doCheckStatus() that migth not work for every use case. 
Since we currently have only one ServiceDependency I would think about doing this refactor later (YAGNI) and for now leave the polling logic just in DatabaseServiceDependency

2023-12-11 10:17 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/health/ServiceDependency.java
> +
I was about to add SoapServletServiceDependency, but i agree if there is no such plan we can skip this for now.

2023-12-11 10:19 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/health/ServiceDependency.java
> +
Ty, no rush, let's check it together when you are available :)

2023-12-11 11:41 UTC, ppolito-zextras commented on store/src/main/java/com/zextras/mailbox/servlet/HealthResponse.java
> +    private HealthResponseBuilder() {
Why can't we leave the public constructor?

2023-12-11 11:41 UTC, ppolito-zextras commented on store/src/main/java/com/zextras/mailbox/servlet/HealthServlet.java
> +      case "/":
Talking about the IOException, the doGet method inherits Exceptions from the parent method. The try-catch block is not needed.

2023-12-11 11:41 UTC, ppolito-zextras commented on store/src/test/java/com/zextras/mailbox/health/DatabaseServiceDependencyTest.java
> +      throws ServiceException, SQLException {
SQLException is never thrown in this method, you can cancel it

2023-12-11 11:41 UTC, ppolito-zextras commented on store/src/main/java/com/zextras/mailbox/servlet/HealthResponse.java
> +  public HealthResponse(boolean ready, List<Dependency> dependencies) {
Pay attention that Dependency is defined lower in this class so it's visible only for the classes of this package, but this method is visible to any class

2023-12-11 11:43 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/servlet/HealthResponse.java
> +  public HealthResponse(boolean ready, List<Dependency> dependencies) {
Yes, IMHO there is no need to have them package-private, unless we want to enforce strict rules. Having them public won't hurt, same for private constructor and enforcing usage of static method newInstance()

2023-12-11 11:45 UTC, ppolito-zextras commented on store/src/test/java/com/zextras/mailbox/util/JettyServerFactory.java
The following variables can be set as final (servlets, filters, listeners and host)

2023-12-11 13:29 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/servlet/HealthServlet.java
> +      case "/":
It is considered a good practice to not throw exception in Servlet methods. 
see: https://rules.sonarsource.com/java/RSPEC-1989/

2023-12-11 13:29 UTC, keshavbhatt commented on store/src/main/java/com/zextras/mailbox/servlet/HealthResponse.java
> +    private HealthResponseBuilder() {
It can be. The idea is not to worry about how to create the builder itself + make the usages more expressive and readable.

2023-12-12 08:09 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/servlet/HealthServlet.java
> +      case "/":
Even if it is a good practice the issue is the IOException is already defined in the method.
At that point I would remove that. Same for others, else we should just do a big try{} catch{}

2023-12-12 09:47 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/health/ServiceDependency.java
> +
I've put back the old behavior

2023-12-12 10:35 UTC, keshavbhatt requested changes
I just ask if it is okay to rely on this endpoint in production to suggest if mailbox is healthy. I suggest to wait for addition of other required service dependencies.

2023-12-12 10:35 UTC, keshavbhatt commented on packages/appserver-service/carbonio-mailbox.hcl
> +    http      = "http://localhost:8080/service/health/ready"
I this it is premature to have this change at the moment. 
The rationale is that the current health endpoint readiness only reflects the readiness of the database, which in itself does not indicate the overall health of the mailbox.

2023-12-12 10:53 UTC, keshavbhatt approved these changes

2023-12-12 13:08 UTC, frisonisland commented on packages/appserver-service/carbonio-mailbox.hcl
> +    http      = "http://localhost:8080/service/health/ready"
Sorry if it sounded harsh, was not my intention at all, but I think it is a pity not use the endpoint + it's already an improvement over the original behavior. Also it will pass quite some time before we reach a fully mature health-check. By using it we can gain some feedback on its performance already + possible issues

2023-12-12 15:32 UTC, matteobaglini approved these changes

2023-12-12 16:34 UTC, merged