refactor: [CO-949] - move and load rights from resources
zextras/carbonio-mailbox pull request #428
Opened 2024-01-11 11:28 UTC by ppolito-zextras

- refactor RightManager to use AttributeManager
- move the rights files to resources
- made the RightManager load the rights from the resources

2024-01-11 13:23 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/account/accesscontrol/RightManager.java
> +    }
Move these classes out. They are not totally related to Rights, as reading content from a file or resource doesnn't have anything to do with rights.
Example: you can do new ResourceContentExtractor("/conf/rights") -> this could allow reading resources from the base path "/conf/rights".
Similarly, new FileContentExtractor("/conf/rights") -> reads from file system in base directory "/conf/rights".

2024-01-11 15:12 UTC, frisonisland requested changes

2024-01-11 15:12 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/account/accesscontrol/RightManagerTest.java
> +    Assertions.assertFalse(rightManager.getAllUserRights().isEmpty());
Not needed, below assertions already include these checks

2024-01-11 15:12 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/account/accesscontrol/RightManagerTest.java
> +  void shouldLoadRightsUsingSingleton() throws ServiceException {
Since this test is does not set zimbra_rights_directory, and value is empty by default, it uses resources.
Rename method to something like _shouldLoadRightsfromResourcesUsingSingleton_

2024-01-11 15:12 UTC, frisonisland commented on store/src/test/java/com/zimbra/cs/account/accesscontrol/RightManagerTest.java
> +class RightManagerTest {
We should add other singleton tests to check it works using filesystem.
However we must remember to destroy the singleton at the end of the test + reset the LC.zimbra_rights_directory.

2024-01-12 08:10 UTC, frisonisland commented on store/src/main/java/com/zimbra/cs/account/accesscontrol/RightManager.java
> +    }
Decided to not do this and opt for another solution

2024-01-12 10:23 UTC, keshavbhatt approved these changes

2024-01-12 10:37 UTC, frisonisland approved these changes

2024-01-12 11:52 UTC, merged