[CO-191] Cookie Safety
Zextras/carbonio-mailbox pull request #43
Opened 2022-05-31 10:41 UTC by keshavbhatt

### What's new:
**SameSiteAttribute** Utility class to set SameSite attribute of the Set-Cookie HTTP response header.

### What has changed:
The `ZM_AUTH_TOKEN` cookie has the `Secure` attribute set to true by default and the `SameSite` Attribute is set to `Lax`(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax) as requested to improve the web app security.

2022-06-06 08:07 UTC, frisonisland approved these changes

2022-06-07 15:16 UTC, Polpetta approved these changes

2022-06-07 15:23 UTC, frisonisland requested changes

2022-06-07 15:23 UTC, frisonisland commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
Wouldn't it be better to check value is "equal to" instead of "contains"? 
I'm saying this because what if the ";" symbol is missing before SameSite=Lax ?

2022-06-07 15:32 UTC, keshavbhatt commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
we can not check for equality since the Set-Cookie attribute value constains more than that. 


> I'm saying this because what if the ";" symbol is missing before SameSite=Lax ?

That won't happen, since we are adding `;` while re-constructing the new header in the addSameSiteAttribute method of the SameSiteAttribute utility class.

2022-06-07 15:55 UTC, keshavbhatt commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
> but we control the input

The input(key value pair are managed/added by the standard method of HttpServletResponse Class) and they take cares of the correct formatting while appending headers to the response object. They won't add extras `;` unless there are more attributes to appeded to the header. I checked that and I confirm. So don't worry :)

2022-06-07 16:09 UTC, frisonisland commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
Sorry, maybe I did not explain myself correctly. I mean that the header, after addSameSiteAttribute, should be equal to
"id=a3fWa; Max-Age=2592000, SameSite=Lax". Checking this we also confirm it's set as per RFC. Isn't it?
I'm not worried about HttpResponse adding extra ";"! I'm just talking about this class. 
See what I did

![image](https://user-images.githubusercontent.com/36330277/172428891-63a9d16d-5455-44f7-b30f-e1d5b4422541.png)

2022-06-07 16:30 UTC, keshavbhatt commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
Made the test case more specific to check the formatting. 
Thanks for drawing attention to this.

2022-06-07 16:31 UTC, keshavbhatt commented on common/src/java-test/com/zimbra/common/util/SameSiteAttributeTest.java
> +    assertThat(response.getHeader("Set-Cookie"), containsString("SameSite=Lax"));
> so I expect to have something like id=a3fWa; Max-Age=2592000; SameSite=Lax;

proper format is : `id=a3fWa; Max-Age=2592000; SameSite=Lax`
no `;` at end unless we have more k/v pairs to add.

2022-06-08 07:11 UTC, frisonisland requested changes

2022-06-08 07:11 UTC, frisonisland commented on common/src/java/com/zimbra/common/util/SameSiteAttribute.java
> +    }
I checked HttpServletResponse interface and it seems that the **getHeaders()** method returns a list of header values (not headers). Also the addHeader() method will add values to a header, so this is what I would do:
```suggestion
    if (!(Objects.isNull(response.getHeader(SET_COOKIE_HEADER)))) {
      response.addHeader(SET_COOKIE_HEADER, "SameSite=" + sameSiteValue);
    }
```
The result of my suggestion should be the value "SameSite=something" added to Set-Cookie header.
**I fear the solution you proposed may add a "SameSite=Lax" to each value of the header** (e.g.: Set-Cookie: id=1; SameSite=Lax; Max-Value=b; SameSite=Lax).
**Unfortunately the Unit Test is not able to show and test if this is the case, because MockHttpServletResponse does not implement all methods the right way.** If possible I would check with a "real" HttpServletResponse (IT)

2022-06-08 07:46 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/util/SameSiteAttribute.java
> +    }
I will test it to see if it works.

2022-06-08 08:06 UTC, keshavbhatt commented on common/src/java/com/zimbra/common/util/SameSiteAttribute.java
> +    }
It doesn't work. 
> I fear the solution you proposed may add a "SameSite=Lax" to each value of the header 
It won't :) we have the checks are in place. 
The provided solution is tested and fulfills the requirements already.

2022-06-08 08:14 UTC, frisonisland commented on common/src/java/com/zimbra/common/util/SameSiteAttribute.java
> +    }
> It won't :) we have the checks are in place. The provided solution is tested and fulfills the requirements already.
There is only a test with a MockHttpServletResponse.
To fulfill the requirements we need a test with a real HttpResponse and a Set-Cookie header with multiple values

2022-06-08 09:06 UTC, frisonisland commented on common/src/java/com/zimbra/common/util/SameSiteAttribute.java
> +    }
We checked together that the implementation result is as expected!
It will just be a plus if we could test SameSiteAttribute class against jetty Response class! Thanks :)

2022-06-08 09:07 UTC, frisonisland approved these changes
Everything works as expected. As I said it would just be a plus to test against a real server (spin-up) or just against Jetty Response class

2022-06-08 09:39 UTC, merged