refactor: [CO-1046] embedded jetty
zextras/carbonio-mailbox pull request #490
Opened 2024-04-15 12:49 UTC by frisonisland

Adds support for embedded jetty with same customization as defined in https://github.com/zextras/carbonio-appserver/blob/main/appserver/conf/jetty/jetty.xml.production.

Benefits:
- can start mailbox locally with same configuration
- full control over startup process
- simplifies deployment
- removes risk of LinkageError caused by common dependencies used in Jetty startup and application

2024-07-02 11:13 UTC, M0Rf30 requested changes

2024-07-02 11:13 UTC, M0Rf30 commented on packages/directory-server/PKGBUILD
> -postinst__rocky_9() {
Why?
there are some different behaviours between rhel8 and rhel9

2024-07-02 11:13 UTC, M0Rf30 commented on packages/mailbox-jar/PKGBUILD
> +pkgdesc="Carbonio Mailbox Jars"
is this new package really needed?

2024-07-03 07:35 UTC, keshavbhatt commented on store/conf/web.xml
>  <web-app xmlns="http://java.sun.com/xml/ns/j2ee"
Hi @frisonisland, is this file intended to be used in production? I am asking since now i see 3 files
- web.xml
- web-dev.xml
- web.xml.production

2024-07-03 07:38 UTC, keshavbhatt commented on store/pom.xml
> +      <version>9.4.48.v20220622</version>
@frisonisland  This also means we do not need `carbonio-jetty-distribution` anymore right?

2024-07-03 07:47 UTC, keshavbhatt approved these changes

2024-07-04 07:12 UTC, frisonisland commented on store/conf/web.xml
>  <web-app xmlns="http://java.sun.com/xml/ns/j2ee"
Thanks, I will check it again. This branch is so long-lived that I can't recall why this file is here

2024-07-04 07:20 UTC, frisonisland commented on store/conf/web.xml
>  <web-app xmlns="http://java.sun.com/xml/ns/j2ee"
Ok, I found it is used by the jetty-maven-plugin for local development purposes. However this file was always there in the repo since before we introduced the plugin.
I think if we manage to merge this PR then we can get rid of maven jetty plugin, since you can run the mailbox with a Main class, and maybe get rid of this web.xml.

2024-07-04 07:21 UTC, frisonisland commented on packages/directory-server/PKGBUILD
> -postinst__rocky_9() {
Updated and also aligned appserver.service file. There are no changes regarding directory-server pkgbuild anymore

2024-07-04 07:24 UTC, frisonisland commented on packages/mailbox-jar/PKGBUILD
> +pkgdesc="Carbonio Mailbox Jars"
We discussed and the reason is this package ships all mailbox jars. It is different from "appserver".
Appserver is a package that "ships" these jars + service definition + other things to make a whole node mailbox. Appserver also might not be limited to the mailbox

2024-07-04 07:25 UTC, frisonisland commented on store/pom.xml
> +      <version>9.4.48.v20220622</version>
Correct, carbonio-jetty-distribution is part of carbonio-thirds if I'm not mistaken and can be removed. Even if installed, it will not cause any troubles since it will be unused and the new jar classpath will be different from the Jetty one.

2024-07-04 08:23 UTC, matteobaglini commented on build_packages.sh
> +if [[ -z $OS ]]
Hi @frisonisland, how about providing a default value for the OS instead of blocking execution? In the end most of our VMs are all Ubuntu. What do you think?

2024-07-04 08:25 UTC, frisonisland commented on build_packages.sh
> +if [[ -z $OS ]]
Agree

2024-07-04 08:36 UTC, matteobaglini commented on store/src/main/java/com/zextras/mailbox/LikeXmlJettyServer.java
> +// Plus we adopted the same variables used in https://github.com/zextras/carbonio-appserver/blob/main/appserver/conf/jetty/jetty.xml.production
Hi @frisonisland, minor note: if I'm not wrong this link will be broken once this PR is merged and released. Better to point to a specific tag instead of main, right?

2024-07-04 08:43 UTC, matteobaglini commented on store/src/test/java/com/zextras/mailbox/LikeXmlJettyServerTest.java
> +  void shouldCreateJettyServer() throws InstantiationException {
Hi @frisonisland , this test is big and generic. We could divide it by groups of assertions: a test for userConnector, another for adminConnector, etc. and centralize the mock setup part.

2024-07-04 08:46 UTC, matteobaglini approved these changes

2024-07-04 08:53 UTC, matteobaglini commented on store/src/test/java/com/zextras/mailbox/SampleLocalMailbox.java
> +    inMemoryLdapServer.initializeBasicData();
Hi @frisonisland, I don't like calling `initializeBasicData` after `start`.
I propose:
- if `initializeBasicData` is a mandatory step invoke it directly inside start.
- If it is optional let put a new `withInitializeBasicData` method in the Builder and the invoke or not the logic in the `start`.

2024-07-04 15:04 UTC, frisonisland commented on store/src/main/java/com/zextras/mailbox/LikeXmlJettyServer.java
> +// Plus we adopted the same variables used in https://github.com/zextras/carbonio-appserver/blob/main/appserver/conf/jetty/jetty.xml.production
Right, updated

2024-07-04 15:10 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/SampleLocalMailbox.java
> +    inMemoryLdapServer.initializeBasicData();
I agree but I have to check other tests since it seems the two methods are public and used in different scenarios

2024-07-04 15:23 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/LikeXmlJettyServerTest.java
> +  void shouldCreateJettyServer() throws InstantiationException {
Do you mean having different tests with same setup but different assert?
Like:
```suggestion
  @BeforeEach
  void setUp() {
    config = mock(Config.class);
    localServer = mock(com.zimbra.cs.account.Server.class);
    when(config.getHttpNumThreads()).thenReturn(20);
    when(config.getMailboxdSSLProtocols()).thenReturn(new String[] {"TLS1.2"});
    when(config.getSSLExcludeCipherSuites()).thenReturn(new String[] {"^TLS_RSA_.*"});
    when(config.getSSLIncludeCipherSuites()).thenReturn(new String[] {});
    when(config.getHttpConnectorMaxIdleTimeMillis()).thenReturn(3000);
  }

  @Test
  void shouldCreateJettyServer_withUserConnector() throws InstantiationException {
    final Server server = new Builder(config, localServer).build();
    
    final Connector[] connectors = server.getConnectors();
    final Connector userConnector = connectors[0];
    assertEquals("http/1.1", userConnector.getProtocols().get(0));
    assertEquals(3000, userConnector.getIdleTimeout());
  }
```

2024-07-04 15:37 UTC, M0Rf30 requested changes

2024-07-04 15:44 UTC, frisonisland commented on packages/appserver-service/carbonio-appserver.service
> +            -Dfile.encoding=UTF-8 \
I applied an shfmt. However we do not use such usually in our repos and do not really check linting anymore

2024-07-04 15:48 UTC, frisonisland commented on store/src/test/java/com/zextras/mailbox/LikeXmlJettyServerTest.java
> +  void shouldCreateJettyServer() throws InstantiationException {
Applied similar changes

2024-07-04 15:48 UTC, M0Rf30 approved these changes

2024-07-04 16:22 UTC, merged