Password policy without LDAP attribute
Zextras/carbonio-mailbox pull request #5
Opened 2022-01-21 19:50 UTC by keshavbhatt

user attribute cannot be part of their password

added new password policy which will prevent users from adding their
personal data in their password string

this policy is enforced by default

2022-01-25 10:37 UTC, Polpetta commented
See https://github.com/Zextras/carbonio-mailbox/pull/1 for reference

2022-01-25 10:51 UTC, frisonisland approved these changes

2022-01-25 10:52 UTC, Polpetta requested changes
Tests need to be fixed, and TLD email considered too. I'd consider the following email, that should have a password that respectively contains or not a sensitive data in it (so for each email address 2 tests cases):
* `emily@example`
* `emily@example.com`
* `emily.surname@example`
* `emily.surname@example.com`

Note that with Junit you can use Parameterized Tests to help you out with the same test on a different set of data: https://www.baeldung.com/parameterized-tests-junit-5. Please check out if it is worth doing that way.

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +    //Account acct = Provisioning.getInstance().get(AccountBy.id, "natalie.leesa@example.com");
You can remove this line
```suggestion
```

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +        Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
Why this? You can simply do this:

```suggestion
    Optional<String> sName = Optional.ofNullable(acct.getAttr(Provisioning.A_sn));
    Optional<String> cName = Optional.ofNullable(acct.getAttr(Provisioning.A_cn));
    Optional<String> initials = Optional.ofNullable(acct.getAttr(Provisioning.A_initials));
    Optional<String> email = Optional.ofNullable(acct.getAttr(Provisioning.A_mail));
```

KISS

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +    MailboxTestUtil.initServer();
Don't initialize stuff in the `static` field. This will lead to problems once all tests are initialized this way. If you are going to start stuff please start it in `@Before` block. It is slower I know, but Java has a hard limit for static memory entries and unfortunately by doing this you're polluting this space, resulting in a KABOM once we reach a good number of tests.

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
```suggestion
  @Before
  public void setUp() throws Exception {
    MailboxTestUtil.initServer();
    Provisioning prov = Provisioning.getInstance();
    HashMap<String,Object> attrs;
    attrs = new HashMap<>();
    attrs.put(Provisioning.A_zimbraId, UUID.randomUUID().toString());
    attrs.put(Provisioning.A_sn, "Leesa");
    attrs.put(Provisioning.A_cn, "Natalie Leesa");
    attrs.put(Provisioning.A_initials, "James");
    attrs.put(Provisioning.A_mail, "natalie.leesa@example.com");
    prov.createAccount("natalie.leesa@example.com", "testpassword", attrs);
  }
```

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
I don't understand this part of the test. Here you're supposed to call the real method, to test if it respects its contract (provided with a given input it gives back the right output). Why did you copied the production code here?

2022-01-25 10:52 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +      Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
Check out `provisioningTest`

2022-01-25 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +import org.junit.Test;
I see `junit4` being used here. Can't we use `junit5` already?

2022-01-25 10:52 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +    };
Have you considered the case where the email is `something@example`? This is a valid email address, since top level domain can be email address. So for example, `lamborghini` has its own TLD, so `milano@lamborghini` is a valid email address (for instance https://milano.lamborghini/ is a valid website, and they have their own email address too).

Please keep this in consideration too.

2022-01-25 10:52 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +          "password contains username or other personal data: " + matchedSensitivePart.get(),
`password` here is lowercase because all the other errors are like that? Or is it `Password`?

2022-01-25 10:54 UTC, Polpetta commented
As a final note, please stick to this PR, don't close it otherwise all the history of the changes I requested will be lost and I'll have to manually keep track of them.
Push on it as much as you need, we'll squash everything anyway so only one commit will come out of this :blush:

2022-01-25 11:02 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +    //Account acct = Provisioning.getInstance().get(AccountBy.id, "natalie.leesa@example.com");
Sure.

2022-01-25 11:06 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +        Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
I don't want to deal with noSuchElementException in my code below these initializations. 
Obviously there could be 1 thousand other ways to keep it simple, but this one works for me. :)

2022-01-25 11:08 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +    MailboxTestUtil.initServer();
I got "java.lang.Exception: Method init() should be static" error when i tried to do it without init,

2022-01-25 11:11 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
? In the future we might have more tests in this class and the idea is to use MailboxTestUtil.clearData(); to provide clear environment for each test.

2022-01-25 11:13 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
I know :) that's why i used reference in java doc to that particular method. 

I cannot initialize LdapProvisioning class just to perform a test on its helper method. That's why it was done like this. 
I might follow the approach you asking for but there i would require to create a separate class with just one method.

2022-01-25 11:14 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +      Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
What ?

2022-01-25 11:16 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +import org.junit.Test;
I don't want to introduce another dependency just to write tests for this case only. I found existing junit4 that is adopted by this project everywhere sufficient enough to test my code. We might consider adding jUnit5 and rewriting all tests to achieve this goal.

2022-01-25 11:18 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +    };
Yes, I have considered.

Also https://www.icann.org/en/announcements/details/new-gtld-dotless-domain-names-prohibited-30-8-2013-en

2022-01-25 11:22 UTC, keshavbhatt commented
> As a final note, please stick to this PR, don't close it otherwise all the history of the changes I requested will be lost and I'll have to manually keep track of them. Push on it as much as you need, we'll squash everything anyway so only one commit will come out of this blush

I understand your concerns. It's an internal thing that forced me to create another PR. 
I understand how git works at least I know the basics :)
All feedbacks are appritiated.

2022-01-25 13:17 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
I am now using the direct invoke to the method, at cost of making it public and static

2022-01-25 13:17 UTC, keshavbhatt reviewed
updated the PR with all necessary changes

2022-01-26 10:47 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +    MailboxTestUtil.initServer();
Ok, then keep it in the static field and let's hope for the best

2022-01-26 10:48 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +   */
This is not something to fix but is a tip: javadoc in tests is not mandatory! It will help people in the future to maintain this code tho

2022-01-26 10:51 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +      Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
I mean I don't understand why `Optional.of(Optional.ofNullable(...).orElse(""))` when you can write this way:
```suggestion
    Optional<String> sName = Optional.ofNullable(acct.getAttr(Provisioning.A_sn));
    Optional<String> cName = Optional.ofNullable(acct.getAttr(Provisioning.A_cn));
    Optional<String> initials = Optional.ofNullable(acct.getAttr(Provisioning.A_initials));
    Optional<String> email = Optional.ofNullable(acct.getAttr(Provisioning.A_mail));
```

The behavior should be the same

Alternatively you can do the following:
```suggestion
    String sName = Optional.ofNullable(acct.getAttr(Provisioning.A_sn)).orElse("");
    String cName = Optional.ofNullable(acct.getAttr(Provisioning.A_cn)).orElse("");
    String initials = Optional.ofNullable(acct.getAttr(Provisioning.A_initials)).orElse("");
    String email = Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse("");
```

If you want the "fallback" value to be `""`

2022-01-26 10:52 UTC, Polpetta commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +  }
Yeah. Anyway as we discussed it is not possible to have it in the non-static block, so I'll resolve this point

2022-01-26 10:54 UTC, Polpetta commented
> updated the PR with all necessary changes

Yep, I answered to you comments, all the other stuff I marked it as resolved

2022-01-27 08:53 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
> +      Optional.of(Optional.ofNullable(acct.getAttr(Provisioning.A_mail)).orElse(""));
Offcourse.

2022-01-27 08:55 UTC, keshavbhatt commented on store/src/java-test/com/zimbra/cs/account/ldap/LdapProvisioningTest.java
> +   */
Will avoid them in the future.
Thanks

2022-01-28 11:44 UTC, Polpetta approved these changes
lgtm :+1:

2022-01-28 12:24 UTC, merged