Co 303 ci tests
Zextras/carbonio-mailbox pull request #53
Opened 2022-06-16 07:20 UTC by frisonisland

### Goal

Add Junit report and JaCoCo report coverage

### What's changed

- added **jacoco-common.xml** to load and download JaCoCo plugin
- added **junit-common.xml** to load and download Junit plugin
- **removed old Emma plugin** coverage build-common.xml
- **wrapped junit tests with jacoco** agent in build-common.xml
- add ant target to merge multiproject JaCoCo coverage
- Jenkinsfile: jacoco and junit publish reports 
- Jenkinsfile: run all tests (unit & IT) when TEST param enabled

2022-06-16 07:45 UTC, keshavbhatt approved these changes

2022-06-16 07:47 UTC, M0Rf30 approved these changes
Everything looks good to me, my main suggestion is related to formatting of build.xml and build-common.xml. In the past I used a specific xml formatter. If the tool is the same across all the team members and I'm the singularity I will adopt your tool, otherwise I can submit a commit, queued to this and only for the mentioned files. Let me know

2022-06-16 09:24 UTC, frisonisland commented
> Everything looks good to me, my main suggestion is related to formatting of build.xml and build-common.xml. In the past I used a specific xml formatter. If the tool is the same across all the team members and I'm the singularity I will adopt your tool, otherwise I can submit a commit, queued to this and only for the mentioned files. Let me know

Hey @M0Rf30 we are using this config: https://github.com/Zextras/carbonio-mailbox/blob/main/.pre-commit-config.yaml
We can add an xml linter if you want. 
Right now I'm using the IDE formatter (should be this: https://google.github.io/styleguide/intellij-java-google-style.xml)

2022-06-16 09:44 UTC, M0Rf30 commented
> > Everything looks good to me, my main suggestion is related to formatting of build.xml and build-common.xml. In the past I used a specific xml formatter. If the tool is the same across all the team members and I'm the singularity I will adopt your tool, otherwise I can submit a commit, queued to this and only for the mentioned files. Let me know
> 
> Hey @M0Rf30 we are using this config: https://github.com/Zextras/carbonio-mailbox/blob/main/.pre-commit-config.yaml We can add an xml linter if you want. Right now I'm using the IDE formatter (should be this: https://google.github.io/styleguide/intellij-java-google-style.xml)

got it. I will sync with you and with the suggested style. thanks

2022-06-16 09:58 UTC, Polpetta requested changes

2022-06-16 09:58 UTC, Polpetta commented on Jenkinsfile
> +        stage("Test all with coverage (allow failure)") {
If you want you can mark the build "stable" with % of test failed, so that from now on we try to diminish that number

2022-06-16 10:02 UTC, frisonisland commented on Jenkinsfile
> +        stage("Test all with coverage (allow failure)") {
> If you want you can mark the build "stable" with % of test failed, so that from now on we try to diminish that number

I didn't do it because I don't have an idea of how much % we need, I think we should reason about that and do it in next iterations

2022-06-16 10:07 UTC, frisonisland commented
> Also, I'm throwing an idea here, how much difficult would be to use Junit5 here?

A lot more work, I was taking care about it here: https://github.com/Zextras/carbonio-mailbox/tree/fix/working-tests
Reason is that we have some issues in downloading transitive dependencies and I found we need to update dependency manager logic (Ivy) to fully use Junit5.
Of course feel free to work on that branch and improve it!

2022-06-16 13:42 UTC, frisonisland commented on Jenkinsfile
> +        stage("Test all with coverage (allow failure)") {
We solved this IRL :slightly_smiling_face: . Junit plugin does not allow for stable/unstable build based on % failure. We discussed several options we can use in the future to achieve this goal. 
Please @Polpetta mark it as solved if you're satisfied :wink:

2022-06-17 09:55 UTC, Polpetta commented
> > Also, I'm throwing an idea here, how much difficult would be to use Junit5 here?
> 
> A lot more work, I was taking care about it here: https://github.com/Zextras/carbonio-mailbox/tree/fix/working-tests Reason is that we have some issues in downloading transitive dependencies and I found we need to update dependency manager logic (Ivy) to fully use Junit5. Of course feel free to work on that branch and improve it!

Cool cool!

2022-06-17 09:55 UTC, Polpetta approved these changes

2022-06-17 10:00 UTC, merged