Add new ldap attribute for Carbonio Chats meeting recording feature
Zextras/carbonio-mailbox pull request #56
Opened 2022-06-24 13:00 UTC by nomanAli95

A new ldap attribute has been added on account, cos and domain level to enable or disable the meeting recording functionality on Carbonio Chats.

2022-06-24 13:18 UTC, keshavbhatt commented
LGTM, we also require support PR for carbonio-ldap-utilities to complete this.

2022-06-24 13:37 UTC, nomanAli95 commented
> LGTM, we also require support PR for carbonio-ldap-utilities to complete this.

Yeah I know, I'm just waiting to merge this one to get the commit hash and use it to generate the correct timestamp for the required file name in carbonio-ldap-utilities

2022-06-24 13:58 UTC, keshavbhatt commented
> I'm just waiting to merge this one to get the commit hash

No need to wait, just use the `git log -1 --pretty=format:%at store/conf/attrs/attrs.xml` in your mailbox branch and use that timestamp.

2022-06-24 15:39 UTC, keshavbhatt approved these changes

2022-06-27 07:05 UTC, frisonisland commented on common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
> + *
Ok, it's not just this file, also all other ZAttr* files are modified by generate-getters.
Anyway I agree, let's check on it next time :+1:

2022-06-27 08:24 UTC, Polpetta requested changes
I don't know if those files are effectively auto-generated, but if not there are a bunch of missing parenthesis!

2022-06-27 08:24 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ZAttrCos.java
> +    if (attrs == null) attrs = new HashMap<String,Object>();
If without parenthesis

2022-06-27 08:24 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ZAttrCos.java
> +    if (attrs == null) attrs = new HashMap<String,Object>();
If without parenthesis

2022-06-27 08:24 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ZAttrAccount.java
> +      if (attrs == null) attrs = new HashMap<String,Object>();
if without parenthesis

2022-06-27 08:24 UTC, Polpetta commented on store/src/java/com/zimbra/cs/account/ZAttrDomain.java
> +        if (attrs == null) attrs = new HashMap<String,Object>();
Same here

2022-06-27 08:38 UTC, keshavbhatt commented
> I don't know if those files are effectively auto-generated, but if not there are a bunch of missing parenthesis!

just verified with auto generator, it also likes no parentheses;

2022-06-27 08:42 UTC, nomanAli95 commented
> > I don't know if those files are effectively auto-generated, but if not there are a bunch of missing parenthesis!
> 
> just verified with auto generator, it also likes no parentheses;

If you want I can add them, no problem

2022-06-27 08:56 UTC, keshavbhatt commented
> > > I don't know if those files are effectively auto-generated, but if not there are a bunch of missing parenthesis!
> > 
> > 
> > just verified with auto generator, it also likes no parentheses;
> 
> If you want I can add them, no problem

Will leave it up to you. I am okay with this exceptional case(We prefer parenthesis). We will be using the Auto generator in the future so no issues.

2022-06-27 10:13 UTC, frisonisland approved these changes

2022-06-27 10:35 UTC, merged

2022-06-27 12:30 UTC, Polpetta commented
I guess...we could merge them anyway :sweat_smile: