Chore/co 326 remove imapd
Zextras/carbonio-mailbox pull request #74
Opened 2022-08-03 13:42 UTC by frisonisland

### What's changed

- ImapDaemon class has been removed.
- Some other classes have been modified because they used ImapDaemon.
- Imapd related attributes (4 of them) have been deprecated, and getters have been generated (except zimbraAuthFallbackToLocal to avoid regression).

2022-08-25 08:59 UTC, keshavbhatt requested changes
Dropped a few comments,
Please check if we still require store-conf/conf/imapd.log4j.properties after these changes. 

Everything else LGTM.

2022-08-25 10:19 UTC, frisonisland commented on soap/src/java/com/zimbra/soap/admin/type/CacheSelector.java
> -  @XmlAttribute(name = AdminConstants.A_IMAPSERVERS /* imapServers */, required = false)
Ty @keshavbhatt , I removed after double-checking it was unused. 
Also remove imapd.log4j.properties as it was loaded inside ImapDaemon class and that has been removed.

2022-08-25 13:26 UTC, keshavbhatt approved these changes

2022-08-26 13:49 UTC, Polpetta approved these changes
Is it a big problem to add `@Deprecated(since= "22.9.0")` on top of methods?

2022-08-29 08:50 UTC, frisonisland commented
> Is it a big problem to add `@Deprecated(since= "22.9.0")` on top of methods?

I'm on you with this, but that code is autogenerated and atm it's like that :/. 
We can take care about when we will improve auto-generators

2022-09-13 10:44 UTC, merged