feat: [CO-359] add ability to preview attachments in shared mailbox folders
Zextras/carbonio-mailbox pull request #77
Opened 2022-08-10 11:09 UTC by keshavbhatt

**Key changes:** 
- Preview servlet now can preview attachments that are part of shared email folders

2022-08-10 15:37 UTC, frisonisland requested changes
Just left a note about managing response error. 
My suggestion is to let the error flow up until the doGet() and only then set the error if returned status is failure.

2022-08-10 15:37 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              encodeClientBuilderRequest(resp, authToken, clientBuilder, getRequest).get();
I have just a note **about passing down the response element as a parameter**: I would avoid it and **instead keep the response error logic at top level (in the doGet method)**.
I'm ok with the "sendError" method to manipulate the response, although I prefer the original resp.sendError of HttpServletResponse interface, but **passing down the response to each method just and modifying its status for each failure will inevitably result in confusion at some point** because we will not be able to trace where the error happened without proper debugging.

I would suggest instead in the doGet, for each method response, calling isFailure() and then set the response error.

Edit: the flow is:
doGet() -> getAttachment() -> encodeClientBuilderRequest() -> getMailHostUrl(), and to each of them the response is being passed.
But in the end **the response is not being used to make any http calls, but just to catch the failure and set the error.**
**Instead let the error flow up, until we catch it in the doGet()**

2022-08-11 10:38 UTC, frisonisland commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              encodeClientBuilderRequest(resp, authToken, clientBuilder, getRequest).get();
Ok, solved IRL, we will take care in next related PR, the functionality is there

2022-08-11 10:39 UTC, frisonisland approved these changes

2022-08-11 10:40 UTC, keshavbhatt commented on store/src/java/com/zimbra/cs/service/PreviewServlet.java
> +              encodeClientBuilderRequest(resp, authToken, clientBuilder, getRequest).get();
I agree with your proposal and I decided to add it to the next PR, which is also connected to something similar. I stated why in chat :wink:

2022-08-11 12:03 UTC, Polpetta approved these changes
LGTM. Remember next time to put finals into variables declaration if their pointers don't need to change :+1:

2022-08-11 13:36 UTC, merged